In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df1 = pd.read_csv("../data/cars_data.csv")
df2 = pd.read_csv("../data/cars_data2.csv")

In [3]:
df1.head()

,Name,Price,Năm SX,Tình trạng,Xuất xứ,Km đã đi,Tỉnh thành,Quận huyện,Hộp số,Nhiên liệu,...,Hỗ trợ trả góp,Bảo hành máy móc động cơ 3-6 tháng,Một chủ từ đầu,Full lịch sử hãng,"Thủ tục trọn gói (Rút hồ sơ,sang tên,...)",Model xe mới,Xe có nhiều đồ chơi,Hỗ trợ/cam kết từ người bán,Có xuất hóa đơn,Còn bảo hiểm thân vỏ
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ,Màu ngoại thất,Màu nội thất
0,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz GLC \...,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,Trắng,Đen
1,Xe \n\t\t\t\n\t\t\t\t\t\t\tKia Sedona \n\t\t\t...,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,Trắng,Nâu
2,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz C cla...,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Đen
3,Xe \n\t\t\t\n\t\t\t\t\t\t\tSuzuki XL7 \n\t\t\t...,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,Trắng,Nâu
4,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz C cla...,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Kem

### clean df1

In [5]:
for i in df1.columns :
    print(f"{i} : {df1[i].nunique()}")

Name : 1119
Price : 584
Năm SX : 24
Tình trạng : 1
Xuất xứ : 2
Km đã đi : 312
Tỉnh thành : 42
Quận huyện : 91
Hộp số : 2
Nhiên liệu : 4
Số tiền vay : 1
Thời gian vay : 1
Lãi xuất (%) : 1
Loại hình : 1
Giá trị xe muốn mua : 1
Kiểu dáng : 11
Hỗ trợ trả góp : 3
Bảo hành máy móc động cơ 3-6 tháng : 2
Một chủ từ đầu : 2
Full lịch sử hãng : 3
Thủ tục trọn gói (Rút hồ sơ,sang tên,...) : 3
Model xe mới : 3
Xe có nhiều đồ chơi : 3
Hỗ trợ/cam kết từ người bán : 3
Có xuất hóa đơn : 1
Còn bảo hiểm thân vỏ : 1

In [6]:
df1 = df1.loc[:, df1.nunique() > 1]

In [7]:
threshold = 0.5
df1 = df1.loc[:, df1.isnull().mean() < threshold]

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1490 non-null   object
 1   Price       1490 non-null   object
 2   Năm SX      1490 non-null   int64
 3   Xuất xứ     1483 non-null   object
 4   Km đã đi    1485 non-null   object
 5   Tỉnh thành  1490 non-null   object
 6   Quận huyện  1285 non-null   object
 7   Hộp số      1490 non-null   object
 8   Nhiên liệu  1490 non-null   object
 9   Kiểu dáng   1352 non-null   object
dtypes: int64(1), object(9)
memory usage: 116.5+ KB

In [9]:
df1.rename(columns={
    'Name': 'Name',
    'Price': 'Price',
    'Năm SX': 'Year',
    'Kiểu dáng': 'Body_Type',
    'Xuất xứ': 'Origin',
    'Km đã đi': 'Mileage',
    'Tỉnh thành': 'Province',
    'Quận huyện': 'District',
    'Hộp số': 'Transmission',
    'Nhiên liệu': 'Fuel_Type'
}, inplace=True)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          1490 non-null   object
 1   Price         1490 non-null   object
 2   Year          1490 non-null   int64
 3   Origin        1483 non-null   object
 4   Mileage       1485 non-null   object
 5   Province      1490 non-null   object
 6   District      1285 non-null   object
 7   Transmission  1490 non-null   object
 8   Fuel_Type     1490 non-null   object
 9   Body_Type     1352 non-null   object
dtypes: int64(1), object(9)
memory usage: 116.5+ KB

In [11]:
df1.isna().sum()

Name              0
Price             0
Year              0
Origin            7
Mileage           5
Province          0
District        205
Transmission      0
Fuel_Type         0
Body_Type       138
dtype: int64

In [12]:
df1.head()

,Name,Price,Year,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,NaN
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,SUV
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Sedan

1. Name

In [13]:
df1.Name.head()

0          Mercedes-Benz GLC 200 4Matic 2021
1                   Lexus RX 350 Luxury 2016
2                 Kia Sonet 1.5 Premium 2024
3     Ford Everest Titanium 2.0L AT 4WD 2019
4    Mercedes-Benz S450 Limited Edition 2020
Name: Name, dtype: object

In [14]:
df1["Brand"] = df1["Name"].str.strip().str.split().str[0]

In [15]:
df1.head()

,Name,Price,Year,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type,Brand
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,NaN,Mercedes-Benz
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,SUV,Lexus
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV,Ford
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Sedan,Mercedes-Benz

2.Price

In [16]:
df1.Price.head()

0    1 tỉ 389 triệu
1    2 tỉ 099 triệu
2         585 triệu
3         810 triệu
4    2 tỉ 398 triệu
Name: Price, dtype: object

In [17]:
def convert_price(price_str):
    price_str = price_str.strip().lower()
    price = 0
    if "tỉ" in price_str:
        parts = price_str.split("tỉ")
        ty = int(parts[0].strip())
        price += ty * 1_000_000_000
        if "triệu" in parts[1]:
            trieu = int(parts[1].replace("triệu", "").strip())
            price += trieu * 1_000_000
    elif "triệu" in price_str:
        trieu = int(price_str.replace("triệu", "").strip())
        price += trieu * 1_000_000
    return price

df1["price_num"] = df1["Price"].apply(convert_price)

In [18]:
df1.head()

,Name,Price,Year,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type,Brand,price_num
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,NaN,Mercedes-Benz,1389000000
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,SUV,Lexus,2099000000
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia,585000000
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV,Ford,810000000
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Sedan,Mercedes-Benz,2398000000

In [19]:
df1 = df1.drop("Price",axis=1)

In [20]:
Q1 = df1['price_num'].quantile(0.25)
Q3 = df1['price_num'].quantile(0.75)
IQR = Q3 - Q1

df1 = df1[(df1['price_num'] >= Q1 - 1.5 * IQR) & (df1['price_num'] <= Q3 + 1.5 * IQR)]

3.Year

In [21]:
df1.Year.head()

0    2021
2    2024
3    2019
6    2016
7    2017
Name: Year, dtype: int64

In [22]:
df1.Year = df1.Year.astype(int)

In [23]:
df1["age"] = 2025 - df1["Year"]

4.Body_Type

In [24]:
df1.Body_Type.unique()

array([nan, 'Crossover', 'SUV', 'Sedan', 'Bán tải', 'MPV', 'Hatchback',
       'Van/Minivan', 'Xe tải', 'Sport Car', 'Convertible', 'Coupe'],
      dtype=object)

In [25]:
df1.Body_Type.value_counts()

Body_Type
SUV            406
Sedan          402
Hatchback      108
Bán tải        101
MPV             99
Van/Minivan     36
Crossover       34
Xe tải           8
Sport Car        3
Convertible      3
Coupe            2
Name: count, dtype: int64

In [26]:
df1.loc[df1["Body_Type"].isna() , "Body_Type"] = "Other"

5.Origin

In [27]:
df1.Origin.isna().sum()

7

In [28]:
df1.Origin.value_counts()

Origin
Trong nước    824
Nhập khẩu     484
Name: count, dtype: int64

In [29]:
df1.loc[df1.Origin.isna(),"Origin"] = "Other"

In [30]:
df1.Origin.value_counts()

Origin
Trong nước    824
Nhập khẩu     484
Other           7
Name: count, dtype: int64

6.Mileage

In [31]:
df1.Mileage.head()

0    55.555 km
2     1.000 km
3        04 km
6    90.000 km
7    57.225 km
Name: Mileage, dtype: object

In [32]:
df1.Mileage.isna().sum()

5

In [33]:
df1.Mileage.describe()

count          1310
unique          288
top       60.000 km
freq             58
Name: Mileage, dtype: object

In [34]:
df1.loc[df1["Mileage"].isna(),"Mileage"] = "60.000 km"

In [35]:
df1['mileage_num'] = df1['Mileage'].str.replace('.', '', regex=False) \
                                  .str.replace(' km', '', regex=False) \
                                  .astype(int)

In [36]:
df1.head()

,Name,Year,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type,Brand,price_num,age,mileage_num
0,Mercedes-Benz GLC 200 4Matic 2021,2021,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Other,Mercedes-Benz,1389000000,4,55555
2,Kia Sonet 1.5 Premium 2024,2024,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia,585000000,1,1000
3,Ford Everest Titanium 2.0L AT 4WD 2019,2019,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV,Ford,810000000,6,4
6,Mercedes-Benz GLC 300 4Matic 2016,2016,Nhập khẩu,90.000 km,Hà Nội,Tây Hồ,Số tự động,Máy xăng,SUV,Mercedes-Benz,885000000,9,90000
7,Mazda 6 2.0 AT 2017,2017,Trong nước,57.225 km,Hải Phòng,An Lão,Số tự động,Máy xăng,Sedan,Mazda,440000000,8,57225

In [37]:
df1 = df1.drop("Mileage",axis=1)

In [38]:
df1.columns

Index(['Name', 'Year', 'Origin', 'Province', 'District', 'Transmission',
       'Fuel_Type', 'Body_Type', 'Brand', 'price_num', 'age', 'mileage_num'],
      dtype='object')

7.Province

In [39]:
df1.Province.head()

0       Tp.HCM
2       Hà Nội
3       Tp.HCM
6       Hà Nội
7    Hải Phòng
Name: Province, dtype: object

In [40]:
df1.Province.isna().sum()

0

In [41]:
df1.Province.nunique()

42

8.District

In [42]:
df1.District.isna().sum()

197

In [43]:
df1.District.describe()

count         1118
unique          89
top       Cầu Giấy
freq           132
Name: District, dtype: object

In [44]:
df1.loc[df1["District"].isna(),"District"] = "Other"

9.Transmission

In [45]:
df1.Transmission.head()

0    Số tự động
2    Số tự động
3    Số tự động
6    Số tự động
7    Số tự động
Name: Transmission, dtype: object

In [46]:
df1.Transmission.isna().sum()

0

In [47]:
df1.Transmission.unique()

array(['Số tự động', 'Số sàn'], dtype=object)

In [48]:
df1.Transmission.value_counts()

Transmission
Số tự động    1143
Số sàn         172
Name: count, dtype: int64

10.Fuel_Type

In [49]:
df1.Fuel_Type.head()

0    Máy xăng
2    Máy xăng
3    Máy xăng
6    Máy xăng
7    Máy xăng
Name: Fuel_Type, dtype: object

In [50]:
df1.Fuel_Type.value_counts()

Fuel_Type
Máy xăng    1083
Máy dầu      210
Điện          15
Hybrid         7
Name: count, dtype: int64

In [51]:
df1.head()

,Name,Year,Origin,Province,District,Transmission,Fuel_Type,Body_Type,Brand,price_num,age,mileage_num
0,Mercedes-Benz GLC 200 4Matic 2021,2021,Trong nước,Tp.HCM,Quận 7,Số tự động,Máy xăng,Other,Mercedes-Benz,1389000000,4,55555
2,Kia Sonet 1.5 Premium 2024,2024,Trong nước,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia,585000000,1,1000
3,Ford Everest Titanium 2.0L AT 4WD 2019,2019,Nhập khẩu,Tp.HCM,Other,Số tự động,Máy xăng,SUV,Ford,810000000,6,4
6,Mercedes-Benz GLC 300 4Matic 2016,2016,Nhập khẩu,Hà Nội,Tây Hồ,Số tự động,Máy xăng,SUV,Mercedes-Benz,885000000,9,90000
7,Mazda 6 2.0 AT 2017,2017,Trong nước,Hải Phòng,An Lão,Số tự động,Máy xăng,Sedan,Mazda,440000000,8,57225

In [52]:
len(df1)

1315

In [53]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1315 entries, 0 to 1489
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          1315 non-null   object
 1   Year          1315 non-null   int32
 2   Origin        1315 non-null   object
 3   Province      1315 non-null   object
 4   District      1315 non-null   object
 5   Transmission  1315 non-null   object
 6   Fuel_Type     1315 non-null   object
 7   Body_Type     1315 non-null   object
 8   Brand         1315 non-null   object
 9   price_num     1315 non-null   int64
 10  age           1315 non-null   int32
 11  mileage_num   1315 non-null   int32
dtypes: int32(3), int64(1), object(8)
memory usage: 118.1+ KB

In [54]:
#  df.to_csv("../data/data_cleaned.csv", index=False, encoding='utf-8-sig')
#  print("Done! Cleaned data saved successfully.")