In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine
from dotenv import load_dotenv
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath(".."))
from config import ENGINE

In [2]:
engine = ENGINE

### clean df1

In [3]:
df1 = pd.read_sql("SELECT * FROM car_data1", engine)

In [4]:
df1.head()

,Name,Price,Năm SX,Kiểu dáng,Tình trạng,Xuất xứ,Km đã đi,Tỉnh thành,Hộp số,Nhiên liệu,Số tiền vay,Thời gian vay,Lãi xuất (%),Loại hình,Giá trị xe muốn mua,Quận huyện,Full lịch sử hãng
0,Toyota Fortuner 2.4G 4x2 AT 2017,525 triệu,2017,SUV,Xe cũ,Nhập khẩu,135 km,Nghệ An,Số sàn,Máy dầu,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,None,None
1,Suzuki Swift 1.4 AT 2013,269 triệu,2013,Hatchback,Xe cũ,Nhập khẩu,132.000 km,Tp.HCM,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,Tân Phú,None
2,Volvo XC60 B6 Ultimate Bright 2023,2 tỉ 190 triệu,2023,SUV,Xe cũ,Nhập khẩu,120 km,Hà Nội,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,Long Biên,None
3,Hyundai Stargazer 1.5 AT Cao cấp 2022,455 triệu,2022,MPV,Xe cũ,Nhập khẩu,72.000 km,Long An,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,None,None
4,Nissan X trail 2018,465 triệu,2018,SUV,Xe cũ,Trong nước,110.000 km,Long An,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,Tân An,None

In [5]:
df1.shape

(1490, 17)

In [6]:
df1 = df1.loc[:, (df1.nunique() > 1) | (df1.columns == "Tình trạng")]

In [7]:
threshold = 0.5
df1 = df1.loc[:, df1.isnull().mean() < threshold]

In [8]:
df1.columns

Index(['Name', 'Price', 'Năm SX', 'Kiểu dáng', 'Tình trạng', 'Xuất xứ',
       'Km đã đi', 'Tỉnh thành', 'Hộp số', 'Nhiên liệu', 'Quận huyện'],
      dtype='object')

In [9]:
df1.shape

(1490, 11)

In [10]:
df1 = df1.drop(["Tỉnh thành","Quận huyện","Hộp số"],axis=1)

In [11]:
df1.columns

Index(['Name', 'Price', 'Năm SX', 'Kiểu dáng', 'Tình trạng', 'Xuất xứ',
       'Km đã đi', 'Nhiên liệu'],
      dtype='object')

In [12]:
df1.rename(columns={
    'Name': 'name',
    'Price': 'price',
    'Tình trạng' : 'status',
    'Năm SX': 'year',
    'Kiểu dáng': 'body_type',
    'Xuất xứ': 'origin',
    'Km đã đi': 'mileage',
    'Nhiên liệu': 'fuel_type'
}, inplace=True)

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       1490 non-null   object
 1   price      1490 non-null   object
 2   year       1490 non-null   object
 3   body_type  1376 non-null   object
 4   status     1490 non-null   object
 5   origin     1485 non-null   object
 6   mileage    1484 non-null   object
 7   fuel_type  1490 non-null   object
dtypes: object(8)
memory usage: 93.3+ KB

In [14]:
df1.isna().sum()

name           0
price          0
year           0
body_type    114
status         0
origin         5
mileage        6
fuel_type      0
dtype: int64

In [15]:
df1.head()

,name,price,year,body_type,status,origin,mileage,fuel_type
0,Toyota Fortuner 2.4G 4x2 AT 2017,525 triệu,2017,SUV,Xe cũ,Nhập khẩu,135 km,Máy dầu
1,Suzuki Swift 1.4 AT 2013,269 triệu,2013,Hatchback,Xe cũ,Nhập khẩu,132.000 km,Máy xăng
2,Volvo XC60 B6 Ultimate Bright 2023,2 tỉ 190 triệu,2023,SUV,Xe cũ,Nhập khẩu,120 km,Máy xăng
3,Hyundai Stargazer 1.5 AT Cao cấp 2022,455 triệu,2022,MPV,Xe cũ,Nhập khẩu,72.000 km,Máy xăng
4,Nissan X trail 2018,465 triệu,2018,SUV,Xe cũ,Trong nước,110.000 km,Máy xăng

1. Name

In [16]:
df1.name.head()

0        Toyota Fortuner 2.4G 4x2 AT  2017
1                 Suzuki Swift 1.4 AT 2013
2       Volvo XC60 B6 Ultimate Bright 2023
3    Hyundai Stargazer 1.5 AT Cao cấp 2022
4                      Nissan X trail 2018
Name: name, dtype: object

In [17]:
df1["brand"] = df1["name"].str.strip().str.split().str[0]

In [18]:
df1["brand"] = df1["brand"].str.split("-").str[0]

In [19]:
df1.head()

,name,price,year,body_type,status,origin,mileage,fuel_type,brand
0,Toyota Fortuner 2.4G 4x2 AT 2017,525 triệu,2017,SUV,Xe cũ,Nhập khẩu,135 km,Máy dầu,Toyota
1,Suzuki Swift 1.4 AT 2013,269 triệu,2013,Hatchback,Xe cũ,Nhập khẩu,132.000 km,Máy xăng,Suzuki
2,Volvo XC60 B6 Ultimate Bright 2023,2 tỉ 190 triệu,2023,SUV,Xe cũ,Nhập khẩu,120 km,Máy xăng,Volvo
3,Hyundai Stargazer 1.5 AT Cao cấp 2022,455 triệu,2022,MPV,Xe cũ,Nhập khẩu,72.000 km,Máy xăng,Hyundai
4,Nissan X trail 2018,465 triệu,2018,SUV,Xe cũ,Trong nước,110.000 km,Máy xăng,Nissan

2.Price

In [20]:
df1.price.head()

0         525 triệu
1         269 triệu
2    2 tỉ 190 triệu
3         455 triệu
4         465 triệu
Name: price, dtype: object

In [21]:
def convert_price(price_str):
    if not price_str or not isinstance(price_str, str):
        return None

    price_str = price_str.strip().lower()
    price = 0

    try:
        if "tỉ" in price_str:
            parts = price_str.split("tỉ")
            ty = float(parts[0].strip().replace(",", "."))
            price += ty * 1_000_000_000

            if len(parts) > 1 and "triệu" in parts[1]:
                trieu = float(parts[1].replace("triệu", "").strip().replace(",", "."))
                price += trieu * 1_000_000
        elif "triệu" in price_str:
            trieu = float(price_str.replace("triệu", "").strip().replace(",", "."))
            price += trieu * 1_000_000
        else:
            price = float(price_str.replace(",", "").strip())
        return int(price)
    except Exception:
        return None

In [22]:
df1["price"] = df1["price"].apply(convert_price)

In [23]:
df1.head()

,name,price,year,body_type,status,origin,mileage,fuel_type,brand
0,Toyota Fortuner 2.4G 4x2 AT 2017,525000000,2017,SUV,Xe cũ,Nhập khẩu,135 km,Máy dầu,Toyota
1,Suzuki Swift 1.4 AT 2013,269000000,2013,Hatchback,Xe cũ,Nhập khẩu,132.000 km,Máy xăng,Suzuki
2,Volvo XC60 B6 Ultimate Bright 2023,2190000000,2023,SUV,Xe cũ,Nhập khẩu,120 km,Máy xăng,Volvo
3,Hyundai Stargazer 1.5 AT Cao cấp 2022,455000000,2022,MPV,Xe cũ,Nhập khẩu,72.000 km,Máy xăng,Hyundai
4,Nissan X trail 2018,465000000,2018,SUV,Xe cũ,Trong nước,110.000 km,Máy xăng,Nissan

In [24]:
def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    filtered_df = df[(df[column] >= Q1 - 1.5 * IQR) & (df[column] <= Q3 + 1.5 * IQR)]
    return filtered_df

In [25]:
df1 = remove_outliers_iqr(df1, "price")

In [26]:
df1.shape

(1315, 9)

3.Year

In [27]:
df1.year.head()

0    2017
1    2013
3    2022
4    2018
5    2016
Name: year, dtype: object

In [28]:
df1.year = df1.year.astype(int)

In [29]:
df1["age"] = 2025 - df1["year"]

4.Body_Type

In [30]:
df1.body_type.unique()

array(['SUV', 'Hatchback', 'MPV', 'Sedan', 'Bán tải', 'Crossover', None,
       'Sport Car', 'Van/Minivan', 'Xe tải', 'Convertible', 'Coupe',
       'Minibus'], dtype=object)

In [31]:
df1.loc[df1["body_type"].isna() , "body_type"] = "Other"

5.Origin

In [32]:
df1.origin.isna().sum()

5

In [33]:
df1.origin.value_counts()

origin
Trong nước    832
Nhập khẩu     478
Name: count, dtype: int64

In [34]:
df1.loc[df1.origin.isna(),"origin"] = "Other"

In [35]:
df1.origin.value_counts()

origin
Trong nước    832
Nhập khẩu     478
Other           5
Name: count, dtype: int64

6.Mileage

In [36]:
df1.mileage.head()

0        135 km
1    132.000 km
3     72.000 km
4    110.000 km
5     79.000 km
Name: mileage, dtype: object

In [37]:
df1.mileage.isna().sum()

6

In [38]:
df1.mileage.describe()

count          1309
unique          314
top       60.000 km
freq             51
Name: mileage, dtype: object

In [39]:
df1.loc[df1["mileage"].isna(),"mileage"] = "60.000 km"

In [40]:
df1['mileage'] = df1['mileage'].str.replace('.', '', regex=False) \
                                  .str.replace(' km', '', regex=False) \
                                  .astype(int)

In [41]:
df1.head()

,name,price,year,body_type,status,origin,mileage,fuel_type,brand,age
0,Toyota Fortuner 2.4G 4x2 AT 2017,525000000,2017,SUV,Xe cũ,Nhập khẩu,135,Máy dầu,Toyota,8
1,Suzuki Swift 1.4 AT 2013,269000000,2013,Hatchback,Xe cũ,Nhập khẩu,132000,Máy xăng,Suzuki,12
3,Hyundai Stargazer 1.5 AT Cao cấp 2022,455000000,2022,MPV,Xe cũ,Nhập khẩu,72000,Máy xăng,Hyundai,3
4,Nissan X trail 2018,465000000,2018,SUV,Xe cũ,Trong nước,110000,Máy xăng,Nissan,7
5,Mazda 3 Sedan 1.5L Luxury 2016,360000000,2016,Sedan,Xe cũ,Nhập khẩu,79000,Máy xăng,Mazda,9

7. Fuel type

In [42]:
df1.fuel_type.head()

0     Máy dầu
1    Máy xăng
3    Máy xăng
4    Máy xăng
5    Máy xăng
Name: fuel_type, dtype: object

In [43]:
df1.fuel_type = df1.fuel_type.str.split(" ").str[1]

In [44]:
df1.fuel_type.value_counts()

fuel_type
xăng    1091
dầu      203
Name: count, dtype: int64

In [45]:
df1.fuel_type.unique()

array(['dầu', 'xăng', nan], dtype=object)

In [46]:
df1.loc[df1["fuel_type"].isna(),"fuel_type"] = "khác"

In [47]:
df1.head()

,name,price,year,body_type,status,origin,mileage,fuel_type,brand,age
0,Toyota Fortuner 2.4G 4x2 AT 2017,525000000,2017,SUV,Xe cũ,Nhập khẩu,135,dầu,Toyota,8
1,Suzuki Swift 1.4 AT 2013,269000000,2013,Hatchback,Xe cũ,Nhập khẩu,132000,xăng,Suzuki,12
3,Hyundai Stargazer 1.5 AT Cao cấp 2022,455000000,2022,MPV,Xe cũ,Nhập khẩu,72000,xăng,Hyundai,3
4,Nissan X trail 2018,465000000,2018,SUV,Xe cũ,Trong nước,110000,xăng,Nissan,7
5,Mazda 3 Sedan 1.5L Luxury 2016,360000000,2016,Sedan,Xe cũ,Nhập khẩu,79000,xăng,Mazda,9

In [48]:
len(df1)

1315

In [49]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1315 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       1315 non-null   object
 1   price      1315 non-null   int64
 2   year       1315 non-null   int32
 3   body_type  1315 non-null   object
 4   status     1315 non-null   object
 5   origin     1315 non-null   object
 6   mileage    1315 non-null   int32
 7   fuel_type  1315 non-null   object
 8   brand      1315 non-null   object
 9   age        1315 non-null   int32
dtypes: int32(3), int64(1), object(6)
memory usage: 97.6+ KB

### clean df2

In [50]:
df2 = pd.read_sql("SELECT * FROM car_data2", engine)

In [51]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ,Màu ngoại thất,Màu nội thất
0,Xe \n\t\t\t\n\t\t\t\t\t\t\tFord Territory \n\t...,2024,Xe đã dùng,"10,000 Km",Lắp ráp trong nước,SUV,Xăng 1.5 L,Trắng,Đen
1,Xe \n\t\t\t\n\t\t\t\t\t\t\tKia Sedona \n\t\t\t...,2020,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,Xanh,Kem
2,Xe \n\t\t\t\n\t\t\t\t\t\t\tFord Ranger \n\t\t\...,2023,Xe đã dùng,645 Km,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L,Đỏ,Nâu
3,Xe \n\t\t\t\n\t\t\t\t\t\t\tMG 5 \n\t\t\t\t\t\t...,2024,Xe mới,None,Nhập khẩu,Sedan,Xăng 1.5 L,Đỏ,Kem
4,Xe \n\t\t\t\n\t\t\t\t\t\t\tToyota Vios \n\t\t\...,2018,Xe đã dùng,"69,000 Km",Lắp ráp trong nước,Sedan,Xăng 1.5 L,Cát,Ghi

In [52]:
df2 = df2.drop(["Màu ngoại thất","Màu nội thất"],axis=1)

In [53]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ
0,Xe \n\t\t\t\n\t\t\t\t\t\t\tFord Territory \n\t...,2024,Xe đã dùng,"10,000 Km",Lắp ráp trong nước,SUV,Xăng 1.5 L
1,Xe \n\t\t\t\n\t\t\t\t\t\t\tKia Sedona \n\t\t\t...,2020,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L
2,Xe \n\t\t\t\n\t\t\t\t\t\t\tFord Ranger \n\t\t\...,2023,Xe đã dùng,645 Km,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L
3,Xe \n\t\t\t\n\t\t\t\t\t\t\tMG 5 \n\t\t\t\t\t\t...,2024,Xe mới,None,Nhập khẩu,Sedan,Xăng 1.5 L
4,Xe \n\t\t\t\n\t\t\t\t\t\t\tToyota Vios \n\t\t\...,2018,Xe đã dùng,"69,000 Km",Lắp ráp trong nước,Sedan,Xăng 1.5 L

In [54]:
df2.rename(columns={
    'Name': 'name',
    'Tình trạng' : 'status',
    'Năm sản xuất': 'year',
    'Kiểu dáng': 'body_type',
    'Xuất xứ': 'origin',
    'Số Km đã đi': 'mileage',
    'Động cơ': 'fuel_type'
}, inplace=True)

In [55]:
df2.columns

Index(['name', 'year', 'status', 'mileage', 'origin', 'body_type',
       'fuel_type'],
      dtype='object')

1. Name

In [56]:
import re

def clean_name(text):
    if not isinstance(text, str):
        return None
    text = re.sub(r"Xe\s+", "", text)  
    text = re.sub(r"\s+", " ", text) 
    return text.strip()

In [57]:
df2["name"] = df2["name"].apply(clean_name)

In [58]:
def split_name_price(full_name):
    if not isinstance(full_name, str):
        return None, None
    
    if " - " in full_name:
        parts = full_name.rsplit(" - ", 1)
        car = parts[0].strip()
        price_raw = parts[1].strip().lower()
        return car, price_raw
    return full_name, None

In [59]:
df2[["name", "price"]] = df2["name"].apply(
    lambda x: pd.Series(split_name_price(x))
)

In [60]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price
0,Ford Territory Titanium X 1.5 AT 2024,2024,Xe đã dùng,"10,000 Km",Lắp ráp trong nước,SUV,Xăng 1.5 L,865 triệu
1,Kia Sedona 2.2 DAT Luxury 2020,2020,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,835 triệu
2,Ford Ranger XLS 2.0L 4x2 AT 2023,2023,Xe đã dùng,645 Km,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L,639 triệu
3,MG 5 1.5 MT 2024,2024,Xe mới,None,Nhập khẩu,Sedan,Xăng 1.5 L,305 triệu
4,Toyota Vios 1.5E MT 2018,2018,Xe đã dùng,"69,000 Km",Lắp ráp trong nước,Sedan,Xăng 1.5 L,275 triệu

In [61]:
df2["brand"] = df2["name"].str.strip().str.split().str[0]

2. Price

In [62]:
def cv_price(price_str):
    if not isinstance(price_str, str):
        return None
    price_str = price_str.strip().lower()
    price = 0

    try:
        ty_match = re.search(r"(\d+)[\.,]?\d*\s*t[ỷỉ]", price_str)
        if ty_match:
            ty = int(ty_match.group(1))
            price += ty * 1_000_000_000

        trieu_match = re.search(r"(\d+)[\.,]?\d*\s*triệu", price_str)
        if trieu_match:
            trieu = int(trieu_match.group(1))
            price += trieu * 1_000_000

        return price if price > 0 else None

    except Exception as e:
        return None

In [63]:
df2["price"] = df2["price"].apply(cv_price)

In [64]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand
0,Ford Territory Titanium X 1.5 AT 2024,2024,Xe đã dùng,"10,000 Km",Lắp ráp trong nước,SUV,Xăng 1.5 L,865000000,Ford
1,Kia Sedona 2.2 DAT Luxury 2020,2020,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,835000000,Kia
2,Ford Ranger XLS 2.0L 4x2 AT 2023,2023,Xe đã dùng,645 Km,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L,639000000,Ford
3,MG 5 1.5 MT 2024,2024,Xe mới,None,Nhập khẩu,Sedan,Xăng 1.5 L,305000000,MG
4,Toyota Vios 1.5E MT 2018,2018,Xe đã dùng,"69,000 Km",Lắp ráp trong nước,Sedan,Xăng 1.5 L,275000000,Toyota

In [65]:
df2 = remove_outliers_iqr(df2, "price")

In [66]:
len(df2)

2578

3. Year

In [67]:
df2["year"] =df2["year"].astype(int)

In [68]:
df2["age"] = 2025 - df2["year"]

In [69]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand,age
0,Ford Territory Titanium X 1.5 AT 2024,2024,Xe đã dùng,"10,000 Km",Lắp ráp trong nước,SUV,Xăng 1.5 L,865000000,Ford,1
1,Kia Sedona 2.2 DAT Luxury 2020,2020,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,835000000,Kia,5
2,Ford Ranger XLS 2.0L 4x2 AT 2023,2023,Xe đã dùng,645 Km,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L,639000000,Ford,2
3,MG 5 1.5 MT 2024,2024,Xe mới,None,Nhập khẩu,Sedan,Xăng 1.5 L,305000000,MG,1
4,Toyota Vios 1.5E MT 2018,2018,Xe đã dùng,"69,000 Km",Lắp ráp trong nước,Sedan,Xăng 1.5 L,275000000,Toyota,7

4. Status

In [70]:
df2.status.unique()

array(['Xe đã dùng', 'Xe mới'], dtype=object)

In [71]:
df2.loc[df2.status == "Xe đã dùng","status"] = "Xe cũ"

In [72]:
df2.status.unique()

array(['Xe cũ', 'Xe mới'], dtype=object)

5. Mileage

In [73]:
df2.groupby("status")["mileage"].describe()

       count unique   top freq
status
Xe cũ   2145    337  0 Km  190
Xe mới     0      0   NaN  NaN

In [74]:
df2.loc[df2["status"].isin(["Xe cũ", "Xe mới"]) & df2["mileage"].isna(), "mileage"] = "0 Km"

In [75]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand,age
0,Ford Territory Titanium X 1.5 AT 2024,2024,Xe cũ,"10,000 Km",Lắp ráp trong nước,SUV,Xăng 1.5 L,865000000,Ford,1
1,Kia Sedona 2.2 DAT Luxury 2020,2020,Xe cũ,"60,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,835000000,Kia,5
2,Ford Ranger XLS 2.0L 4x2 AT 2023,2023,Xe cũ,645 Km,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L,639000000,Ford,2
3,MG 5 1.5 MT 2024,2024,Xe mới,0 Km,Nhập khẩu,Sedan,Xăng 1.5 L,305000000,MG,1
4,Toyota Vios 1.5E MT 2018,2018,Xe cũ,"69,000 Km",Lắp ráp trong nước,Sedan,Xăng 1.5 L,275000000,Toyota,7

In [76]:
df2['mileage'] = (
    df2['mileage']
    .str.replace(',', '', regex=False)   
    .str.replace(' Km', '', regex=False)    
    .str.strip()                         
    .astype(float)                      
)

In [77]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand,age
0,Ford Territory Titanium X 1.5 AT 2024,2024,Xe cũ,10000.0,Lắp ráp trong nước,SUV,Xăng 1.5 L,865000000,Ford,1
1,Kia Sedona 2.2 DAT Luxury 2020,2020,Xe cũ,60000.0,Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,835000000,Kia,5
2,Ford Ranger XLS 2.0L 4x2 AT 2023,2023,Xe cũ,645.0,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L,639000000,Ford,2
3,MG 5 1.5 MT 2024,2024,Xe mới,0.0,Nhập khẩu,Sedan,Xăng 1.5 L,305000000,MG,1
4,Toyota Vios 1.5E MT 2018,2018,Xe cũ,69000.0,Lắp ráp trong nước,Sedan,Xăng 1.5 L,275000000,Toyota,7

6. Origin

In [78]:
df2["origin"].unique()

array(['Lắp ráp trong nước', 'Nhập khẩu'], dtype=object)

In [79]:
df2.loc[df2["origin"]=="Lắp ráp trong nước","origin"] = 'Trong nước'

In [80]:
df2["origin"].unique()

array(['Trong nước', 'Nhập khẩu'], dtype=object)

7. body_type

In [81]:
df2["body_type"].isna().sum()

0

8. fuel_type

In [82]:
df2["fuel_type"].unique()

array(['Xăng  1.5 L', 'Dầu  2.2 L', 'Dầu  2.0 L', 'Xăng  2.0 L',
       'Xăng  2.5 L', 'Điện  0.2 L', 'Xăng  1.25 L', 'Xăng  2.4 L',
       'Dầu  2.5 L', 'Dầu  2.8 L', 'Xăng  1.6 L', 'Xăng  1.0 L',
       'Xăng  1.8 L', 'Xăng  1.2 L', 'Dầu  3.2 L', 'Xăng  5.0 L',
       'Xăng  6.2 L', 'Xăng  2.7 L', 'Xăng  1.4 L', 'Xăng  3.3 L',
       'Xăng  2.3 L', 'Điện', 'Xăng  4.6 L', 'Điện  0.6 L', 'Xăng  3.0 L',
       'Xăng  1.3 L', 'Hybrid  2.5 L', 'Xăng  3.5 L', 'Điện  0.3 L',
       'Dầu  1.9 L', 'Xăng  5.5 L', 'Dầu  3.0 L', 'Xăng  4.7 L',
       'Dầu  2.4 L', 'Xăng  4.8 L', 'Dầu  1.5 L', 'Dầu', 'Điện  8.3 L',
       'Hybrid  1.8 L', 'Dầu  2.1 L', 'Hybrid  2.0 L', 'Xăng  3.6 L',
       'Dầu  2.3 L', 'Xăng  5.7 L', 'Điện  0.1 L', 'Hybrid  1.2 L',
       'Điện  0.4 L', 'Dầu  10.0 L', 'Xăng  4.4 L', 'Xăng  2.2 L',
       'Hybrid  1.5 L', 'Xăng  6.0 L', 'Dầu  5.2 L', 'Xăng  4.0 L',
       'Xăng', 'Hybrid  3.5 L', 'Xăng  0.8 L', 'Xăng  1.1 L',
       'Xăng  4.2 L', 'Xăng  3.7 L', 'Điện  0.5 L', 'Xăng  5.4 L'],
      dtype=object)

In [83]:
df2["fuel_type"] = df2["fuel_type"].str.strip().str.split().str[0]

In [84]:
df2["fuel_type"].unique()

array(['Xăng', 'Dầu', 'Điện', 'Hybrid'], dtype=object)

In [85]:
df2["fuel_type"] = df2["fuel_type"].str.lower()

In [86]:
df2["fuel_type"].unique()

array(['xăng', 'dầu', 'điện', 'hybrid'], dtype=object)

In [87]:
df1["fuel_type"].unique()

array(['dầu', 'xăng', 'khác'], dtype=object)

In [88]:
df_merged = pd.concat([df1, df2], ignore_index=True)

In [89]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3893 entries, 0 to 3892
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       3893 non-null   object
 1   price      3893 non-null   int64
 2   year       3893 non-null   int32
 3   body_type  3893 non-null   object
 4   status     3893 non-null   object
 5   origin     3893 non-null   object
 6   mileage    3893 non-null   float64
 7   fuel_type  3893 non-null   object
 8   brand      3893 non-null   object
 9   age        3893 non-null   int32
dtypes: float64(1), int32(2), int64(1), object(6)
memory usage: 273.9+ KB

In [90]:
df = df_merged

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3893 entries, 0 to 3892
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       3893 non-null   object
 1   price      3893 non-null   int64
 2   year       3893 non-null   int32
 3   body_type  3893 non-null   object
 4   status     3893 non-null   object
 5   origin     3893 non-null   object
 6   mileage    3893 non-null   float64
 7   fuel_type  3893 non-null   object
 8   brand      3893 non-null   object
 9   age        3893 non-null   int32
dtypes: float64(1), int32(2), int64(1), object(6)
memory usage: 273.9+ KB

In [92]:
df = remove_outliers_iqr(df, "price")

In [93]:
df["status"].unique()

array(['Xe cũ', 'Xe mới'], dtype=object)

In [94]:
df["origin"].unique()

array(['Nhập khẩu', 'Trong nước', 'Other'], dtype=object)

In [95]:
df["fuel_type"].unique()

array(['dầu', 'xăng', 'khác', 'điện', 'hybrid'], dtype=object)

In [96]:
print(list(df["body_type"].unique()))

['SUV', 'Hatchback', 'MPV', 'Sedan', 'Bán tải', 'Crossover', 'Other', 'Sport Car', 'Van/Minivan', 'Xe tải', 'Convertible', 'Coupe', 'Minibus', 'Bán tải / Pickup', 'Truck', 'Convertible/Cabriolet', 'Wagon']

In [97]:
body_type_mapping = {
    'Bán tải / Pickup': 'Bán tải',
    'Truck': 'Xe tải',
    'Convertible/Cabriolet': 'Convertible',
    'Sport Car': 'Coupe',
    'Van/Minivan': 'MPV',
    'Other': 'Khác'
}

In [98]:
df["body_type"] = df["body_type"].replace(body_type_mapping)

In [99]:
df["body_type"].unique()

array(['SUV', 'Hatchback', 'MPV', 'Sedan', 'Bán tải', 'Crossover', 'Khác',
       'Coupe', 'Xe tải', 'Convertible', 'Minibus', 'Wagon'], dtype=object)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3592 entries, 0 to 3891
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       3592 non-null   object
 1   price      3592 non-null   int64
 2   year       3592 non-null   int32
 3   body_type  3592 non-null   object
 4   status     3592 non-null   object
 5   origin     3592 non-null   object
 6   mileage    3592 non-null   float64
 7   fuel_type  3592 non-null   object
 8   brand      3592 non-null   object
 9   age        3592 non-null   int32
dtypes: float64(1), int32(2), int64(1), object(6)
memory usage: 280.6+ KB

In [101]:
df.to_sql("car_data_cleaned", engine, index=False, if_exists="append")
print(f"✅ Saved {len(df)} rows into car_data_cleaned")

✅ Saved 3592 rows into car_data_cleaned

In [102]:
df1_demo = pd.read_sql("SELECT * FROM car_data1 LIMIT 5", engine)

In [103]:
df2_demo = pd.read_sql("SELECT * FROM car_data2 LIMIT 5", engine)

In [104]:
df_demo = pd.read_sql("SELECT * FROM car_data_cleaned LIMIT 5", engine)

In [105]:
df1_demo.to_csv("../data/cars_data.csv", index=False, encoding="utf-8-sig")

In [106]:
df2_demo.to_csv("../data/cars_data2.csv", index=False, encoding="utf-8-sig")

In [107]:
df_demo.to_csv("../data/data_cleaned.csv", index=False, encoding="utf-8-sig")