In [180]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### clean df1

In [181]:
df1 = pd.read_csv("../data/cars_data.csv")

In [182]:
df1.head()

,Name,Price,Năm SX,Tình trạng,Xuất xứ,Km đã đi,Tỉnh thành,Quận huyện,Hộp số,Nhiên liệu,...,Hỗ trợ trả góp,Bảo hành máy móc động cơ 3-6 tháng,Một chủ từ đầu,Full lịch sử hãng,"Thủ tục trọn gói (Rút hồ sơ,sang tên,...)",Model xe mới,Xe có nhiều đồ chơi,Hỗ trợ/cam kết từ người bán,Có xuất hóa đơn,Còn bảo hiểm thân vỏ
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [183]:
for i in df1.columns :
    print(f"{i} : {df1[i].nunique()}")

Name : 1119
Price : 584
Năm SX : 24
Tình trạng : 1
Xuất xứ : 2
Km đã đi : 312
Tỉnh thành : 42
Quận huyện : 91
Hộp số : 2
Nhiên liệu : 4
Số tiền vay : 1
Thời gian vay : 1
Lãi xuất (%) : 1
Loại hình : 1
Giá trị xe muốn mua : 1
Kiểu dáng : 11
Hỗ trợ trả góp : 3
Bảo hành máy móc động cơ 3-6 tháng : 2
Một chủ từ đầu : 2
Full lịch sử hãng : 3
Thủ tục trọn gói (Rút hồ sơ,sang tên,...) : 3
Model xe mới : 3
Xe có nhiều đồ chơi : 3
Hỗ trợ/cam kết từ người bán : 3
Có xuất hóa đơn : 1
Còn bảo hiểm thân vỏ : 1

In [184]:
df1 = df1.loc[:, (df1.nunique() > 1) | (df1.columns == "Tình trạng")]

In [185]:
threshold = 0.5
df1 = df1.loc[:, df1.isnull().mean() < threshold]

In [186]:
df1 = df1.drop(["Tỉnh thành","Quận huyện","Hộp số"],axis=1)

In [187]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1490 non-null   object
 1   Price       1490 non-null   object
 2   Năm SX      1490 non-null   int64
 3   Tình trạng  1490 non-null   object
 4   Xuất xứ     1483 non-null   object
 5   Km đã đi    1485 non-null   object
 6   Nhiên liệu  1490 non-null   object
 7   Kiểu dáng   1352 non-null   object
dtypes: int64(1), object(7)
memory usage: 93.3+ KB

In [188]:
df1.rename(columns={
    'Name': 'name',
    'Price': 'price',
    'Tình trạng' : 'status',
    'Năm SX': 'year',
    'Kiểu dáng': 'body_type',
    'Xuất xứ': 'origin',
    'Km đã đi': 'mileage',
    'Nhiên liệu': 'fuel_type'
}, inplace=True)

In [189]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       1490 non-null   object
 1   price      1490 non-null   object
 2   year       1490 non-null   int64
 3   status     1490 non-null   object
 4   origin     1483 non-null   object
 5   mileage    1485 non-null   object
 6   fuel_type  1490 non-null   object
 7   body_type  1352 non-null   object
dtypes: int64(1), object(7)
memory usage: 93.3+ KB

In [190]:
df1.isna().sum()

name           0
price          0
year           0
status         0
origin         7
mileage        5
fuel_type      0
body_type    138
dtype: int64

In [191]:
df1.head()

,name,price,year,status,origin,mileage,fuel_type,body_type
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Máy xăng,NaN
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Máy xăng,SUV
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Máy xăng,Crossover
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Máy xăng,SUV
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Máy xăng,Sedan

1. Name

In [192]:
df1.name.head()

0          Mercedes-Benz GLC 200 4Matic 2021
1                   Lexus RX 350 Luxury 2016
2                 Kia Sonet 1.5 Premium 2024
3     Ford Everest Titanium 2.0L AT 4WD 2019
4    Mercedes-Benz S450 Limited Edition 2020
Name: name, dtype: object

In [193]:
df1["brand"] = df1["name"].str.strip().str.split().str[0]

In [194]:
df1["brand"] = df1["brand"].str.split("-").str[0]

In [195]:
df1.head()

,name,price,year,status,origin,mileage,fuel_type,body_type,brand
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Máy xăng,NaN,Mercedes
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Máy xăng,SUV,Lexus
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Máy xăng,Crossover,Kia
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Máy xăng,SUV,Ford
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Máy xăng,Sedan,Mercedes

2.Price

In [196]:
df1.price.head()

0    1 tỉ 389 triệu
1    2 tỉ 099 triệu
2         585 triệu
3         810 triệu
4    2 tỉ 398 triệu
Name: price, dtype: object

In [197]:
def convert_price(price_str):
    price_str = price_str.strip().lower()
    price = 0
    if "tỉ" in price_str:
        parts = price_str.split("tỉ")
        ty = int(parts[0].strip())
        price += ty * 1_000_000_000
        if "triệu" in parts[1]:
            trieu = int(parts[1].replace("triệu", "").strip())
            price += trieu * 1_000_000
    elif "triệu" in price_str:
        trieu = int(price_str.replace("triệu", "").strip())
        price += trieu * 1_000_000
    return price

In [198]:
df1["price"] = df1["price"].apply(convert_price)

In [199]:
df1.head()

,name,price,year,status,origin,mileage,fuel_type,body_type,brand
0,Mercedes-Benz GLC 200 4Matic 2021,1389000000,2021,Xe cũ,Trong nước,55.555 km,Máy xăng,NaN,Mercedes
1,Lexus RX 350 Luxury 2016,2099000000,2016,Xe cũ,Nhập khẩu,130.000 km,Máy xăng,SUV,Lexus
2,Kia Sonet 1.5 Premium 2024,585000000,2024,Xe cũ,Trong nước,1.000 km,Máy xăng,Crossover,Kia
3,Ford Everest Titanium 2.0L AT 4WD 2019,810000000,2019,Xe cũ,Nhập khẩu,04 km,Máy xăng,SUV,Ford
4,Mercedes-Benz S450 Limited Edition 2020,2398000000,2020,Xe cũ,Trong nước,46.000 km,Máy xăng,Sedan,Mercedes

In [200]:
def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    filtered_df = df[(df[column] >= Q1 - 1.5 * IQR) & (df[column] <= Q3 + 1.5 * IQR)]
    return filtered_df

In [201]:
df1 = remove_outliers_iqr(df1, "price")

3.Year

In [202]:
df1.year.head()

0    2021
2    2024
3    2019
6    2016
7    2017
Name: year, dtype: int64

In [203]:
df1.year = df1.year.astype(int)

In [204]:
df1["age"] = 2025 - df1["year"]

4.Body_Type

In [205]:
df1.body_type.unique()

array([nan, 'Crossover', 'SUV', 'Sedan', 'Bán tải', 'MPV', 'Hatchback',
       'Van/Minivan', 'Xe tải', 'Sport Car', 'Convertible', 'Coupe'],
      dtype=object)

In [206]:
df1.loc[df1["body_type"].isna() , "body_type"] = "Other"

5.Origin

In [207]:
df1.origin.isna().sum()

7

In [208]:
df1.origin.value_counts()

origin
Trong nước    824
Nhập khẩu     484
Name: count, dtype: int64

In [209]:
df1.loc[df1.origin.isna(),"origin"] = "Other"

In [210]:
df1.origin.value_counts()

origin
Trong nước    824
Nhập khẩu     484
Other           7
Name: count, dtype: int64

6.Mileage

In [211]:
df1.mileage.head()

0    55.555 km
2     1.000 km
3        04 km
6    90.000 km
7    57.225 km
Name: mileage, dtype: object

In [212]:
df1.mileage.isna().sum()

5

In [213]:
df1.mileage.describe()

count          1310
unique          288
top       60.000 km
freq             58
Name: mileage, dtype: object

In [214]:
df1.loc[df1["mileage"].isna(),"mileage"] = "60.000 km"

In [215]:
df1['mileage'] = df1['mileage'].str.replace('.', '', regex=False) \
                                  .str.replace(' km', '', regex=False) \
                                  .astype(int)

In [216]:
df1.head()

,name,price,year,status,origin,mileage,fuel_type,body_type,brand,age
0,Mercedes-Benz GLC 200 4Matic 2021,1389000000,2021,Xe cũ,Trong nước,55555,Máy xăng,Other,Mercedes,4
2,Kia Sonet 1.5 Premium 2024,585000000,2024,Xe cũ,Trong nước,1000,Máy xăng,Crossover,Kia,1
3,Ford Everest Titanium 2.0L AT 4WD 2019,810000000,2019,Xe cũ,Nhập khẩu,4,Máy xăng,SUV,Ford,6
6,Mercedes-Benz GLC 300 4Matic 2016,885000000,2016,Xe cũ,Nhập khẩu,90000,Máy xăng,SUV,Mercedes,9
7,Mazda 6 2.0 AT 2017,440000000,2017,Xe cũ,Trong nước,57225,Máy xăng,Sedan,Mazda,8

7. Fuel type

In [217]:
df1.fuel_type.head()

0    Máy xăng
2    Máy xăng
3    Máy xăng
6    Máy xăng
7    Máy xăng
Name: fuel_type, dtype: object

In [218]:
df1.fuel_type = df1.fuel_type.str.split(" ").str[1]

In [219]:
df1.fuel_type.value_counts()

fuel_type
xăng    1083
dầu      210
Name: count, dtype: int64

In [220]:
df1.fuel_type.unique()

array(['xăng', 'dầu', nan], dtype=object)

In [221]:
df1.loc[df1["fuel_type"].isna(),"fuel_type"] = "khác"

In [222]:
df1.head()

,name,price,year,status,origin,mileage,fuel_type,body_type,brand,age
0,Mercedes-Benz GLC 200 4Matic 2021,1389000000,2021,Xe cũ,Trong nước,55555,xăng,Other,Mercedes,4
2,Kia Sonet 1.5 Premium 2024,585000000,2024,Xe cũ,Trong nước,1000,xăng,Crossover,Kia,1
3,Ford Everest Titanium 2.0L AT 4WD 2019,810000000,2019,Xe cũ,Nhập khẩu,4,xăng,SUV,Ford,6
6,Mercedes-Benz GLC 300 4Matic 2016,885000000,2016,Xe cũ,Nhập khẩu,90000,xăng,SUV,Mercedes,9
7,Mazda 6 2.0 AT 2017,440000000,2017,Xe cũ,Trong nước,57225,xăng,Sedan,Mazda,8

In [223]:
len(df1)

1315

In [224]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1315 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       1315 non-null   object
 1   price      1315 non-null   int64
 2   year       1315 non-null   int32
 3   status     1315 non-null   object
 4   origin     1315 non-null   object
 5   mileage    1315 non-null   int32
 6   fuel_type  1315 non-null   object
 7   body_type  1315 non-null   object
 8   brand      1315 non-null   object
 9   age        1315 non-null   int32
dtypes: int32(3), int64(1), object(6)
memory usage: 97.6+ KB

### clean df2

In [225]:
df2 = pd.read_csv("../data/cars_data2.csv")

In [226]:
df2 = df2.drop(["Màu ngoại thất","Màu nội thất"],axis=1)

In [227]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ
0,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz GLC \...,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L
1,Xe \n\t\t\t\n\t\t\t\t\t\t\tKia Sedona \n\t\t\t...,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L
2,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz C cla...,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L
3,Xe \n\t\t\t\n\t\t\t\t\t\t\tSuzuki XL7 \n\t\t\t...,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L
4,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz C cla...,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L

In [228]:
df2.rename(columns={
    'Name': 'name',
    'Tình trạng' : 'status',
    'Năm sản xuất': 'year',
    'Kiểu dáng': 'body_type',
    'Xuất xứ': 'origin',
    'Số Km đã đi': 'mileage',
    'Động cơ': 'fuel_type'
}, inplace=True)

In [229]:
df2.columns

Index(['name', 'year', 'status', 'mileage', 'origin', 'body_type',
       'fuel_type'],
      dtype='object')

1. Name

In [230]:
import re

def clean_name(text):
    if not isinstance(text, str):
        return None
    text = re.sub(r"Xe\s+", "", text)  
    text = re.sub(r"\s+", " ", text) 
    return text.strip()

In [231]:
df2["name"] = df2["name"].apply(clean_name)

In [232]:
def split_name_price(full_name):
    if not isinstance(full_name, str):
        return None, None
    
    if " - " in full_name:
        parts = full_name.rsplit(" - ", 1)
        car = parts[0].strip()
        price_raw = parts[1].strip().lower()
        return car, price_raw
    return full_name, None

In [233]:
df2[["name", "price"]] = df2["name"].apply(
    lambda x: pd.Series(split_name_price(x))
)

In [234]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price
0,Mercedes Benz GLC 200 2021,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,1 tỷ 250 triệu
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,875 triệu
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,580 triệu
3,Suzuki XL7 1.5 AT 2022,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,499 triệu
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,595 triệu

In [235]:
df2["brand"] = df2["name"].str.strip().str.split().str[0]

2. Price

In [236]:
def cv_price(price_str):
    if not isinstance(price_str, str):
        return None
    price_str = price_str.strip().lower()
    price = 0

    try:
        ty_match = re.search(r"(\d+)[\.,]?\d*\s*t[ỷỉ]", price_str)
        if ty_match:
            ty = int(ty_match.group(1))
            price += ty * 1_000_000_000

        trieu_match = re.search(r"(\d+)[\.,]?\d*\s*triệu", price_str)
        if trieu_match:
            trieu = int(trieu_match.group(1))
            price += trieu * 1_000_000

        return price if price > 0 else None

    except Exception as e:
        return None

In [237]:
df2["price"] = df2["price"].apply(cv_price)

In [238]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand
0,Mercedes Benz GLC 200 2021,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,1250000000,Mercedes
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,875000000,Kia
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,580000000,Mercedes
3,Suzuki XL7 1.5 AT 2022,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,499000000,Suzuki
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,595000000,Mercedes

In [239]:
df2 = remove_outliers_iqr(df2, "price")

In [240]:
len(df2)

2525

3. Year

In [241]:
df2["age"] = 2025 - df2["year"]

In [242]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand,age
0,Mercedes Benz GLC 200 2021,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,1250000000,Mercedes,4
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,875000000,Kia,4
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,580000000,Mercedes,10
3,Suzuki XL7 1.5 AT 2022,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,499000000,Suzuki,3
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,595000000,Mercedes,10

4. Status

In [243]:
df2.status.unique()

array(['Xe đã dùng', 'Xe mới'], dtype=object)

In [244]:
df2.loc[df2.status == "Xe đã dùng","status"] = "Xe cũ"

In [245]:
df2.status.unique()

array(['Xe cũ', 'Xe mới'], dtype=object)

5. Mileage

In [246]:
df2.groupby("status")["mileage"].describe()

       count unique   top freq
status
Xe cũ   2035    311  0 Km  184
Xe mới     0      0   NaN  NaN

In [247]:
df2.loc[df2["status"].isin(["Xe cũ", "Xe mới"]) & df2["mileage"].isna(), "mileage"] = "0 Km"

In [248]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand,age
0,Mercedes Benz GLC 200 2021,2021,Xe cũ,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,1250000000,Mercedes,4
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe cũ,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,875000000,Kia,4
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe cũ,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,580000000,Mercedes,10
3,Suzuki XL7 1.5 AT 2022,2022,Xe cũ,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,499000000,Suzuki,3
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe cũ,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,595000000,Mercedes,10

In [249]:
df2['mileage'] = (
    df2['mileage']
    .str.replace(',', '', regex=False)   
    .str.replace(' Km', '', regex=False)    
    .str.strip()                         
    .astype(float)                      
)

In [250]:
df2.head()

,name,year,status,mileage,origin,body_type,fuel_type,price,brand,age
0,Mercedes Benz GLC 200 2021,2021,Xe cũ,60000.0,Lắp ráp trong nước,SUV,Xăng 2.0 L,1250000000,Mercedes,4
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe cũ,96000.0,Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,875000000,Kia,4
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe cũ,70000.0,Lắp ráp trong nước,Sedan,Xăng 2.0 L,580000000,Mercedes,10
3,Suzuki XL7 1.5 AT 2022,2022,Xe cũ,65000.0,Nhập khẩu,SUV,Xăng 1.5 L,499000000,Suzuki,3
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe cũ,89000.0,Lắp ráp trong nước,Sedan,Xăng 2.0 L,595000000,Mercedes,10

6. Origin

In [251]:
df2["origin"].unique()

array(['Lắp ráp trong nước', 'Nhập khẩu'], dtype=object)

In [252]:
df2.loc[df2["origin"]=="Lắp ráp trong nước","origin"] = 'Trong nước'

In [253]:
df2["origin"].unique()

array(['Trong nước', 'Nhập khẩu'], dtype=object)

7. body_type

In [254]:
df2["body_type"].isna().sum()

0

8. fuel_type

In [255]:
df2["fuel_type"].unique()

array(['Xăng  2.0 L', 'Dầu  2.2 L', 'Xăng  1.5 L', 'Xăng  1.25 L',
       'Dầu  2.4 L', 'Xăng  1.8 L', 'Xăng  1.6 L', 'Xăng  2.5 L',
       'Xăng  3.6 L', 'Điện', 'Dầu  1.9 L', 'Xăng  3.0 L', 'Dầu  2.1 L',
       'Dầu  2.0 L', 'Xăng  2.7 L', 'Xăng  2.4 L', 'Xăng  1.4 L',
       'Xăng  2.3 L', 'Dầu  2.5 L', 'Xăng  1.2 L', 'Xăng  4.6 L',
       'Xăng  3.5 L', 'Điện  0.3 L', 'Dầu  2.3 L', 'Dầu  3.0 L',
       'Dầu  3.2 L', 'Hybrid  1.5 L', 'Điện  0.2 L', 'Xăng  1.3 L',
       'Dầu  3.9 L', 'Hybrid  2.0 L', 'Xăng  1.0 L', 'Hybrid  2.5 L',
       'Xăng  3.7 L', 'Xăng  6.2 L', 'Dầu  2.8 L', 'Điện  5.0 L',
       'Hybrid  1.8 L', 'Xăng  4.0 L', 'Điện  0.6 L', 'Điện  0.1 L',
       'Dầu  1.5 L', 'Xăng  2.2 L', 'Xăng  0.8 L', 'Điện  0.7 L',
       'Xăng  4.8 L', 'Hybrid  1.6 L', 'Xăng  5.0 L', 'Xăng  3.3 L',
       'Xăng  1.1 L', 'Hybrid  3.5 L', 'Xăng  4.7 L', 'Dầu',
       'Hybrid  1.2 L', 'Xăng  6.0 L', 'Xăng', 'Xăng  5.7 L',
       'Dầu  5.2 L', 'Xăng  5.5 L', 'Điện  6.0 L'], dtype=object)

In [256]:
df2["fuel_type"] = df2["fuel_type"].str.strip().str.split().str[0]

In [257]:
df2["fuel_type"].unique()

array(['Xăng', 'Dầu', 'Điện', 'Hybrid'], dtype=object)

In [258]:
df2["fuel_type"] = df2["fuel_type"].str.lower()

In [259]:
df2["fuel_type"].unique()

array(['xăng', 'dầu', 'điện', 'hybrid'], dtype=object)

In [260]:
df1["fuel_type"].unique()

array(['xăng', 'dầu', 'khác'], dtype=object)

In [261]:
df_merged = pd.concat([df1, df2], ignore_index=True)

In [262]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840 entries, 0 to 3839
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       3840 non-null   object
 1   price      3840 non-null   int64
 2   year       3840 non-null   int64
 3   status     3840 non-null   object
 4   origin     3840 non-null   object
 5   mileage    3840 non-null   float64
 6   fuel_type  3840 non-null   object
 7   body_type  3840 non-null   object
 8   brand      3840 non-null   object
 9   age        3840 non-null   int64
dtypes: float64(1), int64(3), object(6)
memory usage: 300.1+ KB

In [263]:
df = df_merged

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840 entries, 0 to 3839
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       3840 non-null   object
 1   price      3840 non-null   int64
 2   year       3840 non-null   int64
 3   status     3840 non-null   object
 4   origin     3840 non-null   object
 5   mileage    3840 non-null   float64
 6   fuel_type  3840 non-null   object
 7   body_type  3840 non-null   object
 8   brand      3840 non-null   object
 9   age        3840 non-null   int64
dtypes: float64(1), int64(3), object(6)
memory usage: 300.1+ KB

In [265]:
df = remove_outliers_iqr(df, "price")

In [266]:
df["status"].unique()

array(['Xe cũ', 'Xe mới'], dtype=object)

In [267]:
df["origin"].unique()

array(['Trong nước', 'Nhập khẩu', 'Other'], dtype=object)

In [268]:
df["fuel_type"].unique()

array(['xăng', 'dầu', 'khác', 'điện', 'hybrid'], dtype=object)

In [269]:
df["body_type"].unique()

array(['Other', 'Crossover', 'SUV', 'Sedan', 'Bán tải', 'MPV',
       'Hatchback', 'Van/Minivan', 'Xe tải', 'Sport Car', 'Convertible',
       'Coupe', 'Bán tải / Pickup', 'Truck', 'Convertible/Cabriolet'],
      dtype=object)

In [270]:
body_type_mapping = {
    'Bán tải / Pickup': 'Bán tải',
    'Truck': 'Xe tải',
    'Convertible/Cabriolet': 'Convertible',
    'Sport Car': 'Coupe',
    'Van/Minivan': 'MPV',
    'Other': 'Khác'
}

In [271]:
df["body_type"] = df["body_type"].replace(body_type_mapping)

In [272]:
df["body_type"].unique()

array(['Khác', 'Crossover', 'SUV', 'Sedan', 'Bán tải', 'MPV', 'Hatchback',
       'Xe tải', 'Coupe', 'Convertible'], dtype=object)

In [273]:
df.to_csv("../data/data_cleaned.csv", index=False, encoding='utf-8-sig')  
print("Done! cleaned")

Done! cleaned