In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### clean df1

In [2]:
df1 = pd.read_csv("../data/cars_data.csv")

In [3]:
df1.head()

,Name,Price,Năm SX,Tình trạng,Xuất xứ,Km đã đi,Tỉnh thành,Quận huyện,Hộp số,Nhiên liệu,...,Hỗ trợ trả góp,Bảo hành máy móc động cơ 3-6 tháng,Một chủ từ đầu,Full lịch sử hãng,"Thủ tục trọn gói (Rút hồ sơ,sang tên,...)",Model xe mới,Xe có nhiều đồ chơi,Hỗ trợ/cam kết từ người bán,Có xuất hóa đơn,Còn bảo hiểm thân vỏ
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
for i in df1.columns :
    print(f"{i} : {df1[i].nunique()}")

Name : 1119
Price : 584
Năm SX : 24
Tình trạng : 1
Xuất xứ : 2
Km đã đi : 312
Tỉnh thành : 42
Quận huyện : 91
Hộp số : 2
Nhiên liệu : 4
Số tiền vay : 1
Thời gian vay : 1
Lãi xuất (%) : 1
Loại hình : 1
Giá trị xe muốn mua : 1
Kiểu dáng : 11
Hỗ trợ trả góp : 3
Bảo hành máy móc động cơ 3-6 tháng : 2
Một chủ từ đầu : 2
Full lịch sử hãng : 3
Thủ tục trọn gói (Rút hồ sơ,sang tên,...) : 3
Model xe mới : 3
Xe có nhiều đồ chơi : 3
Hỗ trợ/cam kết từ người bán : 3
Có xuất hóa đơn : 1
Còn bảo hiểm thân vỏ : 1

In [5]:
df1 = df1.loc[:, (df1.nunique() > 1) | (df1.columns == "Tình trạng")]

In [6]:
threshold = 0.5
df1 = df1.loc[:, df1.isnull().mean() < threshold]

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1490 non-null   object
 1   Price       1490 non-null   object
 2   Năm SX      1490 non-null   int64
 3   Tình trạng  1490 non-null   object
 4   Xuất xứ     1483 non-null   object
 5   Km đã đi    1485 non-null   object
 6   Tỉnh thành  1490 non-null   object
 7   Quận huyện  1285 non-null   object
 8   Hộp số      1490 non-null   object
 9   Nhiên liệu  1490 non-null   object
 10  Kiểu dáng   1352 non-null   object
dtypes: int64(1), object(10)
memory usage: 128.2+ KB

In [8]:
df1.rename(columns={
    'Name': 'Name',
    'Price': 'Price',
    'Năm SX': 'Year',
    'Kiểu dáng': 'Body_Type',
    'Xuất xứ': 'Origin',
    'Km đã đi': 'Mileage',
    'Tỉnh thành': 'Province',
    'Quận huyện': 'District',
    'Hộp số': 'Transmission',
    'Nhiên liệu': 'Fuel_Type'
}, inplace=True)

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          1490 non-null   object
 1   Price         1490 non-null   object
 2   Year          1490 non-null   int64
 3   Tình trạng    1490 non-null   object
 4   Origin        1483 non-null   object
 5   Mileage       1485 non-null   object
 6   Province      1490 non-null   object
 7   District      1285 non-null   object
 8   Transmission  1490 non-null   object
 9   Fuel_Type     1490 non-null   object
 10  Body_Type     1352 non-null   object
dtypes: int64(1), object(10)
memory usage: 128.2+ KB

In [10]:
df1.isna().sum()

Name              0
Price             0
Year              0
Tình trạng        0
Origin            7
Mileage           5
Province          0
District        205
Transmission      0
Fuel_Type         0
Body_Type       138
dtype: int64

In [11]:
df1.head()

,Name,Price,Year,Tình trạng,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,NaN
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,SUV
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Sedan

1. Name

In [12]:
df1.Name.head()

0          Mercedes-Benz GLC 200 4Matic 2021
1                   Lexus RX 350 Luxury 2016
2                 Kia Sonet 1.5 Premium 2024
3     Ford Everest Titanium 2.0L AT 4WD 2019
4    Mercedes-Benz S450 Limited Edition 2020
Name: Name, dtype: object

In [13]:
df1["Brand"] = df1["Name"].str.strip().str.split().str[0]

In [14]:
df1.head()

,Name,Price,Year,Tình trạng,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type,Brand
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,NaN,Mercedes-Benz
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,SUV,Lexus
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV,Ford
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Sedan,Mercedes-Benz

2.Price

In [15]:
df1.Price.head()

0    1 tỉ 389 triệu
1    2 tỉ 099 triệu
2         585 triệu
3         810 triệu
4    2 tỉ 398 triệu
Name: Price, dtype: object

In [16]:
def convert_price(price_str):
    price_str = price_str.strip().lower()
    price = 0
    if "tỉ" in price_str:
        parts = price_str.split("tỉ")
        ty = int(parts[0].strip())
        price += ty * 1_000_000_000
        if "triệu" in parts[1]:
            trieu = int(parts[1].replace("triệu", "").strip())
            price += trieu * 1_000_000
    elif "triệu" in price_str:
        trieu = int(price_str.replace("triệu", "").strip())
        price += trieu * 1_000_000
    return price

df1["price_num"] = df1["Price"].apply(convert_price)

In [17]:
df1.head()

,Name,Price,Year,Tình trạng,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type,Brand,price_num
0,Mercedes-Benz GLC 200 4Matic 2021,1 tỉ 389 triệu,2021,Xe cũ,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,NaN,Mercedes-Benz,1389000000
1,Lexus RX 350 Luxury 2016,2 tỉ 099 triệu,2016,Xe cũ,Nhập khẩu,130.000 km,Hà Nội,Ba Đình,Số tự động,Máy xăng,SUV,Lexus,2099000000
2,Kia Sonet 1.5 Premium 2024,585 triệu,2024,Xe cũ,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia,585000000
3,Ford Everest Titanium 2.0L AT 4WD 2019,810 triệu,2019,Xe cũ,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV,Ford,810000000
4,Mercedes-Benz S450 Limited Edition 2020,2 tỉ 398 triệu,2020,Xe cũ,Trong nước,46.000 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Sedan,Mercedes-Benz,2398000000

In [18]:
df1 = df1.drop("Price",axis=1)

In [19]:
Q1 = df1['price_num'].quantile(0.25)
Q3 = df1['price_num'].quantile(0.75)
IQR = Q3 - Q1

df1 = df1[(df1['price_num'] >= Q1 - 1.5 * IQR) & (df1['price_num'] <= Q3 + 1.5 * IQR)]

3.Year

In [20]:
df1.Year.head()

0    2021
2    2024
3    2019
6    2016
7    2017
Name: Year, dtype: int64

In [21]:
df1.Year = df1.Year.astype(int)

In [22]:
df1["age"] = 2025 - df1["Year"]

4.Body_Type

In [23]:
df1.Body_Type.unique()

array([nan, 'Crossover', 'SUV', 'Sedan', 'Bán tải', 'MPV', 'Hatchback',
       'Van/Minivan', 'Xe tải', 'Sport Car', 'Convertible', 'Coupe'],
      dtype=object)

In [24]:
df1.Body_Type.value_counts()

Body_Type
SUV            406
Sedan          402
Hatchback      108
Bán tải        101
MPV             99
Van/Minivan     36
Crossover       34
Xe tải           8
Sport Car        3
Convertible      3
Coupe            2
Name: count, dtype: int64

In [25]:
df1.loc[df1["Body_Type"].isna() , "Body_Type"] = "Other"

5.Origin

In [26]:
df1.Origin.isna().sum()

7

In [27]:
df1.Origin.value_counts()

Origin
Trong nước    824
Nhập khẩu     484
Name: count, dtype: int64

In [28]:
df1.loc[df1.Origin.isna(),"Origin"] = "Other"

In [29]:
df1.Origin.value_counts()

Origin
Trong nước    824
Nhập khẩu     484
Other           7
Name: count, dtype: int64

6.Mileage

In [30]:
df1.Mileage.head()

0    55.555 km
2     1.000 km
3        04 km
6    90.000 km
7    57.225 km
Name: Mileage, dtype: object

In [31]:
df1.Mileage.isna().sum()

5

In [32]:
df1.Mileage.describe()

count          1310
unique          288
top       60.000 km
freq             58
Name: Mileage, dtype: object

In [33]:
df1.loc[df1["Mileage"].isna(),"Mileage"] = "60.000 km"

In [34]:
df1['mileage_num'] = df1['Mileage'].str.replace('.', '', regex=False) \
                                  .str.replace(' km', '', regex=False) \
                                  .astype(int)

In [35]:
df1.head()

,Name,Year,Tình trạng,Origin,Mileage,Province,District,Transmission,Fuel_Type,Body_Type,Brand,price_num,age,mileage_num
0,Mercedes-Benz GLC 200 4Matic 2021,2021,Xe cũ,Trong nước,55.555 km,Tp.HCM,Quận 7,Số tự động,Máy xăng,Other,Mercedes-Benz,1389000000,4,55555
2,Kia Sonet 1.5 Premium 2024,2024,Xe cũ,Trong nước,1.000 km,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia,585000000,1,1000
3,Ford Everest Titanium 2.0L AT 4WD 2019,2019,Xe cũ,Nhập khẩu,04 km,Tp.HCM,NaN,Số tự động,Máy xăng,SUV,Ford,810000000,6,4
6,Mercedes-Benz GLC 300 4Matic 2016,2016,Xe cũ,Nhập khẩu,90.000 km,Hà Nội,Tây Hồ,Số tự động,Máy xăng,SUV,Mercedes-Benz,885000000,9,90000
7,Mazda 6 2.0 AT 2017,2017,Xe cũ,Trong nước,57.225 km,Hải Phòng,An Lão,Số tự động,Máy xăng,Sedan,Mazda,440000000,8,57225

In [36]:
df1 = df1.drop("Mileage",axis=1)

In [37]:
df1.columns

Index(['Name', 'Year', 'Tình trạng', 'Origin', 'Province', 'District',
       'Transmission', 'Fuel_Type', 'Body_Type', 'Brand', 'price_num', 'age',
       'mileage_num'],
      dtype='object')

7.Province

In [38]:
df1.Province.head()

0       Tp.HCM
2       Hà Nội
3       Tp.HCM
6       Hà Nội
7    Hải Phòng
Name: Province, dtype: object

In [39]:
df1.Province.isna().sum()

0

In [40]:
df1.Province.nunique()

42

8.District

In [41]:
df1.District.isna().sum()

197

In [42]:
df1.District.describe()

count         1118
unique          89
top       Cầu Giấy
freq           132
Name: District, dtype: object

In [43]:
df1.loc[df1["District"].isna(),"District"] = "Other"

9.Transmission

In [44]:
df1.Transmission.head()

0    Số tự động
2    Số tự động
3    Số tự động
6    Số tự động
7    Số tự động
Name: Transmission, dtype: object

In [45]:
df1.Transmission.isna().sum()

0

In [46]:
df1.Transmission.unique()

array(['Số tự động', 'Số sàn'], dtype=object)

In [47]:
df1.Transmission.value_counts()

Transmission
Số tự động    1143
Số sàn         172
Name: count, dtype: int64

10.Fuel_Type

In [48]:
df1.Fuel_Type.head()

0    Máy xăng
2    Máy xăng
3    Máy xăng
6    Máy xăng
7    Máy xăng
Name: Fuel_Type, dtype: object

In [49]:
df1.Fuel_Type.value_counts()

Fuel_Type
Máy xăng    1083
Máy dầu      210
Điện          15
Hybrid         7
Name: count, dtype: int64

In [50]:
df1.head()

,Name,Year,Tình trạng,Origin,Province,District,Transmission,Fuel_Type,Body_Type,Brand,price_num,age,mileage_num
0,Mercedes-Benz GLC 200 4Matic 2021,2021,Xe cũ,Trong nước,Tp.HCM,Quận 7,Số tự động,Máy xăng,Other,Mercedes-Benz,1389000000,4,55555
2,Kia Sonet 1.5 Premium 2024,2024,Xe cũ,Trong nước,Hà Nội,Nam Từ Liêm,Số tự động,Máy xăng,Crossover,Kia,585000000,1,1000
3,Ford Everest Titanium 2.0L AT 4WD 2019,2019,Xe cũ,Nhập khẩu,Tp.HCM,Other,Số tự động,Máy xăng,SUV,Ford,810000000,6,4
6,Mercedes-Benz GLC 300 4Matic 2016,2016,Xe cũ,Nhập khẩu,Hà Nội,Tây Hồ,Số tự động,Máy xăng,SUV,Mercedes-Benz,885000000,9,90000
7,Mazda 6 2.0 AT 2017,2017,Xe cũ,Trong nước,Hải Phòng,An Lão,Số tự động,Máy xăng,Sedan,Mazda,440000000,8,57225

In [51]:
len(df1)

1315

In [52]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1315 entries, 0 to 1489
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          1315 non-null   object
 1   Year          1315 non-null   int32
 2   Tình trạng    1315 non-null   object
 3   Origin        1315 non-null   object
 4   Province      1315 non-null   object
 5   District      1315 non-null   object
 6   Transmission  1315 non-null   object
 7   Fuel_Type     1315 non-null   object
 8   Body_Type     1315 non-null   object
 9   Brand         1315 non-null   object
 10  price_num     1315 non-null   int64
 11  age           1315 non-null   int32
 12  mileage_num   1315 non-null   int32
dtypes: int32(3), int64(1), object(9)
memory usage: 128.4+ KB

### clean df2

In [53]:
df2 = pd.read_csv("../data/cars_data2.csv")

In [54]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ,Màu ngoại thất,Màu nội thất
0,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz GLC \...,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,Trắng,Đen
1,Xe \n\t\t\t\n\t\t\t\t\t\t\tKia Sedona \n\t\t\t...,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,Trắng,Nâu
2,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz C cla...,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Đen
3,Xe \n\t\t\t\n\t\t\t\t\t\t\tSuzuki XL7 \n\t\t\t...,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,Trắng,Nâu
4,Xe \n\t\t\t\n\t\t\t\t\t\t\tMercedes Benz C cla...,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Kem

In [55]:
import re

def clean_name(text):
    if not isinstance(text, str):
        return None
    text = re.sub(r"Xe\s+", "", text)  
    text = re.sub(r"\s+", " ", text) 
    return text.strip()

df2["Name"] = df2["Name"].apply(clean_name)

In [56]:
import re

def split_name_price(full_name):
    if not isinstance(full_name, str):
        return None, None
    
    if " - " in full_name:
        parts = full_name.rsplit(" - ", 1)
        car = parts[0].strip()
        price_raw = parts[1].strip().lower()
        try:
            price_raw = price_raw.replace(",", ".")  
            matches = re.findall(r"(\d+(?:[\.,]?\d*)?)\s*(tỷ|triệu)", price_raw)
            price = 0
            for value, unit in matches:
                value = float(value.replace(",", ".").replace(".", "")) if "," not in value else float(value.replace(",", "."))
                if unit == "tỷ":
                    price += value * 1_000_000_000
                elif unit == "triệu":
                    price += value * 1_000_000
        except:
            price = None
        return car, price
    return full_name, None

In [57]:
df2[["Name", "Price"]] = df2["Name"].apply(
    lambda x: pd.Series(split_name_price(x))
)

In [58]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ,Màu ngoại thất,Màu nội thất,Price
0,Mercedes Benz GLC 200 2021,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,Trắng,Đen,1.250000e+09
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,Trắng,Nâu,8.750000e+08
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Đen,5.800000e+08
3,Suzuki XL7 1.5 AT 2022,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,Trắng,Nâu,4.990000e+08
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Kem,5.950000e+08

In [59]:
for i in df2.columns :
    print(f"{i} : {df2[i].nunique()}")

Name : 1482
Năm sản xuất : 27
Tình trạng : 2
Số Km đã đi : 331
Xuất xứ : 2
Kiểu dáng : 9
Động cơ : 69
Màu ngoại thất : 17
Màu nội thất : 17
Price : 923

In [60]:
df2.isna().sum()

Name                0
Năm sản xuất        0
Tình trạng          0
Số Km đã đi       592
Xuất xứ             0
Kiểu dáng           0
Động cơ             0
Màu ngoại thất      0
Màu nội thất        0
Price               0
dtype: int64

In [61]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2851 entries, 0 to 2850
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            2851 non-null   object
 1   Năm sản xuất    2851 non-null   int64
 2   Tình trạng      2851 non-null   object
 3   Số Km đã đi     2259 non-null   object
 4   Xuất xứ         2851 non-null   object
 5   Kiểu dáng       2851 non-null   object
 6   Động cơ         2851 non-null   object
 7   Màu ngoại thất  2851 non-null   object
 8   Màu nội thất    2851 non-null   object
 9   Price           2851 non-null   float64
dtypes: float64(1), int64(1), object(8)
memory usage: 222.9+ KB

In [62]:
df2["Số Km đã đi"].describe()

count     2259
unique     331
top       0 Km
freq       205
Name: Số Km đã đi, dtype: object

In [63]:
df2.groupby("Tình trạng")["Số Km đã đi"].describe()

           count unique   top freq
Tình trạng
Xe mới         0      0   NaN  NaN
Xe đã dùng  2259    331  0 Km  205

In [64]:
df2.loc[df2["Số Km đã đi"].isna(),"Số Km đã đi"] = "0 Km"

In [65]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ,Màu ngoại thất,Màu nội thất,Price
0,Mercedes Benz GLC 200 2021,2021,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,SUV,Xăng 2.0 L,Trắng,Đen,1.250000e+09
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe đã dùng,"96,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,Trắng,Nâu,8.750000e+08
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"70,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Đen,5.800000e+08
3,Suzuki XL7 1.5 AT 2022,2022,Xe đã dùng,"65,000 Km",Nhập khẩu,SUV,Xăng 1.5 L,Trắng,Nâu,4.990000e+08
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,"89,000 Km",Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Kem,5.950000e+08

In [66]:
df2['Số Km đã đi'] = (
    df2['Số Km đã đi']
    .str.replace(',', '', regex=False)   
    .str.replace(' Km', '', regex=False)    
    .str.strip()                         
    .astype(float)                      
)

In [67]:
df2["Brand"] = df2["Name"].str.strip().str.split().str[0]

In [68]:
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ,Màu ngoại thất,Màu nội thất,Price,Brand
0,Mercedes Benz GLC 200 2021,2021,Xe đã dùng,60000.0,Lắp ráp trong nước,SUV,Xăng 2.0 L,Trắng,Đen,1.250000e+09,Mercedes
1,Kia Sedona 2.2 DAT Luxury 2021,2021,Xe đã dùng,96000.0,Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,Trắng,Nâu,8.750000e+08,Kia
2,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,70000.0,Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Đen,5.800000e+08,Mercedes
3,Suzuki XL7 1.5 AT 2022,2022,Xe đã dùng,65000.0,Nhập khẩu,SUV,Xăng 1.5 L,Trắng,Nâu,4.990000e+08,Suzuki
4,Mercedes Benz C class C250 Exclusive 2015,2015,Xe đã dùng,89000.0,Lắp ráp trong nước,Sedan,Xăng 2.0 L,Đen,Kem,5.950000e+08,Mercedes

In [69]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1315 entries, 0 to 1489
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          1315 non-null   object
 1   Year          1315 non-null   int32
 2   Tình trạng    1315 non-null   object
 3   Origin        1315 non-null   object
 4   Province      1315 non-null   object
 5   District      1315 non-null   object
 6   Transmission  1315 non-null   object
 7   Fuel_Type     1315 non-null   object
 8   Body_Type     1315 non-null   object
 9   Brand         1315 non-null   object
 10  price_num     1315 non-null   int64
 11  age           1315 non-null   int32
 12  mileage_num   1315 non-null   int32
dtypes: int32(3), int64(1), object(9)
memory usage: 128.4+ KB

In [70]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2851 entries, 0 to 2850
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            2851 non-null   object
 1   Năm sản xuất    2851 non-null   int64
 2   Tình trạng      2851 non-null   object
 3   Số Km đã đi     2851 non-null   float64
 4   Xuất xứ         2851 non-null   object
 5   Kiểu dáng       2851 non-null   object
 6   Động cơ         2851 non-null   object
 7   Màu ngoại thất  2851 non-null   object
 8   Màu nội thất    2851 non-null   object
 9   Price           2851 non-null   float64
 10  Brand           2851 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 245.1+ KB

In [71]:
df2_clean = pd.DataFrame()
df2_clean["Name"] = df2["Name"]
df2_clean["Year"] = df2["Năm sản xuất"]
df2_clean["Tình trạng"] = df2["Tình trạng"]
df2_clean["Origin"] = df2["Xuất xứ"]
df2_clean["Brand"] = df2["Brand"]
df2_clean["Body_Type"] = df2["Kiểu dáng"]
df2_clean["Fuel_Type"] = df2["Động cơ"].str.extract(r'(\w+)', expand=False)  
df2_clean["price_num"] = df2["Price"].astype("int64")
df2_clean["mileage_num"] = df2["Số Km đã đi"].astype("int32")
df2_clean["age"] = 2025 - df2["Năm sản xuất"]  

df2_clean["Transmission"] = None
df2_clean["Province"] = None
df2_clean["District"] = None

In [72]:
df_merged = pd.concat([df1, df2_clean], ignore_index=True)

In [73]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4166 entries, 0 to 4165
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4166 non-null   object
 1   Year          4166 non-null   int64
 2   Tình trạng    4166 non-null   object
 3   Origin        4166 non-null   object
 4   Province      1315 non-null   object
 5   District      1315 non-null   object
 6   Transmission  1315 non-null   object
 7   Fuel_Type     4166 non-null   object
 8   Body_Type     4166 non-null   object
 9   Brand         4166 non-null   object
 10  price_num     4166 non-null   int64
 11  age           4166 non-null   int64
 12  mileage_num   4166 non-null   int32
dtypes: int32(1), int64(3), object(9)
memory usage: 407.0+ KB

In [74]:
df_merged = df_merged.drop(columns=["Province", "District", "Transmission"])

In [75]:
df_merged.to_csv("../data/data_cleaned.csv", index=False, encoding='utf-8-sig')  
print("Done! cleaned")

Done! cleaned