In [1]:
import aiohttp
import asyncio
from bs4 import BeautifulSoup
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import os
import time
import random
import sys
sys.path.append(os.path.abspath(".."))
from config import ENGINE,PROXY,HEADERS

In [2]:
proxy = PROXY

engine = ENGINE

headers = HEADERS

link_page = "https://oto.com.vn/mua-ban-xe"

In [24]:
semaphore = asyncio.Semaphore(random.randint(5,10))
link_set = set()
no_new_count = 0
MAX_NO_NEW = 3

def getlink(soup):
    items = soup.find_all('h3', class_='title')
    links = []
    for item in items:
        a_tag = item.find('a')
        if a_tag and a_tag.get('href'):
            link = 'https://oto.com.vn' + a_tag['href']
            links.append(link)
    return links

async def get_prd(session, i):
    global no_new_count, link_set

    url = f"https://oto.com.vn/mua-ban-xe/p{i}"
    async with semaphore:
        try:
            await asyncio.sleep(random.uniform(0.5 , 1.5))
            async with session.get(url,headers=headers, proxy=proxy, timeout=15) as resp:
                if resp.status != 200:
                    print(f"❌ HTTP {resp.status} at page {i}")
                    return False

                html = await resp.text()
                soup = BeautifulSoup(html, "html.parser")
                link_phones = getlink(soup)

                if not link_phones:
                    print(f"⚠️ No products found on page {i}")
                    return False

                before = len(link_set)
                for link in link_phones:
                    link_set.add(link)
                after = len(link_set)

                if after == before:
                    no_new_count += 1
                    print(f"⚠️ Page {i}: no new links ({no_new_count}/{MAX_NO_NEW})")
                else:
                    no_new_count = 0
                    print(f"✅ Page {i} done. Added {after - before} new products.")

                if no_new_count >= MAX_NO_NEW:
                    print(f"\n⛔ Stopping crawl: {MAX_NO_NEW} consecutive pages with no new links.")
                    return "STOP"

                return True

        except Exception as e:
            print(f"⚠️ Error at page {i}: {e}")
            return False

async def main():
    async with aiohttp.ClientSession() as session:
        for i in range(1, 150):
            result = await get_prd(session, i)
            if result == "STOP":
                break

await main()
print(f"\n📦 Total product links collected: {len(link_set)}")

✅ Page 1 done. Added 19 new products.
✅ Page 2 done. Added 15 new products.
✅ Page 3 done. Added 15 new products.
✅ Page 4 done. Added 15 new products.
✅ Page 5 done. Added 15 new products.
✅ Page 6 done. Added 15 new products.
✅ Page 7 done. Added 15 new products.
✅ Page 8 done. Added 15 new products.
✅ Page 9 done. Added 15 new products.
✅ Page 10 done. Added 15 new products.
✅ Page 11 done. Added 15 new products.
✅ Page 12 done. Added 13 new products.
✅ Page 13 done. Added 15 new products.
✅ Page 14 done. Added 15 new products.
✅ Page 15 done. Added 15 new products.
✅ Page 16 done. Added 15 new products.
✅ Page 17 done. Added 15 new products.
✅ Page 18 done. Added 15 new products.
✅ Page 19 done. Added 15 new products.
✅ Page 20 done. Added 15 new products.
✅ Page 21 done. Added 14 new products.
✅ Page 22 done. Added 15 new products.
✅ Page 23 done. Added 15 new products.
✅ Page 24 done. Added 15 new products.
✅ Page 25 done. Added 11 new products.
✅ Page 26 done. Added 15 new products.
✅ Page 27 done. Added 15 new products.
✅ Page 28 done. Added 15 new products.
✅ Page 29 done. Added 15 new products.
✅ Page 30 done. Added 15 new products.
✅ Page 31 done. Added 15 new products.
✅ Page 32 done. Added 15 new products.
✅ Page 33 done. Added 15 new products.
✅ Page 34 done. Added 15 new products.
✅ Page 35 done. Added 15 new products.
✅ Page 36 done. Added 15 new products.
✅ Page 37 done. Added 15 new products.
✅ Page 38 done. Added 15 new products.
✅ Page 39 done. Added 15 new products.
✅ Page 40 done. Added 15 new products.
✅ Page 41 done. Added 15 new products.
✅ Page 42 done. Added 15 new products.
✅ Page 43 done. Added 15 new products.
✅ Page 44 done. Added 15 new products.
✅ Page 45 done. Added 15 new products.
✅ Page 46 done. Added 15 new products.
✅ Page 47 done. Added 15 new products.
✅ Page 48 done. Added 15 new products.
✅ Page 49 done. Added 15 new products.
✅ Page 50 done. Added 15 new products.
✅ Page 51 done. Added 15 new products.
✅ Page 52 done. Added 15 new products.
✅ Page 53 done. Added 15 new products.
✅ Page 54 done. Added 15 new products.
✅ Page 55 done. Added 15 new products.
✅ Page 56 done. Added 15 new products.
✅ Page 57 done. Added 15 new products.
✅ Page 58 done. Added 15 new products.
✅ Page 59 done. Added 15 new products.
✅ Page 60 done. Added 15 new products.
✅ Page 61 done. Added 15 new products.
✅ Page 62 done. Added 15 new products.
✅ Page 63 done. Added 15 new products.
✅ Page 64 done. Added 15 new products.
✅ Page 65 done. Added 15 new products.
✅ Page 66 done. Added 15 new products.
✅ Page 67 done. Added 15 new products.
✅ Page 68 done. Added 15 new products.
✅ Page 69 done. Added 15 new products.
✅ Page 70 done. Added 15 new products.
✅ Page 71 done. Added 15 new products.
✅ Page 72 done. Added 15 new products.
✅ Page 73 done. Added 15 new products.
✅ Page 74 done. Added 15 new products.
✅ Page 75 done. Added 15 new products.
✅ Page 76 done. Added 15 new products.
✅ Page 77 done. Added 15 new products.
✅ Page 78 done. Added 15 new products.
✅ Page 79 done. Added 15 new products.
✅ Page 80 done. Added 15 new products.
✅ Page 81 done. Added 15 new products.
✅ Page 82 done. Added 15 new products.
✅ Page 83 done. Added 15 new products.
✅ Page 84 done. Added 15 new products.
✅ Page 85 done. Added 15 new products.
✅ Page 86 done. Added 15 new products.
✅ Page 87 done. Added 15 new products.
✅ Page 88 done. Added 13 new products.
✅ Page 89 done. Added 14 new products.
✅ Page 90 done. Added 15 new products.
✅ Page 91 done. Added 15 new products.
✅ Page 92 done. Added 15 new products.
✅ Page 93 done. Added 15 new products.
✅ Page 94 done. Added 15 new products.
✅ Page 95 done. Added 15 new products.
✅ Page 96 done. Added 15 new products.
✅ Page 97 done. Added 15 new products.
✅ Page 98 done. Added 15 new products.
✅ Page 99 done. Added 15 new products.
✅ Page 100 done. Added 15 new products.
⚠️ Page 101: no new links (1/3)
⚠️ Page 102: no new links (2/3)
⚠️ Page 103: no new links (3/3)

⛔ Stopping crawl: 3 consecutive pages with no new links.

📦 Total product links collected: 1494

In [41]:
semaphore = asyncio.Semaphore(random.randint(3, 5))
all_cars = []
MAX_RETRIES = 3

async def fetch_detail(session, link, idx, total):
    async with semaphore:
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                await asyncio.sleep(random.uniform(0.3, 1))
                async with session.get(link, headers=headers, proxy=proxy, timeout=20) as resp:
                    if resp.status != 200:
                        print(f"❌ [{idx}/{total}] HTTP {resp.status} at {link}")
                        continue

                    html = await resp.read()
                    html = html.decode('utf-8', errors='ignore')
                    soup = BeautifulSoup(html, "html.parser")

                    car_info = {}

                    name_tag = soup.find("div", class_="group-title-detail")
                    name = name_tag.find_next("h1", class_="title-detail").get_text(strip=True) if name_tag else None
                    car_info["Name"] = name

                    price_tag = soup.find("span", class_="price")
                    price = price_tag.get_text(strip=True) if price_tag else None
                    car_info["Price"] = price

                    labels = soup.find_all("label", class_="label")
                    for label in labels:
                        key = label.get_text(strip=True)
                        value_node = label.find_next_sibling(text=True)
                        if not value_node or value_node.strip() == "":
                            div = label.find_next("div")
                            value = div.get_text(strip=True) if div else "N/A"
                        else:
                            value = value_node.strip()
                        car_info[key] = value

                    print(f"✅ Done car {idx}/{total}")
                    return car_info

            except Exception as e:
                print(f"⚠️ [{idx}/{total}] Attempt {attempt}/{MAX_RETRIES} failed for {link}: {e}")
                if attempt < MAX_RETRIES:
                    await asyncio.sleep(2 * attempt)
                else:
                    print(f"⛔ [{idx}/{total}] Giving up on {link} after {MAX_RETRIES} attempts.")
                    return None


async def main():
    global all_cars
    async with aiohttp.ClientSession() as session:
        tasks = [fetch_detail(session, link, i, len(link_set)) 
                 for i, link in enumerate(link_set, 1)]
        results = await asyncio.gather(*tasks)
        all_cars = [r for r in results if r is not None]

await main()
print(f"\n📦 Total product details collected: {len(all_cars)}/{len(link_set)}")

✅ Done car 5/1494
✅ Done car 3/1494
✅ Done car 2/1494
✅ Done car 1/1494
✅ Done car 4/1494
✅ Done car 6/1494
✅ Done car 7/1494
✅ Done car 8/1494
✅ Done car 10/1494
✅ Done car 9/1494
✅ Done car 12/1494
✅ Done car 13/1494
✅ Done car 11/1494
✅ Done car 14/1494
✅ Done car 15/1494
✅ Done car 16/1494
✅ Done car 18/1494
✅ Done car 17/1494
✅ Done car 19/1494
✅ Done car 20/1494
✅ Done car 21/1494
✅ Done car 22/1494
✅ Done car 23/1494
✅ Done car 24/1494
⚠️ [26/1494] Attempt 1/3 failed for https://oto.com.vnhttps://thaihoanglongauto.oto.com.vn: 502, message='Bad Gateway', url=URL('http://lXnKoa:xXs8eU@xoay300s.proxyipv4.org:26779')
✅ Done car 25/1494
✅ Done car 27/1494
✅ Done car 28/1494
✅ Done car 29/1494
✅ Done car 30/1494
✅ Done car 31/1494
✅ Done car 32/1494
✅ Done car 33/1494
✅ Done car 34/1494
✅ Done car 36/1494
⚠️ [26/1494] Attempt 2/3 failed for https://oto.com.vnhttps://thaihoanglongauto.oto.com.vn: 502, message='Bad Gateway', url=URL('http://lXnKoa:xXs8eU@xoay300s.proxyipv4.org:26779')
✅ Done car 35/1494
✅ Done car 37/1494
✅ Done car 39/1494
✅ Done car 40/1494
✅ Done car 38/1494
✅ Done car 42/1494
✅ Done car 43/1494
✅ Done car 41/1494
✅ Done car 44/1494
✅ Done car 45/1494
✅ Done car 46/1494
✅ Done car 47/1494
✅ Done car 48/1494
✅ Done car 49/1494
⚠️ [26/1494] Attempt 3/3 failed for https://oto.com.vnhttps://thaihoanglongauto.oto.com.vn: 502, message='Bad Gateway', url=URL('http://lXnKoa:xXs8eU@xoay300s.proxyipv4.org:26779')
⛔ [26/1494] Giving up on https://oto.com.vnhttps://thaihoanglongauto.oto.com.vn after 3 attempts.
✅ Done car 51/1494
✅ Done car 52/1494
✅ Done car 54/1494
✅ Done car 53/1494
✅ Done car 55/1494
✅ Done car 56/1494
✅ Done car 58/1494
✅ Done car 57/1494
✅ Done car 59/1494
✅ Done car 60/1494
✅ Done car 62/1494
✅ Done car 61/1494
✅ Done car 63/1494
✅ Done car 64/1494
✅ Done car 66/1494
✅ Done car 65/1494
✅ Done car 67/1494
✅ Done car 68/1494
✅ Done car 69/1494
✅ Done car 70/1494
✅ Done car 71/1494
✅ Done car 72/1494
✅ Done car 73/1494
✅ Done car 74/1494
✅ Done car 75/1494
✅ Done car 76/1494
✅ Done car 77/1494
✅ Done car 78/1494
✅ Done car 79/1494
✅ Done car 80/1494
✅ Done car 81/1494
✅ Done car 84/1494
✅ Done car 82/1494
✅ Done car 83/1494
✅ Done car 85/1494
✅ Done car 86/1494
✅ Done car 87/1494
✅ Done car 89/1494
✅ Done car 88/1494
✅ Done car 90/1494
✅ Done car 91/1494
✅ Done car 93/1494
✅ Done car 92/1494
✅ Done car 94/1494
✅ Done car 96/1494
✅ Done car 95/1494
✅ Done car 97/1494
✅ Done car 98/1494
✅ Done car 100/1494
✅ Done car 99/1494
✅ Done car 102/1494
✅ Done car 101/1494
✅ Done car 103/1494
✅ Done car 104/1494
✅ Done car 105/1494
✅ Done car 106/1494
✅ Done car 107/1494
✅ Done car 108/1494
⚠️ [50/1494] Attempt 1/3 failed for https://oto.com.vn/mua-ban-xe-hyundai-grand-i10-hcm/2020-hatchback-12-at-83000-km-aidxc23348667:
✅ Done car 109/1494
✅ Done car 110/1494
✅ Done car 112/1494
✅ Done car 111/1494
✅ Done car 114/1494
✅ Done car 113/1494
✅ Done car 115/1494
✅ Done car 116/1494
✅ Done car 118/1494
✅ Done car 117/1494
✅ Done car 50/1494
✅ Done car 120/1494
✅ Done car 119/1494
✅ Done car 122/1494
✅ Done car 121/1494
✅ Done car 123/1494
✅ Done car 124/1494
✅ Done car 125/1494
✅ Done car 127/1494
✅ Done car 126/1494
✅ Done car 128/1494
✅ Done car 129/1494
✅ Done car 130/1494
✅ Done car 132/1494
✅ Done car 131/1494
✅ Done car 133/1494
✅ Done car 134/1494
✅ Done car 136/1494
✅ Done car 135/1494
✅ Done car 137/1494
✅ Done car 138/1494
✅ Done car 140/1494
✅ Done car 139/1494
✅ Done car 141/1494
✅ Done car 143/1494
✅ Done car 142/1494
✅ Done car 144/1494
✅ Done car 145/1494
✅ Done car 147/1494
✅ Done car 146/1494
✅ Done car 148/1494
✅ Done car 149/1494
✅ Done car 150/1494
✅ Done car 151/1494
✅ Done car 153/1494
✅ Done car 154/1494
✅ Done car 155/1494
✅ Done car 157/1494
✅ Done car 156/1494
✅ Done car 152/1494
✅ Done car 159/1494
✅ Done car 160/1494
✅ Done car 158/1494
✅ Done car 161/1494
✅ Done car 162/1494
✅ Done car 163/1494
✅ Done car 164/1494
✅ Done car 167/1494
✅ Done car 165/1494
✅ Done car 166/1494
✅ Done car 169/1494
✅ Done car 168/1494
✅ Done car 170/1494
✅ Done car 171/1494
✅ Done car 172/1494
✅ Done car 173/1494
✅ Done car 175/1494
✅ Done car 174/1494
✅ Done car 176/1494
✅ Done car 178/1494
✅ Done car 177/1494
✅ Done car 180/1494
✅ Done car 179/1494
✅ Done car 182/1494
✅ Done car 181/1494
✅ Done car 184/1494
✅ Done car 183/1494
✅ Done car 185/1494
✅ Done car 186/1494
✅ Done car 187/1494
✅ Done car 189/1494
✅ Done car 188/1494
✅ Done car 190/1494
✅ Done car 192/1494
✅ Done car 193/1494
✅ Done car 191/1494
✅ Done car 195/1494
✅ Done car 194/1494
✅ Done car 196/1494
✅ Done car 198/1494
✅ Done car 197/1494
✅ Done car 200/1494
✅ Done car 199/1494
✅ Done car 202/1494
✅ Done car 201/1494
✅ Done car 203/1494
✅ Done car 204/1494
✅ Done car 205/1494
✅ Done car 206/1494
⚠️ [208/1494] Attempt 1/3 failed for https://oto.com.vn/mua-ban-xe-hongqi-e-hs9-ha-noi/hien-dai-quyen-luc-thuong-luu-aidxc23338662:
⚠️ [207/1494] Attempt 1/3 failed for https://oto.com.vn/mua-ban-xe-mazda-cx-8-hcm/2019-luxury-72000-km-aidxc23347729:
⚠️ [209/1494] Attempt 1/3 failed for https://oto.com.vn/mua-ban-xe-kia-cerato-hcm/2020-20-at-premium-32900-km-aidxc23345672: Cannot connect to host oto.com.vn:443 ssl:default [None]
⚠️ [210/1494] Attempt 1/3 failed for https://oto.com.vn/mua-ban-xe-ford-ecosport-hcm/ban-15l-at-2017-5-cho-gam-cao-so-tu-dong-aidxc23342763: Cannot connect to host oto.com.vn:443 ssl:default [None]
⚠️ [211/1494] Attempt 1/3 failed for https://oto.com.vn/mua-ban-xe-mazda-cx-5-ha-noi/xe-dang-ky-tu-nhan-cong-chuc-aidxc23348657: Cannot connect to host oto.com.vn:443 ssl:default [None]
✅ Done car 209/1494
✅ Done car 210/1494
✅ Done car 211/1494
✅ Done car 208/1494
✅ Done car 207/1494
✅ Done car 213/1494
✅ Done car 212/1494
✅ Done car 215/1494
✅ Done car 214/1494
✅ Done car 216/1494
✅ Done car 217/1494
✅ Done car 219/1494
✅ Done car 220/1494
✅ Done car 218/1494
✅ Done car 221/1494
✅ Done car 222/1494
✅ Done car 223/1494
✅ Done car 225/1494
✅ Done car 224/1494
✅ Done car 228/1494
✅ Done car 227/1494
✅ Done car 226/1494
✅ Done car 230/1494
✅ Done car 229/1494
✅ Done car 231/1494
✅ Done car 233/1494
✅ Done car 232/1494
✅ Done car 236/1494
✅ Done car 235/1494
✅ Done car 234/1494
✅ Done car 238/1494
✅ Done car 240/1494
✅ Done car 239/1494
✅ Done car 237/1494
✅ Done car 241/1494
✅ Done car 242/1494
✅ Done car 244/1494
✅ Done car 243/1494
✅ Done car 245/1494
✅ Done car 246/1494
✅ Done car 247/1494
✅ Done car 249/1494
✅ Done car 248/1494
✅ Done car 250/1494
✅ Done car 252/1494
✅ Done car 251/1494
✅ Done car 255/1494
✅ Done car 253/1494
✅ Done car 256/1494
✅ Done car 257/1494
✅ Done car 258/1494
✅ Done car 260/1494
✅ Done car 259/1494
✅ Done car 261/1494
✅ Done car 254/1494
✅ Done car 262/1494
✅ Done car 264/1494
✅ Done car 263/1494
✅ Done car 266/1494
✅ Done car 265/1494
✅ Done car 267/1494
✅ Done car 268/1494
✅ Done car 271/1494
✅ Done car 269/1494
✅ Done car 270/1494
✅ Done car 272/1494
✅ Done car 273/1494
✅ Done car 275/1494
✅ Done car 274/1494
✅ Done car 277/1494
✅ Done car 276/1494
✅ Done car 278/1494
✅ Done car 280/1494
✅ Done car 279/1494
✅ Done car 282/1494
✅ Done car 281/1494
✅ Done car 283/1494
✅ Done car 284/1494
✅ Done car 285/1494
✅ Done car 288/1494
✅ Done car 286/1494
✅ Done car 287/1494
✅ Done car 289/1494
✅ Done car 290/1494
✅ Done car 291/1494
✅ Done car 292/1494
✅ Done car 293/1494
✅ Done car 294/1494
✅ Done car 295/1494
✅ Done car 296/1494
✅ Done car 298/1494
✅ Done car 297/1494
✅ Done car 300/1494
✅ Done car 299/1494
✅ Done car 301/1494
✅ Done car 303/1494
✅ Done car 302/1494
✅ Done car 305/1494
✅ Done car 304/1494
✅ Done car 306/1494
✅ Done car 308/1494
✅ Done car 310/1494
✅ Done car 307/1494
✅ Done car 309/1494
✅ Done car 313/1494
✅ Done car 312/1494
✅ Done car 314/1494
✅ Done car 315/1494
✅ Done car 311/1494
✅ Done car 316/1494
✅ Done car 317/1494
✅ Done car 318/1494
✅ Done car 319/1494
✅ Done car 320/1494
✅ Done car 322/1494
✅ Done car 321/1494
✅ Done car 325/1494
✅ Done car 324/1494
✅ Done car 323/1494
✅ Done car 326/1494
✅ Done car 327/1494
✅ Done car 328/1494
✅ Done car 330/1494
✅ Done car 331/1494
✅ Done car 329/1494
✅ Done car 334/1494
✅ Done car 333/1494
✅ Done car 332/1494
✅ Done car 335/1494
✅ Done car 336/1494
✅ Done car 337/1494
✅ Done car 338/1494
✅ Done car 339/1494
✅ Done car 340/1494
✅ Done car 343/1494
✅ Done car 341/1494
✅ Done car 342/1494
✅ Done car 344/1494
✅ Done car 345/1494
✅ Done car 346/1494
✅ Done car 347/1494
✅ Done car 348/1494
✅ Done car 349/1494
✅ Done car 350/1494
✅ Done car 351/1494
✅ Done car 352/1494
✅ Done car 354/1494
✅ Done car 353/1494
✅ Done car 355/1494
✅ Done car 357/1494
✅ Done car 356/1494
✅ Done car 358/1494
✅ Done car 359/1494
✅ Done car 360/1494
✅ Done car 362/1494
✅ Done car 361/1494
✅ Done car 363/1494
✅ Done car 364/1494
✅ Done car 365/1494
✅ Done car 366/1494
✅ Done car 368/1494
✅ Done car 369/1494
✅ Done car 367/1494
✅ Done car 372/1494
✅ Done car 371/1494
✅ Done car 370/1494
✅ Done car 374/1494
✅ Done car 373/1494
✅ Done car 375/1494
✅ Done car 378/1494
✅ Done car 377/1494
✅ Done car 376/1494
✅ Done car 380/1494
✅ Done car 382/1494
✅ Done car 379/1494
✅ Done car 381/1494
✅ Done car 383/1494
✅ Done car 384/1494
✅ Done car 388/1494
✅ Done car 385/1494
✅ Done car 386/1494
✅ Done car 387/1494
✅ Done car 389/1494
✅ Done car 390/1494
✅ Done car 391/1494
✅ Done car 392/1494
✅ Done car 393/1494
✅ Done car 394/1494
✅ Done car 395/1494
✅ Done car 396/1494
✅ Done car 397/1494
✅ Done car 398/1494
✅ Done car 399/1494
✅ Done car 400/1494
✅ Done car 402/1494
✅ Done car 401/1494
✅ Done car 403/1494
✅ Done car 404/1494
✅ Done car 405/1494
✅ Done car 406/1494
✅ Done car 407/1494
✅ Done car 408/1494
✅ Done car 409/1494
✅ Done car 411/1494
✅ Done car 410/1494
✅ Done car 412/1494
✅ Done car 413/1494
✅ Done car 414/1494
✅ Done car 415/1494
✅ Done car 417/1494
✅ Done car 416/1494
✅ Done car 418/1494
✅ Done car 420/1494
✅ Done car 419/1494
✅ Done car 422/1494
✅ Done car 421/1494
✅ Done car 423/1494
✅ Done car 424/1494
✅ Done car 426/1494
✅ Done car 427/1494
✅ Done car 425/1494
✅ Done car 429/1494
✅ Done car 430/1494
✅ Done car 428/1494
✅ Done car 431/1494
✅ Done car 433/1494
✅ Done car 432/1494
✅ Done car 435/1494
✅ Done car 436/1494
✅ Done car 434/1494
✅ Done car 438/1494
✅ Done car 439/1494
✅ Done car 437/1494
✅ Done car 441/1494
✅ Done car 440/1494
✅ Done car 443/1494
✅ Done car 442/1494
✅ Done car 446/1494
✅ Done car 445/1494
✅ Done car 444/1494
✅ Done car 448/1494
✅ Done car 449/1494
✅ Done car 447/1494
✅ Done car 451/1494
✅ Done car 450/1494
✅ Done car 452/1494
✅ Done car 455/1494
✅ Done car 453/1494
✅ Done car 456/1494
✅ Done car 454/1494
✅ Done car 457/1494
✅ Done car 458/1494
✅ Done car 461/1494
✅ Done car 460/1494
✅ Done car 459/1494
✅ Done car 462/1494
✅ Done car 463/1494
✅ Done car 464/1494
✅ Done car 466/1494
✅ Done car 465/1494
✅ Done car 467/1494
✅ Done car 468/1494
✅ Done car 472/1494
✅ Done car 469/1494
✅ Done car 470/1494
✅ Done car 474/1494
✅ Done car 473/1494
✅ Done car 471/1494
✅ Done car 475/1494
✅ Done car 477/1494
✅ Done car 476/1494
✅ Done car 478/1494
✅ Done car 479/1494
✅ Done car 480/1494
✅ Done car 481/1494
✅ Done car 482/1494
✅ Done car 483/1494
✅ Done car 484/1494
✅ Done car 487/1494
✅ Done car 486/1494
✅ Done car 485/1494
✅ Done car 491/1494
✅ Done car 488/1494
✅ Done car 489/1494
✅ Done car 490/1494
✅ Done car 493/1494
✅ Done car 492/1494
✅ Done car 494/1494
✅ Done car 495/1494
✅ Done car 496/1494
✅ Done car 499/1494
✅ Done car 497/1494
✅ Done car 498/1494
✅ Done car 500/1494
✅ Done car 501/1494
✅ Done car 502/1494
✅ Done car 505/1494
✅ Done car 503/1494
✅ Done car 504/1494
✅ Done car 506/1494
✅ Done car 507/1494
✅ Done car 510/1494
✅ Done car 508/1494
✅ Done car 509/1494
✅ Done car 511/1494
✅ Done car 513/1494
✅ Done car 514/1494
✅ Done car 512/1494
✅ Done car 515/1494
✅ Done car 516/1494
✅ Done car 518/1494
✅ Done car 520/1494
✅ Done car 517/1494
✅ Done car 519/1494
✅ Done car 522/1494
✅ Done car 521/1494
✅ Done car 524/1494
✅ Done car 523/1494
✅ Done car 525/1494
✅ Done car 526/1494
✅ Done car 527/1494
✅ Done car 528/1494
✅ Done car 530/1494
✅ Done car 529/1494
✅ Done car 531/1494
✅ Done car 532/1494
✅ Done car 534/1494
✅ Done car 535/1494
✅ Done car 533/1494
✅ Done car 537/1494
✅ Done car 536/1494
✅ Done car 539/1494
✅ Done car 540/1494
✅ Done car 538/1494
✅ Done car 541/1494
✅ Done car 543/1494
✅ Done car 542/1494
✅ Done car 546/1494
✅ Done car 547/1494
✅ Done car 545/1494
✅ Done car 544/1494
✅ Done car 549/1494
✅ Done car 548/1494
✅ Done car 550/1494
✅ Done car 552/1494
✅ Done car 551/1494
✅ Done car 553/1494
✅ Done car 554/1494
✅ Done car 555/1494
✅ Done car 557/1494
✅ Done car 558/1494
✅ Done car 556/1494
✅ Done car 560/1494
✅ Done car 559/1494
✅ Done car 561/1494
✅ Done car 562/1494
✅ Done car 563/1494
✅ Done car 564/1494
✅ Done car 565/1494
✅ Done car 566/1494
✅ Done car 567/1494
✅ Done car 568/1494
✅ Done car 570/1494
✅ Done car 569/1494
✅ Done car 571/1494
✅ Done car 573/1494
✅ Done car 572/1494
✅ Done car 575/1494
✅ Done car 576/1494
✅ Done car 574/1494
✅ Done car 578/1494
✅ Done car 577/1494
✅ Done car 579/1494
✅ Done car 581/1494
✅ Done car 580/1494
✅ Done car 582/1494
✅ Done car 583/1494
✅ Done car 584/1494
✅ Done car 586/1494
✅ Done car 585/1494
✅ Done car 587/1494
✅ Done car 590/1494
✅ Done car 588/1494
✅ Done car 591/1494
✅ Done car 589/1494
✅ Done car 592/1494
✅ Done car 593/1494
✅ Done car 594/1494
✅ Done car 595/1494
✅ Done car 597/1494
✅ Done car 596/1494
✅ Done car 598/1494
✅ Done car 601/1494
✅ Done car 600/1494
✅ Done car 599/1494
✅ Done car 604/1494
✅ Done car 603/1494
✅ Done car 602/1494
✅ Done car 605/1494
✅ Done car 606/1494
✅ Done car 608/1494
✅ Done car 609/1494
✅ Done car 610/1494
✅ Done car 611/1494
✅ Done car 607/1494
✅ Done car 612/1494
✅ Done car 613/1494
✅ Done car 615/1494
✅ Done car 614/1494
✅ Done car 616/1494
✅ Done car 617/1494
✅ Done car 618/1494
✅ Done car 619/1494
✅ Done car 620/1494
✅ Done car 621/1494
✅ Done car 623/1494
✅ Done car 622/1494
✅ Done car 625/1494
✅ Done car 626/1494
✅ Done car 624/1494
✅ Done car 627/1494
✅ Done car 628/1494
✅ Done car 629/1494
✅ Done car 631/1494
✅ Done car 630/1494
✅ Done car 632/1494
✅ Done car 633/1494
✅ Done car 635/1494
✅ Done car 636/1494
✅ Done car 634/1494
✅ Done car 638/1494
✅ Done car 637/1494
✅ Done car 639/1494
✅ Done car 641/1494
✅ Done car 640/1494
✅ Done car 643/1494
✅ Done car 642/1494
✅ Done car 644/1494
✅ Done car 645/1494
✅ Done car 646/1494
✅ Done car 648/1494
✅ Done car 647/1494
✅ Done car 649/1494
✅ Done car 650/1494
✅ Done car 651/1494
✅ Done car 652/1494
✅ Done car 653/1494
✅ Done car 654/1494
✅ Done car 655/1494
✅ Done car 656/1494
✅ Done car 657/1494
✅ Done car 658/1494
✅ Done car 660/1494
✅ Done car 661/1494
✅ Done car 659/1494
✅ Done car 663/1494
✅ Done car 664/1494
✅ Done car 662/1494
✅ Done car 665/1494
✅ Done car 666/1494
✅ Done car 667/1494
✅ Done car 668/1494
✅ Done car 670/1494
✅ Done car 672/1494
✅ Done car 671/1494
✅ Done car 673/1494
✅ Done car 669/1494
✅ Done car 674/1494
✅ Done car 676/1494
✅ Done car 675/1494
✅ Done car 677/1494
✅ Done car 679/1494
✅ Done car 678/1494
✅ Done car 681/1494
✅ Done car 680/1494
✅ Done car 684/1494
✅ Done car 682/1494
✅ Done car 683/1494
✅ Done car 685/1494
✅ Done car 686/1494
✅ Done car 689/1494
✅ Done car 688/1494
✅ Done car 690/1494
✅ Done car 687/1494
✅ Done car 691/1494
✅ Done car 692/1494
✅ Done car 693/1494
✅ Done car 694/1494
✅ Done car 695/1494
✅ Done car 697/1494
✅ Done car 696/1494
✅ Done car 700/1494
✅ Done car 698/1494
✅ Done car 699/1494
✅ Done car 701/1494
✅ Done car 702/1494
✅ Done car 703/1494
✅ Done car 705/1494
✅ Done car 704/1494
✅ Done car 707/1494
✅ Done car 706/1494
✅ Done car 708/1494
✅ Done car 709/1494
✅ Done car 712/1494
✅ Done car 711/1494
✅ Done car 710/1494
✅ Done car 713/1494
✅ Done car 714/1494
✅ Done car 715/1494
✅ Done car 716/1494
✅ Done car 717/1494
✅ Done car 718/1494
✅ Done car 719/1494
✅ Done car 720/1494
✅ Done car 721/1494
✅ Done car 722/1494
✅ Done car 725/1494
✅ Done car 726/1494
✅ Done car 723/1494
✅ Done car 724/1494
✅ Done car 728/1494
✅ Done car 727/1494
✅ Done car 731/1494
✅ Done car 730/1494
✅ Done car 733/1494
✅ Done car 732/1494
✅ Done car 729/1494
✅ Done car 734/1494
✅ Done car 735/1494
✅ Done car 736/1494
✅ Done car 737/1494
✅ Done car 738/1494
✅ Done car 741/1494
✅ Done car 739/1494
✅ Done car 740/1494
✅ Done car 742/1494
✅ Done car 743/1494
✅ Done car 746/1494
✅ Done car 745/1494
✅ Done car 744/1494
✅ Done car 747/1494
✅ Done car 748/1494
✅ Done car 749/1494
✅ Done car 751/1494
✅ Done car 750/1494
✅ Done car 753/1494
✅ Done car 752/1494
✅ Done car 754/1494
✅ Done car 756/1494
✅ Done car 757/1494
✅ Done car 755/1494
✅ Done car 758/1494
✅ Done car 759/1494
✅ Done car 760/1494
✅ Done car 761/1494
✅ Done car 762/1494
✅ Done car 763/1494
✅ Done car 765/1494
✅ Done car 764/1494
✅ Done car 766/1494
✅ Done car 768/1494
✅ Done car 770/1494
✅ Done car 769/1494
✅ Done car 767/1494
✅ Done car 771/1494
✅ Done car 772/1494
✅ Done car 775/1494
✅ Done car 774/1494
✅ Done car 773/1494
✅ Done car 776/1494
✅ Done car 777/1494
✅ Done car 779/1494
✅ Done car 780/1494
✅ Done car 778/1494
✅ Done car 781/1494
✅ Done car 783/1494
✅ Done car 782/1494
✅ Done car 785/1494
✅ Done car 784/1494
✅ Done car 786/1494
✅ Done car 787/1494
✅ Done car 788/1494
✅ Done car 789/1494
✅ Done car 791/1494
✅ Done car 792/1494
✅ Done car 790/1494
✅ Done car 794/1494
✅ Done car 793/1494
✅ Done car 796/1494
✅ Done car 797/1494
✅ Done car 798/1494
✅ Done car 799/1494
✅ Done car 795/1494
✅ Done car 800/1494
✅ Done car 801/1494
✅ Done car 803/1494
✅ Done car 802/1494
✅ Done car 806/1494
✅ Done car 805/1494
✅ Done car 804/1494
✅ Done car 807/1494
✅ Done car 808/1494
✅ Done car 810/1494
✅ Done car 811/1494
✅ Done car 809/1494
✅ Done car 812/1494
✅ Done car 813/1494
✅ Done car 814/1494
✅ Done car 817/1494
✅ Done car 816/1494
✅ Done car 815/1494
✅ Done car 818/1494
✅ Done car 819/1494
✅ Done car 820/1494
✅ Done car 821/1494
✅ Done car 822/1494
✅ Done car 824/1494
✅ Done car 823/1494
✅ Done car 825/1494
✅ Done car 826/1494
✅ Done car 827/1494
✅ Done car 829/1494
✅ Done car 828/1494
✅ Done car 830/1494
✅ Done car 831/1494
✅ Done car 832/1494
✅ Done car 834/1494
✅ Done car 833/1494
✅ Done car 835/1494
✅ Done car 836/1494
✅ Done car 837/1494
✅ Done car 838/1494
✅ Done car 839/1494
✅ Done car 841/1494
✅ Done car 840/1494
✅ Done car 843/1494
✅ Done car 844/1494
✅ Done car 842/1494
✅ Done car 845/1494
✅ Done car 846/1494
✅ Done car 847/1494
✅ Done car 848/1494
✅ Done car 849/1494
✅ Done car 850/1494
✅ Done car 852/1494
✅ Done car 851/1494
✅ Done car 854/1494
✅ Done car 853/1494
✅ Done car 855/1494
✅ Done car 856/1494
✅ Done car 857/1494
✅ Done car 858/1494
✅ Done car 860/1494
✅ Done car 859/1494
✅ Done car 861/1494
✅ Done car 862/1494
✅ Done car 863/1494
✅ Done car 866/1494
✅ Done car 865/1494
✅ Done car 864/1494
✅ Done car 867/1494
✅ Done car 868/1494
✅ Done car 869/1494
✅ Done car 870/1494
✅ Done car 871/1494
✅ Done car 872/1494
✅ Done car 873/1494
✅ Done car 874/1494
✅ Done car 875/1494
✅ Done car 877/1494
✅ Done car 876/1494
✅ Done car 878/1494
✅ Done car 879/1494
✅ Done car 880/1494
✅ Done car 881/1494
✅ Done car 882/1494
✅ Done car 883/1494
✅ Done car 885/1494
✅ Done car 884/1494
✅ Done car 886/1494
✅ Done car 888/1494
✅ Done car 887/1494
✅ Done car 889/1494
✅ Done car 891/1494
✅ Done car 890/1494
✅ Done car 893/1494
✅ Done car 894/1494
✅ Done car 892/1494
✅ Done car 896/1494
✅ Done car 895/1494
✅ Done car 897/1494
✅ Done car 898/1494
✅ Done car 899/1494
✅ Done car 900/1494
✅ Done car 902/1494
✅ Done car 901/1494
✅ Done car 903/1494
✅ Done car 904/1494
✅ Done car 905/1494
✅ Done car 906/1494
✅ Done car 907/1494
✅ Done car 908/1494
✅ Done car 909/1494
✅ Done car 910/1494
✅ Done car 911/1494
✅ Done car 912/1494
✅ Done car 913/1494
✅ Done car 914/1494
✅ Done car 915/1494
✅ Done car 916/1494
✅ Done car 917/1494
✅ Done car 918/1494
✅ Done car 919/1494
✅ Done car 920/1494
✅ Done car 921/1494
✅ Done car 922/1494
✅ Done car 924/1494
✅ Done car 923/1494
✅ Done car 925/1494
✅ Done car 926/1494

In [42]:
df1 = pd.DataFrame(all_cars)
df1.head()

,Name,Price,Năm SX,Kiểu dáng,Tình trạng,Xuất xứ,Km đã đi,Tỉnh thành,Hộp số,Nhiên liệu,Số tiền vay,Thời gian vay,Lãi xuất (%),Loại hình,Giá trị xe muốn mua,Quận huyện,Full lịch sử hãng
0,Toyota Fortuner 2.4G 4x2 AT 2017,525 triệu,2017,SUV,Xe cũ,Nhập khẩu,135 km,Nghệ An,Số sàn,Máy dầu,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,NaN,NaN
1,Suzuki Swift 1.4 AT 2013,269 triệu,2013,Hatchback,Xe cũ,Nhập khẩu,132.000 km,Tp.HCM,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,Tân Phú,NaN
2,Volvo XC60 B6 Ultimate Bright 2023,2 tỉ 190 triệu,2023,SUV,Xe cũ,Nhập khẩu,120 km,Hà Nội,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,Long Biên,NaN
3,Hyundai Stargazer 1.5 AT Cao cấp 2022,455 triệu,2022,MPV,Xe cũ,Nhập khẩu,72.000 km,Long An,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,NaN,NaN
4,Nissan X trail 2018,465 triệu,2018,SUV,Xe cũ,Trong nước,110.000 km,Long An,Số tự động,Máy xăng,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ,Tân An,NaN

In [43]:
df1.to_sql("car_data1", engine, if_exists="replace", index=False)
print(f"✅ Saved {len(df1)} rows to PostgreSQL table 'car_data1'")

✅ Saved 1490 rows to PostgreSQL table 'car_data1'

link-page2 = "https://bonbanh.com/oto/page,1"

In [32]:
semaphore = asyncio.Semaphore(random.randint(5, 10))
link_set_bonbanh = set()
no_new_count = 0
MAX_NO_NEW = 3

def extract_links_bonbanh(soup):
    items = soup.find_all("li", class_=["car-item row1", "car-item row2"])
    links = []
    for item in items:
        a_tag = item.find("a", itemprop="url")
        if a_tag and a_tag.get("href"):
            link = "https://bonbanh.com/" + a_tag.get("href")
            links.append(link)
    return links

async def get_links_bonbanh(session, i):
    global no_new_count, link_set_bonbanh

    url = f"https://bonbanh.com/oto/page,{i}"
    async with semaphore:
        try:
            await asyncio.sleep(random.uniform(0.5, 1.5))
            async with session.get(url,headers=headers,proxy=proxy, timeout=15) as resp:
                if resp.status != 200:
                    print(f"❌ HTTP {resp.status} at page {i}")
                    return False

                html = await resp.text()
                soup = BeautifulSoup(html, "html.parser")
                link_cars = extract_links_bonbanh(soup)

                if not link_cars:
                    print(f"⚠️ No products found on page {i}")
                    return False

                before = len(link_set_bonbanh)
                for link in link_cars:
                    link_set_bonbanh.add(link)
                after = len(link_set_bonbanh)

                if after == before:
                    no_new_count += 1
                    print(f"⚠️ Page {i}: no new links ({no_new_count}/{MAX_NO_NEW})")
                else:
                    no_new_count = 0
                    print(f"✅ Page {i} done. Added {after - before} new products.")

                if no_new_count >= MAX_NO_NEW:
                    print(f"\n⛔ Stopping crawl: {MAX_NO_NEW} consecutive pages with no new links.")
                    return "STOP"

                return True

        except Exception as e:
            print(f"⚠️ Error at page {i}: {e}")
            return False

async def main():
    async with aiohttp.ClientSession() as session:
        for i in range(1, 150):
            result = await get_links_bonbanh(session, i)
            if result == "STOP":
                break

await main()
print(f"\n📦 Total product links collected from bonbanh: {len(link_set_bonbanh)}")

✅ Page 1 done. Added 20 new products.
✅ Page 2 done. Added 20 new products.
✅ Page 3 done. Added 20 new products.
✅ Page 4 done. Added 20 new products.
✅ Page 5 done. Added 20 new products.
✅ Page 6 done. Added 20 new products.
✅ Page 7 done. Added 20 new products.
✅ Page 8 done. Added 20 new products.
✅ Page 9 done. Added 20 new products.
✅ Page 10 done. Added 9 new products.
✅ Page 11 done. Added 17 new products.
✅ Page 12 done. Added 20 new products.
✅ Page 13 done. Added 20 new products.
✅ Page 14 done. Added 20 new products.
✅ Page 15 done. Added 20 new products.
✅ Page 16 done. Added 20 new products.
✅ Page 17 done. Added 20 new products.
✅ Page 18 done. Added 20 new products.
✅ Page 19 done. Added 20 new products.
✅ Page 20 done. Added 20 new products.
✅ Page 21 done. Added 20 new products.
✅ Page 22 done. Added 20 new products.
✅ Page 23 done. Added 20 new products.
✅ Page 24 done. Added 20 new products.
✅ Page 25 done. Added 20 new products.
✅ Page 26 done. Added 20 new products.
✅ Page 27 done. Added 20 new products.
✅ Page 28 done. Added 20 new products.
✅ Page 29 done. Added 20 new products.
✅ Page 30 done. Added 20 new products.
✅ Page 31 done. Added 20 new products.
✅ Page 32 done. Added 20 new products.
✅ Page 33 done. Added 20 new products.
✅ Page 34 done. Added 20 new products.
✅ Page 35 done. Added 20 new products.
✅ Page 36 done. Added 20 new products.
✅ Page 37 done. Added 12 new products.
✅ Page 38 done. Added 18 new products.
✅ Page 39 done. Added 20 new products.
✅ Page 40 done. Added 19 new products.
✅ Page 41 done. Added 20 new products.
✅ Page 42 done. Added 20 new products.
✅ Page 43 done. Added 20 new products.
✅ Page 44 done. Added 20 new products.
✅ Page 45 done. Added 20 new products.
✅ Page 46 done. Added 20 new products.
✅ Page 47 done. Added 20 new products.
✅ Page 48 done. Added 20 new products.
✅ Page 49 done. Added 20 new products.
✅ Page 50 done. Added 20 new products.
✅ Page 51 done. Added 20 new products.
✅ Page 52 done. Added 20 new products.
✅ Page 53 done. Added 20 new products.
✅ Page 54 done. Added 15 new products.
✅ Page 55 done. Added 20 new products.
✅ Page 56 done. Added 20 new products.
✅ Page 57 done. Added 20 new products.
✅ Page 58 done. Added 20 new products.
✅ Page 59 done. Added 20 new products.
✅ Page 60 done. Added 20 new products.
✅ Page 61 done. Added 20 new products.
✅ Page 62 done. Added 20 new products.
✅ Page 63 done. Added 20 new products.
✅ Page 64 done. Added 20 new products.
✅ Page 65 done. Added 20 new products.
✅ Page 66 done. Added 19 new products.
✅ Page 67 done. Added 20 new products.
✅ Page 68 done. Added 20 new products.
✅ Page 69 done. Added 20 new products.
✅ Page 70 done. Added 20 new products.
✅ Page 71 done. Added 20 new products.
✅ Page 72 done. Added 20 new products.
✅ Page 73 done. Added 20 new products.
✅ Page 74 done. Added 20 new products.
✅ Page 75 done. Added 20 new products.
✅ Page 76 done. Added 20 new products.
✅ Page 77 done. Added 20 new products.
✅ Page 78 done. Added 20 new products.
✅ Page 79 done. Added 20 new products.
✅ Page 80 done. Added 18 new products.
✅ Page 81 done. Added 20 new products.
✅ Page 82 done. Added 20 new products.
✅ Page 83 done. Added 20 new products.
✅ Page 84 done. Added 20 new products.
✅ Page 85 done. Added 20 new products.
✅ Page 86 done. Added 20 new products.
✅ Page 87 done. Added 20 new products.
✅ Page 88 done. Added 20 new products.
✅ Page 89 done. Added 20 new products.
✅ Page 90 done. Added 20 new products.
✅ Page 91 done. Added 20 new products.
✅ Page 92 done. Added 20 new products.
✅ Page 93 done. Added 20 new products.
✅ Page 94 done. Added 18 new products.
✅ Page 95 done. Added 14 new products.
✅ Page 96 done. Added 13 new products.
✅ Page 97 done. Added 20 new products.
✅ Page 98 done. Added 20 new products.
✅ Page 99 done. Added 20 new products.
✅ Page 100 done. Added 20 new products.
✅ Page 101 done. Added 20 new products.
✅ Page 102 done. Added 20 new products.
✅ Page 103 done. Added 20 new products.
✅ Page 104 done. Added 20 new products.
✅ Page 105 done. Added 20 new products.
✅ Page 106 done. Added 19 new products.
✅ Page 107 done. Added 20 new products.
✅ Page 108 done. Added 20 new products.
✅ Page 109 done. Added 20 new products.
✅ Page 110 done. Added 20 new products.
✅ Page 111 done. Added 19 new products.
✅ Page 112 done. Added 20 new products.
✅ Page 113 done. Added 20 new products.
✅ Page 114 done. Added 20 new products.
✅ Page 115 done. Added 20 new products.
✅ Page 116 done. Added 20 new products.
✅ Page 117 done. Added 20 new products.
✅ Page 118 done. Added 20 new products.
✅ Page 119 done. Added 19 new products.
✅ Page 120 done. Added 10 new products.
✅ Page 121 done. Added 20 new products.
✅ Page 122 done. Added 20 new products.
✅ Page 123 done. Added 20 new products.
✅ Page 124 done. Added 20 new products.
✅ Page 125 done. Added 20 new products.
✅ Page 126 done. Added 20 new products.
✅ Page 127 done. Added 20 new products.
✅ Page 128 done. Added 20 new products.
✅ Page 129 done. Added 20 new products.
✅ Page 130 done. Added 20 new products.
✅ Page 131 done. Added 20 new products.
✅ Page 132 done. Added 20 new products.
✅ Page 133 done. Added 20 new products.
✅ Page 134 done. Added 19 new products.
✅ Page 135 done. Added 16 new products.
✅ Page 136 done. Added 20 new products.
✅ Page 137 done. Added 20 new products.
✅ Page 138 done. Added 20 new products.
✅ Page 139 done. Added 20 new products.
✅ Page 140 done. Added 20 new products.
✅ Page 141 done. Added 20 new products.
✅ Page 142 done. Added 19 new products.
✅ Page 143 done. Added 19 new products.
✅ Page 144 done. Added 19 new products.
✅ Page 145 done. Added 20 new products.
✅ Page 146 done. Added 19 new products.
✅ Page 147 done. Added 18 new products.
✅ Page 148 done. Added 19 new products.
✅ Page 149 done. Added 19 new products.

📦 Total product links collected from bonbanh: 2906

In [ ]:
import math
links = list(link_set_bonbanh)
mid = math.ceil(len(links) / 2)

part1 = links[:mid]
part2 = links[mid:]

print(f"📌 Total link: {len(links)}")
print(f"➡️ Part 1: {len(part1)} links")
print(f"➡️ Part 2: {len(part2)} links")

📌 Tổng số link: 2906
➡️ Part 1: 1453 links
➡️ Part 2: 1453 links

In [35]:
def in4(soup):
    specs = {}
    name_tag = soup.find("div", class_="title")
    name = name_tag.find_next("h1").get_text(strip=True) if name_tag else None
    specs["Name"] = name

    spec_section = soup.find("div", class_="box_car_detail")
    if spec_section:
        rows = spec_section.find_all("div", class_="row")
        for row in rows:
            label_div = row.find("div", class_="label")
            value_div = row.find("div", class_="txt_input")
            if label_div and value_div:
                label = label_div.get_text(strip=True).replace(":", "")
                value = value_div.get_text(strip=True)
                specs[label] = value
    return specs

In [ ]:
semaphore = asyncio.Semaphore(random.randint(5, 10))
all_cars2 = []
MAX_RETRIES = 3
MISSING_NAME_LIMIT = 5
missing_name_count = 0

async def fetch_car_detail(session, link, idx, total):
    global missing_name_count
    async with semaphore:
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                await asyncio.sleep(random.uniform(0.3, 1))
                async with session.get(link, headers=headers, proxy=proxy, timeout=20) as resp:
                    if resp.status != 200:
                        print(f"❌ [{idx}/{total}] HTTP {resp.status} at {link}")
                        continue

                    html = await resp.read()
                    html = html.decode('utf-8', errors='ignore')
                    soup = BeautifulSoup(html, "html.parser")

                    specs = in4(soup)

                    if not specs.get("Name"):
                        missing_name_count += 1
                        print(f"⚠️ [{idx}/{total}] Missing car name ({missing_name_count}/{MISSING_NAME_LIMIT})")
                    else:
                        print(f"✅ [{idx}/{total}] Done: {link}")

                    return specs

            except Exception as e:
                print(f"⚠️ [{idx}/{total}] Attempt {attempt}/{MAX_RETRIES} failed for {link}: {e}")
                if attempt < MAX_RETRIES:
                    await asyncio.sleep(2 * attempt) 
                else:
                    print(f"⛔ [{idx}/{total}] Giving up on {link} after {MAX_RETRIES} attempts.")
                    return None
    return None

async def main(ls):
    global all_cars2, missing_name_count
    async with aiohttp.ClientSession() as session:
        for idx, link in enumerate(ls, 1):
            if missing_name_count >= MISSING_NAME_LIMIT:
                print(f"\n⛔ Stopping: Exceeded {MISSING_NAME_LIMIT} cars missing names.")
                break

            spec = await fetch_car_detail(session, link, idx, len(ls))
            if spec:
                all_cars2.append(spec)

In [45]:
await main(part1)
print(f"📦 After Part 1: {len(all_cars2)} cars collected")

✅ [1/1453] Done: https://bonbanh.com/xe-ford-territory-titanium-x-1.5-at-2024-6234029
✅ [2/1453] Done: https://bonbanh.com/xe-kia-sedona-2.2-dat-luxury-2020-6347011
✅ [3/1453] Done: https://bonbanh.com/xe-ford-ranger-xls-2.0l-4x2-at-2023-6303558
✅ [4/1453] Done: https://bonbanh.com/xe-mg-5-1.5-mt-2024-6328665
✅ [5/1453] Done: https://bonbanh.com/xe-toyota-vios-1.5e-mt-2018-6215749
✅ [6/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-dac-biet-2025-5911890
✅ [7/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-2.0l-4x4-at-2025-6323204
✅ [8/1453] Done: https://bonbanh.com/xe-toyota-camry-2.5g-2014-6246587
✅ [9/1453] Done: https://bonbanh.com/xe-vinfast-vf8-plus-2025-6348713
✅ [10/1453] Done: https://bonbanh.com/xe-mg-zs-luxury-1.5-at-2wd-2022-5254462
✅ [11/1453] Done: https://bonbanh.com/xe-ford-ranger-raptor-2.0l-4x4-at-2025-6241129
✅ [12/1453] Done: https://bonbanh.com/xe-hyundai-i10-grand-1.2-at-2014-6095756
✅ [13/1453] Done: https://bonbanh.com/xe-landrover-range_rover_velar-r-dynamic-2.0-2018-6315723
✅ [14/1453] Done: https://bonbanh.com/xe-toyota-rav4-2.4-at-2008-6093509
✅ [15/1453] Done: https://bonbanh.com/xe-ford-everest-platinum-2.0l-4x4-at-2025-6067943
✅ [16/1453] Done: https://bonbanh.com/xe-ford-ranger-raptor-2.0l-4x4-at-2025-6356851
✅ [17/1453] Done: https://bonbanh.com/xe-honda-crv-2.0-at-2017-6348581
✅ [18/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2022-6317085
✅ [19/1453] Done: https://bonbanh.com/xe-hyundai-i10-grand-1.2-at-2018-6340072
✅ [20/1453] Done: https://bonbanh.com/xe-hyundai-kona-2.0-ath-2021-6338565
✅ [21/1453] Done: https://bonbanh.com/xe-nissan-navara-el-a-ivi-2.5-at-2wd-2020-6143543
✅ [22/1453] Done: https://bonbanh.com/xe-landrover-range_rover-autobiography-lwb-5.0-2014-6324162
✅ [23/1453] Done: https://bonbanh.com/xe-lexus-lx-570-2016-6285411
✅ [24/1453] Done: https://bonbanh.com/xe-mg-5-1.5-mt-2024-5991679
✅ [25/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2023-6188380
✅ [26/1453] Done: https://bonbanh.com/xe-bmw-4_series-430i-convertible-m-sport-2023-6305917
✅ [27/1453] Done: https://bonbanh.com/xe-toyota-vios-1.5g-2019-6148884
✅ [28/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.5l-htrac-2021-6166016
✅ [29/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-premium-2.0-at-2019-6357790
✅ [30/1453] Done: https://bonbanh.com/xe-toyota-hilux-2.8g-4x4-at-2018-6356659
✅ [31/1453] Done: https://bonbanh.com/xe-mazda-6-2.0-at-2016-6275012
✅ [32/1453] Done: https://bonbanh.com/xe-toyota-alphard-hev-2.5-at-2025-6194289
✅ [33/1453] Done: https://bonbanh.com/xe-kia-sportage-signature-2.0g-2023-6336984
✅ [34/1453] Done: https://bonbanh.com/xe-toyota-yaris-cross-1.5-d-cvt-2025-3491696
✅ [35/1453] Done: https://bonbanh.com/xe-kia-k3-premium-1.6-at-2021-6358511
✅ [36/1453] Done: https://bonbanh.com/xe-kia-sportage-signature-1.6t-awd-2023-6361791
✅ [37/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-at-2021-6335799
⚠️ [38/1453] Attempt 1/3 failed for https://bonbanh.com/xe-vinfast-lux_sa_2.0-2.0-at-2021-6295868: Server disconnected
✅ [38/1453] Done: https://bonbanh.com/xe-vinfast-lux_sa_2.0-2.0-at-2021-6295868
✅ [39/1453] Done: https://bonbanh.com/xe-hyundai-i10-grand-1.2-at-2020-6111505
✅ [40/1453] Done: https://bonbanh.com/xe-hyundai-santafe-2.4l-htrac-2019-6339249
✅ [41/1453] Done: https://bonbanh.com/xe-honda-city-rs-1.5-at-2022-6188241
✅ [42/1453] Done: https://bonbanh.com/xe-toyota-raize-g-1.0-cvt-2023-6265578
✅ [43/1453] Done: https://bonbanh.com/xe-toyota-corolla_cross-1.8v-2022-6190554
✅ [44/1453] Done: https://bonbanh.com/xe-honda-crv-2.4-at---tg-2016-6287318
✅ [45/1453] Done: https://bonbanh.com/xe-mazda-3-1.5l-luxury-2024-6356607
✅ [46/1453] Done: https://bonbanh.com/xe-kia-morning-mt-2019-6352458
✅ [47/1453] Done: https://bonbanh.com/xe-suzuki-swift-glx-1.2-at-2023-6337703
✅ [48/1453] Done: https://bonbanh.com/xe-volkswagen-teramont-2.0-at-2022-6331576
✅ [49/1453] Done: https://bonbanh.com/xe-kia-k3-premium-1.6-at-2024-6338879
✅ [50/1453] Done: https://bonbanh.com/xe-hyundai-accent-dac-biet-1.5-at-2025-6009018
✅ [51/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-3.2l-4x4-at-2016-6215968
✅ [52/1453] Done: https://bonbanh.com/xe-volkswagen-viloran-luxury-2024-6150203
✅ [53/1453] Done: https://bonbanh.com/xe-bmw-3_series-320i-sport-line-2024-6351438
✅ [54/1453] Done: https://bonbanh.com/xe-landrover-range_rover-autobiography-5.0-2014-6254788
✅ [55/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s63-amg-2007-6089205
✅ [56/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-at-2022-6164361
✅ [57/1453] Done: https://bonbanh.com/xe-toyota-fortuner-trd-sportivo-4x2-at-2016-6361766
✅ [58/1453] Done: https://bonbanh.com/xe-kia-sonet-premium-1.5-at-2022-6310935
✅ [59/1453] Done: https://bonbanh.com/xe-mazda-6-premium-2.0-at-2020-6237621
✅ [60/1453] Done: https://bonbanh.com/xe-suzuki-ciaz-1.4-at-2019-6087240
✅ [61/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-2.0l-4x4-at-2025-6271283
✅ [62/1453] Done: https://bonbanh.com/xe-mitsubishi-xforce-glx-2025-6305657
✅ [63/1453] Done: https://bonbanh.com/xe-landrover-range_rover_velar-r-dynamic-s-2.0-2022-6264521
✅ [64/1453] Done: https://bonbanh.com/xe-mg-5-luxury-1.5-at-2023-6331426
✅ [65/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.5l-htrac-2022-6361622
✅ [66/1453] Done: https://bonbanh.com/xe-audi-q7-45-tfsi-quattro-2021-5927153
✅ [67/1453] Done: https://bonbanh.com/xe-cadillac-escalade-premium-luxury-esv-awd-2021-6263899
✅ [68/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e250-2017-6355942
✅ [69/1453] Done: https://bonbanh.com/xe-mazda-3-1.5-at-2018-6215842
✅ [70/1453] Done: https://bonbanh.com/xe-mercedes_benz-g_class-g63-amg-2016-5996117
✅ [71/1453] Done: https://bonbanh.com/xe-kia-sedona-3.3-gat-premium-2019-6355806
✅ [72/1453] Done: https://bonbanh.com/xe-toyota-hilux-adventure-2.8l-4x4-at-2024-6278651
✅ [73/1453] Done: https://bonbanh.com/xe-suzuki-ertiga-sport-1.5-at-2022-6338637
✅ [74/1453] Done: https://bonbanh.com/xe-kia-sonet-premium-1.5-at-2022-6346359
✅ [75/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e200-edition-2015-6095835
✅ [76/1453] Done: https://bonbanh.com/xe-lexus-rx-350h-luxury-2025-6004491
✅ [77/1453] Done: https://bonbanh.com/xe-toyota-camry-2.0q-2022-6282949
✅ [78/1453] Done: https://bonbanh.com/xe-lexus-rx-350h-premium-2025-6138272
✅ [79/1453] Done: https://bonbanh.com/xe-honda-city-1.5-at-2017-6182452
✅ [80/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-200-2021-5857250
✅ [81/1453] Done: https://bonbanh.com/xe-lexus-nx-200t-2016-6361777
✅ [82/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c250-exclusive-2016-6222230
✅ [83/1453] Done: https://bonbanh.com/xe-ford-escape-xls-2.3l-4x2-at-2012-6355348
✅ [84/1453] Done: https://bonbanh.com/xe-mazda-2-sport-premium-2021-6273073
✅ [85/1453] Done: https://bonbanh.com/xe-toyota-fortuner-2.7v-4x2-at-2015-6339321
✅ [86/1453] Done: https://bonbanh.com/xe-honda-crv-l-2019-6317513
✅ [87/1453] Done: https://bonbanh.com/xe-vinfast-fadil-1.4-at-plus-2019-6325563
✅ [88/1453] Done: https://bonbanh.com/xe-honda-city-1.5-at-2017-6361805
✅ [89/1453] Done: https://bonbanh.com/xe-lexus-rx-350-premium-2025-5331000
✅ [90/1453] Done: https://bonbanh.com/xe-peugeot-3008-gt-2023-6296787
✅ [91/1453] Done: https://bonbanh.com/xe-ford-explorer-limited-2.3l-ecoboost-2019-6196040
✅ [92/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-nang-cao-2022-6306070
✅ [93/1453] Done: https://bonbanh.com/xe-toyota-prado-txl-2.7l-2014-6346783
✅ [94/1453] Done: https://bonbanh.com/xe-toyota-yaris-cross-1.5-d-cvt-2024-6293267
✅ [95/1453] Done: https://bonbanh.com/xe-toyota-land_cruiser-3.5-v6-2021-6361577
✅ [96/1453] Done: https://bonbanh.com/xe-suzuki-carry-pro-thung-bat-2025-6271134
✅ [97/1453] Done: https://bonbanh.com/xe-toyota-land_cruiser-4.6-v8-2019-6336924
✅ [98/1453] Done: https://bonbanh.com/xe-mazda-6-2.0-at-2016-6304669
✅ [99/1453] Done: https://bonbanh.com/xe-hyundai-accent-1.4-at-dac-biet-2021-6346598
✅ [100/1453] Done: https://bonbanh.com/xe-subaru-brz-2.4-at-eyesight-2025-6182708
✅ [101/1453] Done: https://bonbanh.com/xe-vinfast-vf3-plus-2024-6018556
✅ [102/1453] Done: https://bonbanh.com/xe-porsche-macan-s-2020-6337345
✅ [103/1453] Done: https://bonbanh.com/xe-kia-sonet-luxury-1.5-at-2025-6126949
✅ [104/1453] Done: https://bonbanh.com/xe-honda-hrv-g-2025-6137576
✅ [105/1453] Done: https://bonbanh.com/xe-mercedes_benz-v_class-v250-luxury-2020-6176306
✅ [106/1453] Done: https://bonbanh.com/xe-kia-soluto-1.4-mt-2020-6350157
✅ [107/1453] Done: https://bonbanh.com/xe-hyundai-elantra-2.0-at-2021-6327092
✅ [108/1453] Done: https://bonbanh.com/xe-mazda-cx8-premium-2021-6361646
✅ [109/1453] Done: https://bonbanh.com/xe-hyundai-kona-1.6-turbo-2018-6282220
✅ [110/1453] Done: https://bonbanh.com/xe-mercedes_benz-gls-450-4matic-2021-6310655
✅ [111/1453] Done: https://bonbanh.com/xe-kia-k3-premium-2.0-at-2022-6358108
✅ [112/1453] Done: https://bonbanh.com/xe-honda-crv-2.0-at-2016-6344926
✅ [113/1453] Done: https://bonbanh.com/xe-mazda-cx5-luxury-2.0-at-2025-6324814
✅ [114/1453] Done: https://bonbanh.com/xe-lexus-gx-460-2015-6361729
✅ [115/1453] Done: https://bonbanh.com/xe-lexus-rx-350-luxury-2023-6324900
✅ [116/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-mt-2021-6329638
✅ [117/1453] Done: https://bonbanh.com/xe-volkswagen-teramont-2.0-at-2022-6348312
✅ [118/1453] Done: https://bonbanh.com/xe-volkswagen-viloran-luxury-2024-6361773
✅ [119/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c200-avantgarde-plus-2021-6208671
✅ [120/1453] Done: https://bonbanh.com/xe-lexus-gx-460-2014-6293232
✅ [121/1453] Done: https://bonbanh.com/xe-suzuki-swift-glx-1.2-at-2023-6259444
✅ [122/1453] Done: https://bonbanh.com/xe-vinfast-vf6-eco-2025-6302877
✅ [123/1453] Done: https://bonbanh.com/xe-peugeot-2008-gt-line-1.2-at-2021-6348276
✅ [124/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-3.2l-4x4-at-2015-6284042
✅ [125/1453] Done: https://bonbanh.com/xe-toyota-camry-2.0g-2019-6357385
✅ [126/1453] Done: https://bonbanh.com/xe-bmw-6_series-640i-gran-coupe-2012-6286269
✅ [127/1453] Done: https://bonbanh.com/xe-mg-zs-standard-1.5-at-2wd-2024-6357808
✅ [128/1453] Done: https://bonbanh.com/xe-hyundai-kona-1.6-turbo-2018-6307114
✅ [129/1453] Done: https://bonbanh.com/xe-vinfast-vf8-plus-2025-6348709
✅ [130/1453] Done: https://bonbanh.com/xe-bmw-x5-xdrive40i-2019-6345559
✅ [131/1453] Done: https://bonbanh.com/xe-toyota-yaris-1.3-at-2010-6275031
✅ [132/1453] Done: https://bonbanh.com/xe-mitsubishi-attrage-1.2-mt-2024-5753726
✅ [133/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.2l-htrac-2022-6325587
✅ [134/1453] Done: https://bonbanh.com/xe-hyundai-tucson-1.6-at-turbo-htrac-dac-biet-2022-6296723
✅ [135/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c200-2012-6341472
✅ [136/1453] Done: https://bonbanh.com/xe-vinfast-vf5-plus-2025-6238300
✅ [137/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-200-2022-6313730
✅ [138/1453] Done: https://bonbanh.com/xe-mitsubishi-outlander-premium-2.0-cvt-2022-6304836
✅ [139/1453] Done: https://bonbanh.com/xe-ford-everest-ambiente-2.0l-4x2-at-2025-5082696
✅ [140/1453] Done: https://bonbanh.com/xe-mitsubishi-outlander-2.0-cvt-2020-6206356
✅ [141/1453] Done: https://bonbanh.com/xe-hyundai-venue-1.0-t-gdi-dac-biet-2025-5783119
✅ [142/1453] Done: https://bonbanh.com/xe-toyota-yaris-cross-1.5-d-cvt-2025-5186953
✅ [143/1453] Done: https://bonbanh.com/xe-kia-morning-s-at-2014-6352045
✅ [144/1453] Done: https://bonbanh.com/xe-volkswagen-viloran-premium-2024-5347857
✅ [145/1453] Done: https://bonbanh.com/xe-honda-accord-1.5-at-2021-6290255
✅ [146/1453] Done: https://bonbanh.com/xe-toyota-highlander-le-2.7-2015-6082844
✅ [147/1453] Done: https://bonbanh.com/xe-volkswagen-viloran-premium-2025-5295007
✅ [148/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-crdi-2019-6258881
✅ [149/1453] Done: https://bonbanh.com/xe-chevrolet-trailblazer-ltz-2.5l-vgt-4x4-at-2019-6356590
✅ [150/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-crdi-dac-biet-2025-6104184
✅ [151/1453] Done: https://bonbanh.com/xe-toyota-camry-2.5-hev-top-2025-6271424
✅ [152/1453] Done: https://bonbanh.com/xe-vinfast-lux_sa_2.0-premium-2.0-at-2021-6321978
✅ [153/1453] Done: https://bonbanh.com/xe-nissan-rogue-sl-2007-6225352
✅ [154/1453] Done: https://bonbanh.com/xe-toyota-vios-1.5g-2016-6347544
✅ [155/1453] Done: https://bonbanh.com/xe-mazda-3-1.5l-luxury-2019-6070559
✅ [156/1453] Done: https://bonbanh.com/xe-ford-ecosport-titanium-1.5l-at-2019-6341158
✅ [157/1453] Done: https://bonbanh.com/xe-hyundai-i10-grand-1.2-at-2020-6352085
✅ [158/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-at-2020-6239859
✅ [159/1453] Done: https://bonbanh.com/xe-peugeot-5008-gt-1.6-at-2021-6285602
✅ [160/1453] Done: https://bonbanh.com/xe-daewoo-nubira-ii-1.6-2001-6072916
✅ [161/1453] Done: https://bonbanh.com/xe-mazda-cx5-2.0-luxury-2019-6361836
✅ [162/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c300-amg-2021-6264577
✅ [163/1453] Done: https://bonbanh.com/xe-ford-tourneo-limousine-2.0-at-2019-6327864
✅ [164/1453] Done: https://bonbanh.com/xe-nissan-sunny-xv-premium-s-2017-6267381
✅ [165/1453] Done: https://bonbanh.com/xe-ford-territory-trend-1.5-at-2025-6351664
✅ [166/1453] Done: https://bonbanh.com/xe-mazda-cx5-premium-2.0-at-2025-6083546
✅ [167/1453] Done: https://bonbanh.com/xe-mercedes_benz-gle_class-gle-53-4matic+-coupe-amg-2022-6239933
✅ [168/1453] Done: https://bonbanh.com/xe-toyota-corolla_altis-1.8v-2023-6358405
✅ [169/1453] Done: https://bonbanh.com/xe-mazda-3-1.5l-luxury-2024-6358059
✅ [170/1453] Done: https://bonbanh.com/xe-hyundai-accent-dac-biet-1.5-at-2024-6347659
✅ [171/1453] Done: https://bonbanh.com/xe-volkswagen-tiguan-allspace-2021-6336167
✅ [172/1453] Done: https://bonbanh.com/xe-kia-carnival-signature-3.5g-2022-6315712
✅ [173/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.5l-htrac-2022-6360029
✅ [174/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.2l-htrac-2023-6281329
✅ [175/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450l-luxury-2017-6349847
✅ [176/1453] Done: https://bonbanh.com/xe-toyota-prado-txl-2.7l-2016-6248413
✅ [177/1453] Done: https://bonbanh.com/xe-lexus-rx-350-2022-5682398
✅ [178/1453] Done: https://bonbanh.com/xe-toyota-vios-e-1.5-mt-2025-6337863
✅ [179/1453] Done: https://bonbanh.com/xe-vinfast-vf7-plus-2024-6322573
✅ [180/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-cao-cap-2022-6317113
✅ [181/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-2.0-at-2021-6276745
✅ [182/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-200-4matic-2021-6250203
✅ [183/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450l-luxury-2017-6293773
✅ [184/1453] Done: https://bonbanh.com/xe-rolls_royce-phantom-6.7-v12-2009-6063898
✅ [185/1453] Done: https://bonbanh.com/xe-hyundai-tucson-1.6-at-turbo-2019-6245628
✅ [186/1453] Done: https://bonbanh.com/xe-ford-territory-titanium-x-1.5-at-2023-6304554
✅ [187/1453] Done: https://bonbanh.com/xe-ford-ecosport-titanium-1.5l-at-2017-6141074
✅ [188/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2020-6079080
✅ [189/1453] Done: https://bonbanh.com/xe-toyota-corolla_altis-2.0v-2015-6322798
✅ [190/1453] Done: https://bonbanh.com/xe-vinfast-lux_sa_2.0-premium-2.0-at-2019-6325083
✅ [191/1453] Done: https://bonbanh.com/xe-vinfast-fadil-1.4-at-2020-6198588
✅ [192/1453] Done: https://bonbanh.com/xe-subaru-crosstrek-2.0-i-s-eyesight-2024-6031146
✅ [193/1453] Done: https://bonbanh.com/xe-bmw-5_series-520i-luxury-line-2022-6346597
✅ [194/1453] Done: https://bonbanh.com/xe-toyota-wigo-1.2g-at-2019-6348020
✅ [195/1453] Done: https://bonbanh.com/xe-toyota-veloz-cross-1.5-cvt-2023-6284735
✅ [196/1453] Done: https://bonbanh.com/xe-toyota-innova-2.0e-2019-6256147
✅ [197/1453] Done: https://bonbanh.com/xe-toyota-land_cruiser-3.5-v6-2025-6163087
✅ [198/1453] Done: https://bonbanh.com/xe-toyota-wigo-1.2-at-2021-6347247
✅ [199/1453] Done: https://bonbanh.com/xe-peugeot-2008-gt-line-1.2-at-2022-6358441
✅ [200/1453] Done: https://bonbanh.com/xe-isuzu-mu-x-b7-plus-1.9-4x2-at-2023-6106157
✅ [201/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-crdi-dac-biet-2024-6356825
✅ [202/1453] Done: https://bonbanh.com/xe-mazda-cx5-2.0-at-awd-2015-6348916
✅ [203/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-tieu-chuan-2022-6361752
✅ [204/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2021-6099754
✅ [205/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s600-2007-6351996
✅ [206/1453] Done: https://bonbanh.com/xe-toyota-hilux-3.0g-4x4-at-2016-6206153
✅ [207/1453] Done: https://bonbanh.com/xe-mitsubishi-xforce-premium-2025-6116043
✅ [208/1453] Done: https://bonbanh.com/xe-ford-everest-titanium-plus-2.0l-4x4-at-2025-6323275
✅ [209/1453] Done: https://bonbanh.com/xe-ford-ranger-xls-2.2l-4x2-mt-2015-6338237
✅ [210/1453] Done: https://bonbanh.com/xe-vinfast-vf3-plus-2025-6339637
✅ [211/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-200-4matic-2024-6030147
✅ [212/1453] Done: https://bonbanh.com/xe-ford-everest-titanium-2.0l-4x4-at-2021-6312611
✅ [213/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c200-exclusive-2020-6186424
✅ [214/1453] Done: https://bonbanh.com/xe-vinfast-vf7-plus-2025-6348512
✅ [215/1453] Done: https://bonbanh.com/xe-vinfast-vf3-plus-2025-6353607
✅ [216/1453] Done: https://bonbanh.com/xe-landrover-range_rover-vogue-3.0-2019-5911362
✅ [217/1453] Done: https://bonbanh.com/xe-hyundai-stargazer-x-1.5-at-2025-5289989
✅ [218/1453] Done: https://bonbanh.com/xe-jaguar-xe-25t-prestige-2015-6113480
✅ [219/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c300-amg-2020-6331059
✅ [220/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s500l-2014-6237482
✅ [221/1453] Done: https://bonbanh.com/xe-hongqi-e-hs9-flagship-2021-6335725
✅ [222/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c200-2017-6355096
✅ [223/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2019-6312399
✅ [224/1453] Done: https://bonbanh.com/xe-kia-morning-s-at-2018-6163480
✅ [225/1453] Done: https://bonbanh.com/xe-ford-focus-trend-1.5l-2017-6347100
✅ [226/1453] Done: https://bonbanh.com/xe-jeep-wrangler-rubicon-2.0-4x4-at-2020-6320463
✅ [227/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c180-kompressor-2003-6311871
✅ [228/1453] Done: https://bonbanh.com/xe-toyota-fortuner-2.4g-4x2-mt-2020-6316959
✅ [229/1453] Done: https://bonbanh.com/xe-nissan-navara-el-premium-z-2019-6359460
✅ [230/1453] Done: https://bonbanh.com/xe-gac-m6-pro-gs-1.5t-2025-6300955
✅ [231/1453] Done: https://bonbanh.com/xe-mazda-cx-30-luxury-2.0-at-2022-6151493
⚠️ [232/1453] Attempt 1/3 failed for https://bonbanh.com/xe-volkswagen-teramont-president-2.0-at-2024-6317643: Server disconnected
✅ [232/1453] Done: https://bonbanh.com/xe-volkswagen-teramont-president-2.0-at-2024-6317643
✅ [233/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450l-2020-6225132
✅ [234/1453] Done: https://bonbanh.com/xe-honda-crv-2.4-at---tg-2017-6351740
✅ [235/1453] Done: https://bonbanh.com/xe-bmw-x5-xdrive40i-xline-2023-6297861
✅ [236/1453] Done: https://bonbanh.com/xe-mercedes_benz-gls-450-4matic-2021-6189108
✅ [237/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c180-2020-6318621
✅ [238/1453] Done: https://bonbanh.com/xe-porsche-cayenne-s-2012-6164453
✅ [239/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-at-2019-5918687
✅ [240/1453] Done: https://bonbanh.com/xe-volkswagen-teramont-2.0-at-2023-6307463
✅ [241/1453] Done: https://bonbanh.com/xe-honda-crv-l-2020-6285434
✅ [242/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-nang-cao-2022-6220904
✅ [243/1453] Done: https://bonbanh.com/xe-toyota-camry-le-2.4-2007-6242567
✅ [244/1453] Done: https://bonbanh.com/xe-toyota-prado-vx-2.7l-2020-6349762
✅ [245/1453] Done: https://bonbanh.com/xe-honda-crv-l-2018-6324037

In [46]:
await main(part2)
print(f"📦 After Part 2: {len(all_cars2)} cars collected")

✅ [1/1453] Done: https://bonbanh.com/xe-mercedes_benz-maybach-s450-4matic-2023-6257298
✅ [2/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c300-amg-2019-6246050
✅ [3/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c43-amg-4matic-2023-6361693
✅ [4/1453] Done: https://bonbanh.com/xe-toyota-yaris-1.3e-2014-6361812
✅ [5/1453] Done: https://bonbanh.com/xe-porsche-cayenne-3.0-v6-2021-6242577
✅ [6/1453] Done: https://bonbanh.com/xe-audi-a8-l-v8-4.0l-tfsi-2014-6152831
✅ [7/1453] Done: https://bonbanh.com/xe-volvo-xc90-t6-2.0-at-2015-6312386
✅ [8/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e180-2022-5504038
✅ [9/1453] Done: https://bonbanh.com/xe-honda-hrv-g-2024-5181000
✅ [10/1453] Done: https://bonbanh.com/xe-toyota-corolla_cross-1.8v-2025-6257183
✅ [11/1453] Done: https://bonbanh.com/xe-bmw-3_series-320i-2015-6122694
✅ [12/1453] Done: https://bonbanh.com/xe-mg-hs-1.5t-lux-2024-6183447
✅ [13/1453] Done: https://bonbanh.com/xe-porsche-cayenne-3.0-v6-2021-6315376
✅ [14/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c300-amg-2015-6352977
✅ [15/1453] Done: https://bonbanh.com/xe-vinfast-lux_sa_2.0-premium-2.0-at-2021-6209862
✅ [16/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e300-amg-2019-6298478
✅ [17/1453] Done: https://bonbanh.com/xe-honda-crv-2.4-at-2016-6309570
✅ [18/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2024-6272375
✅ [19/1453] Done: https://bonbanh.com/xe-toyota-innova-2.0g-2018-6355920
✅ [20/1453] Done: https://bonbanh.com/xe-mercedes_benz-g_class-g63-amg-2022-4661053
✅ [21/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-at-2020-6289979
✅ [22/1453] Done: https://bonbanh.com/xe-toyota-corolla_altis-2.0v-2010-6226220
✅ [23/1453] Done: https://bonbanh.com/xe-volkswagen-teramont-2.0-at-2022-6331558
✅ [24/1453] Done: https://bonbanh.com/xe-bmw-x3-xdrive30i-m-sport-2023-6325345
✅ [25/1453] Done: https://bonbanh.com/xe-ford-ranger-xl-2.2l-4x4-mt-2021-6361641
✅ [26/1453] Done: https://bonbanh.com/xe-lexus-es-250-2025-5480560
✅ [27/1453] Done: https://bonbanh.com/xe-hyundai-santafe-2.4l-4wd-2016-6352740
✅ [28/1453] Done: https://bonbanh.com/xe-chevrolet-aveo-lt-1.5-mt-2015-6213234
✅ [29/1453] Done: https://bonbanh.com/xe-peugeot-3008-gt-2022-6344739
✅ [30/1453] Done: https://bonbanh.com/xe-bmw-5_series-520i-2016-6137707
✅ [31/1453] Done: https://bonbanh.com/xe-suzuki-jimny-1.5l-4x4-at-2024-5851758
✅ [32/1453] Done: https://bonbanh.com/xe-volvo-xc60-t6-awd-inscription-2021-6327451
✅ [33/1453] Done: https://bonbanh.com/xe-vinfast-fadil-1.4-at-2019-6313088
✅ [34/1453] Done: https://bonbanh.com/xe-vinfast-vf3-plus-2025-6115369
✅ [35/1453] Done: https://bonbanh.com/xe-toyota-prado-vx-2.7l-2021-6211207
✅ [36/1453] Done: https://bonbanh.com/xe-mercedes_benz-gls-450-4matic-2021-6278679
✅ [37/1453] Done: https://bonbanh.com/xe-mazda-cx5-luxury-2.0-at-2021-6352787
✅ [38/1453] Done: https://bonbanh.com/xe-kia-k3-premium-1.6-at-2022-6298994
✅ [39/1453] Done: https://bonbanh.com/xe-kia-sorento-gat-2016-6349900
✅ [40/1453] Done: https://bonbanh.com/xe-toyota-camry-2.0e-2017-6157773
✅ [41/1453] Done: https://bonbanh.com/xe-mitsubishi-triton-4x4-at-mivec-premium-2021-6352186
✅ [42/1453] Done: https://bonbanh.com/xe-ford-ranger-sport-2.0l-4x4-at-2025-6273015
✅ [43/1453] Done: https://bonbanh.com/xe-hyundai-venue-1.0-t-gdi-dac-biet-2025-6104099
✅ [44/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-200-2021-6158324
✅ [45/1453] Done: https://bonbanh.com/xe-skoda-kodiaq-style-2.0-at-4wd-2024-5246164
✅ [46/1453] Done: https://bonbanh.com/xe-porsche-cayenne-gts-2008-6225649
✅ [47/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2019-6295714
✅ [48/1453] Done: https://bonbanh.com/xe-lexus-es-250-f-sport-2022-6162372
✅ [49/1453] Done: https://bonbanh.com/xe-kia-morning-si-at-2016-6280044
✅ [50/1453] Done: https://bonbanh.com/xe-toyota-camry-2.0q-2022-6355962
✅ [51/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e250-2009-6186275
✅ [52/1453] Done: https://bonbanh.com/xe-lexus-nx-350-f-sport-2023-6192171
✅ [53/1453] Done: https://bonbanh.com/xe-hyundai-santafe-2.2l-4wd-2017-6314389
✅ [54/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-200-2019-6307606
✅ [55/1453] Done: https://bonbanh.com/xe-toyota-corolla_altis-1.8v-2022-6352261
✅ [56/1453] Done: https://bonbanh.com/xe-toyota-veloz-cross-1.5-cvt-2024-6280631
✅ [57/1453] Done: https://bonbanh.com/xe-ford-territory-titanium-x-1.5-at-2025-5960808
✅ [58/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-2.0-at-2021-6361799
✅ [59/1453] Done: https://bonbanh.com/xe-audi-a6-s-line-40-tfsi-2025-6079705
✅ [60/1453] Done: https://bonbanh.com/xe-toyota-hilux-2.5e-4x2-mt-2009-6350643
✅ [61/1453] Done: https://bonbanh.com/xe-toyota-innova-cross-hev-2.0-cvt-2025-5243786
✅ [62/1453] Done: https://bonbanh.com/xe-hyundai-grand_starex-2.4-mt-2015-6282860
✅ [63/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-2.0l-4x2-at-2019-6307421
✅ [64/1453] Done: https://bonbanh.com/xe-lexus-rx-350-2016-6292207
✅ [65/1453] Done: https://bonbanh.com/xe-ford-ranger-xls-2.2l-4x2-at-2022-6351826
✅ [66/1453] Done: https://bonbanh.com/xe-toyota-vios-g-1.5-cvt-2024-6312602
✅ [67/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-tieu-chuan-2024-6331186
✅ [68/1453] Done: https://bonbanh.com/xe-toyota-prado-vx-2.7l-2019-6343563
✅ [69/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2023-6306472
✅ [70/1453] Done: https://bonbanh.com/xe-toyota-raize-g-1.0-cvt-2025-5841170
✅ [71/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e200-2017-6286448
✅ [72/1453] Done: https://bonbanh.com/xe-vinfast-vf3-plus-2025-6293440
✅ [73/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-2.0l-4x4-at-2020-6179942
✅ [74/1453] Done: https://bonbanh.com/xe-ford-everest-platinum-2.0l-4x4-at-2025-6356901
✅ [75/1453] Done: https://bonbanh.com/xe-peugeot-3008-gt-2022-6256819
✅ [76/1453] Done: https://bonbanh.com/xe-toyota-vios-1.5e-2012-6352527
✅ [77/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-premium-1.5-at-2025-6302320
✅ [78/1453] Done: https://bonbanh.com/xe-honda-crv-e-2021-6357890
✅ [79/1453] Done: https://bonbanh.com/xe-honda-crv-l-2018-6361763
✅ [80/1453] Done: https://bonbanh.com/xe-ford-ranger-xls-2.2l-4x2-at-2021-6247427
✅ [81/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-2.0l-4x4-at-2025-6324606
✅ [82/1453] Done: https://bonbanh.com/xe-suzuki-swift-glx-1.2-at-2019-6304930
✅ [83/1453] Done: https://bonbanh.com/xe-hyundai-santafe-premium-2.4l-htrac-2019-6357831
✅ [84/1453] Done: https://bonbanh.com/xe-honda-crv-2.4-at-2015-6314235
✅ [85/1453] Done: https://bonbanh.com/xe-mazda-3-1.5l-luxury-2023-6345432
✅ [86/1453] Done: https://bonbanh.com/xe-volvo-s90-ultra-b6-awd-2025-4666124
✅ [87/1453] Done: https://bonbanh.com/xe-toyota-vios-e-1.5-mt-2022-6240001
✅ [88/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-300-4matic-2017-6141467
✅ [89/1453] Done: https://bonbanh.com/xe-bmw-4_series-420i-convertible-2015-6302578
✅ [90/1453] Done: https://bonbanh.com/xe-toyota-camry-2.5q-2020-6089147
✅ [91/1453] Done: https://bonbanh.com/xe-toyota-yaris-cross-1.5-d-cvt-2025-5991634
✅ [92/1453] Done: https://bonbanh.com/xe-ford-everest-titanium-plus-2.0l-4x4-at-2023-6337293
✅ [93/1453] Done: https://bonbanh.com/xe-toyota-corolla_cross-1.8hev-2025-6316031
✅ [94/1453] Done: https://bonbanh.com/xe-isuzu-mu-x-b7-plus-1.9-4x2-at-2023-6106161
✅ [95/1453] Done: https://bonbanh.com/xe-ford-everest-titanium-plus-2.0l-4x4-at-2024-6290794
✅ [96/1453] Done: https://bonbanh.com/xe-mazda-6-2.0l-2017-6312159
✅ [97/1453] Done: https://bonbanh.com/xe-toyota-prado-vx-2.7l-2021-6341666
✅ [98/1453] Done: https://bonbanh.com/xe-kia-cerato-2.0-at-premium-2020-6239414
✅ [99/1453] Done: https://bonbanh.com/xe-mazda-3-1.5l-sport-luxury-2019-6331353
✅ [100/1453] Done: https://bonbanh.com/xe-bmw-x4-xdrive20i-m-sport-2020-6272649
✅ [101/1453] Done: https://bonbanh.com/xe-lexus-rx-300-2020-6347311
✅ [102/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-2.0l-4x4-at-2019-6259068
✅ [103/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-at-2022-6361878
✅ [104/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450l-luxury-2019-6356236
✅ [105/1453] Done: https://bonbanh.com/xe-hyundai-accent-cao-cap-1.5-at-2025-6009007
✅ [106/1453] Done: https://bonbanh.com/xe-ford-ecosport-titanium-1.5l-at-2017-6079246
✅ [107/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-2018-6212328
✅ [108/1453] Done: https://bonbanh.com/xe-toyota-corolla_altis-1.8e-at-2021-6332000
✅ [109/1453] Done: https://bonbanh.com/xe-mg-zs-standard-1.5-at-2wd-2024-6361169
✅ [110/1453] Done: https://bonbanh.com/xe-kia-cerato-1.6-at-luxury-2021-6207858
✅ [111/1453] Done: https://bonbanh.com/xe-mercedes_benz-glb-200-amg-2022-6361784
✅ [112/1453] Done: https://bonbanh.com/xe-ford-territory-titanium-x-1.5-at-2024-6079333
✅ [113/1453] Done: https://bonbanh.com/xe-byd-dolphin-glx-2024-6132742
✅ [114/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c300-amg-2019-6118065
✅ [115/1453] Done: https://bonbanh.com/xe-toyota-yaris-cross-1.5-d-cvt-2024-6139610
✅ [116/1453] Done: https://bonbanh.com/xe-mitsubishi-triton-athlete-4wd-at-2024-6346833
✅ [117/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e200-2019-6307838
✅ [118/1453] Done: https://bonbanh.com/xe-chevrolet-captiva-ltz-2.4-at-2007-6270470
✅ [119/1453] Done: https://bonbanh.com/xe-mazda-3-1.5l-sport-luxury-2020-6282684
✅ [120/1453] Done: https://bonbanh.com/xe-lexus-es-250-f-sport-2025-5963522
✅ [121/1453] Done: https://bonbanh.com/xe-toyota-wigo-g-1.2-at-2025-5841200
✅ [122/1453] Done: https://bonbanh.com/xe-porsche-cayman-2.7-at-2015-6351808
✅ [123/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e400-amg-cabriolet-2015-6133814
✅ [124/1453] Done: https://bonbanh.com/xe-mercedes_benz-maybach-s450-4matic-2017-6324708
✅ [125/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c300-amg-2015-6232211
✅ [126/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.5l-htrac-2024-6350108
✅ [127/1453] Done: https://bonbanh.com/xe-lexus-rx-350-awd-2010-6356376
✅ [128/1453] Done: https://bonbanh.com/xe-volkswagen-tiguan-allspace-luxury-2019-6337255
✅ [129/1453] Done: https://bonbanh.com/xe-ssangyong-musso-libero-2.3-at-2004-6233732
✅ [130/1453] Done: https://bonbanh.com/xe-ford-ecosport-titanium-1.5l-at-2020-6350979
✅ [131/1453] Done: https://bonbanh.com/xe-kia-sedona-platinum-d-2018-6000608
✅ [132/1453] Done: https://bonbanh.com/xe-ford-explorer-limited-2.3l-ecoboost-2023-6332527
✅ [133/1453] Done: https://bonbanh.com/xe-porsche-panamera-turbo-s-2021-6257327
✅ [134/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450l-luxury-2019-6356673
✅ [135/1453] Done: https://bonbanh.com/xe-toyota-corolla_altis-1.8g-at-2021-6164696
✅ [136/1453] Done: https://bonbanh.com/xe-toyota-vios-e-1.5-mt-2025-5024544
✅ [137/1453] Done: https://bonbanh.com/xe-mazda-cx5-premium-2.0-at-2022-6325045
✅ [138/1453] Done: https://bonbanh.com/xe-toyota-corolla_cross-1.8v-2022-6358212
✅ [139/1453] Done: https://bonbanh.com/xe-toyota-veloz-cross-top-1.5-cvt-2023-6353208
✅ [140/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-tieu-chuan-2025-6283787
✅ [141/1453] Done: https://bonbanh.com/xe-vinfast-fadil-tieu-chuan-1.4-at-2022-6202573
✅ [142/1453] Done: https://bonbanh.com/xe-toyota-vios-g-1.5-cvt-2021-6334513
✅ [143/1453] Done: https://bonbanh.com/xe-lexus-es-250-f-sport-2025-6350503
✅ [144/1453] Done: https://bonbanh.com/xe-toyota-corolla_altis-1.8g-at-2021-6359451
✅ [145/1453] Done: https://bonbanh.com/xe-kia-cerato-2.0-at-premium-2021-6358312
✅ [146/1453] Done: https://bonbanh.com/xe-mg-5-standard-1.5-at-2024-5182627
✅ [147/1453] Done: https://bonbanh.com/xe-honda-city-rs-1.5-at-2025-6349765
✅ [148/1453] Done: https://bonbanh.com/xe-ford-territory-titanium-1.5-at-2024-6348077
✅ [149/1453] Done: https://bonbanh.com/xe-mazda-cx-30-premium-2.0-at-2025-3789817
✅ [150/1453] Done: https://bonbanh.com/xe-mercedes_benz-c_class-c300-amg-2014-6333352
✅ [151/1453] Done: https://bonbanh.com/xe-porsche-cayenne-turbo-diesel-2010-6284679
✅ [152/1453] Done: https://bonbanh.com/xe-kia-k3-premium-2.0-at-2022-6150773
✅ [153/1453] Done: https://bonbanh.com/xe-kia-carnival-signature-2.2d-2022-6147756
✅ [154/1453] Done: https://bonbanh.com/xe-toyota-vios-1.5e-mt-2018-6351377
✅ [155/1453] Done: https://bonbanh.com/xe-lexus-es-300h-2025-6120469
✅ [156/1453] Done: https://bonbanh.com/xe-toyota-corolla_cross-1.8v-2024-6336132
✅ [157/1453] Done: https://bonbanh.com/xe-toyota-camry-2.5q-2022-6117184
✅ [158/1453] Done: https://bonbanh.com/xe-mg-hs-1.5t-lux-2024-6324208
✅ [159/1453] Done: https://bonbanh.com/xe-ford-territory-titanium-x-1.5-at-2024-6319645
✅ [160/1453] Done: https://bonbanh.com/xe-volkswagen-teramont-2.0-at-2022-5515708
✅ [161/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450-4matic-luxury-2022-6361579
✅ [162/1453] Done: https://bonbanh.com/xe-lexus-rx-300-2022-6340486
✅ [163/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.2l-htrac-2023-6276881
✅ [164/1453] Done: https://bonbanh.com/xe-kia-carens-1.5d-premium-2022-6289403
✅ [165/1453] Done: https://bonbanh.com/xe-toyota-veloz-cross-top-1.5-cvt-2022-6300874
✅ [166/1453] Done: https://bonbanh.com/xe-hyundai-accent-1.4-at-dac-biet-2021-6342077
✅ [167/1453] Done: https://bonbanh.com/xe-hyundai-elantra-1.6-at-dac-biet-2022-6348532
✅ [168/1453] Done: https://bonbanh.com/xe-toyota-yaris-cross-1.5-d-cvt-2024-6336405
✅ [169/1453] Done: https://bonbanh.com/xe-ford-ranger-raptor-2.0l-4x4-at-2022-6270461
✅ [170/1453] Done: https://bonbanh.com/xe-skoda-kodiaq-ambition-1.4-at-2024-5264732
✅ [171/1453] Done: https://bonbanh.com/xe-toyota-corolla_cross-1.8hv-2021-6258771
✅ [172/1453] Done: https://bonbanh.com/xe-toyota-camry-2.5q-2013-6244098
✅ [173/1453] Done: https://bonbanh.com/xe-hyundai-santafe-cao-cap-2.2l-htrac-2022-6295193
✅ [174/1453] Done: https://bonbanh.com/xe-toyota-vios-1.5e-2016-6252738
✅ [175/1453] Done: https://bonbanh.com/xe-toyota-yaris-1.5g-2018-6287473
✅ [176/1453] Done: https://bonbanh.com/xe-kia-morning-van-1.0-at-2013-6361675
✅ [177/1453] Done: https://bonbanh.com/xe-honda-br_v-g-2025-6237297
✅ [178/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450l-2020-6322736
✅ [179/1453] Done: https://bonbanh.com/xe-mitsubishi-attrage-premium-1.2-cvt-2025-5515485
✅ [180/1453] Done: https://bonbanh.com/xe-ford-ranger-xls-2.2l-4x2-at-2018-6339740
✅ [181/1453] Done: https://bonbanh.com/xe-mercedes_benz-glb-200-amg-2021-6360264
✅ [182/1453] Done: https://bonbanh.com/xe-mazda-cx5-2.0-at-2014-6285186
✅ [183/1453] Done: https://bonbanh.com/xe-peugeot-3008-gt-2022-6310974
✅ [184/1453] Done: https://bonbanh.com/xe-kia-cerato-1.6-mt-2018-6339567
✅ [185/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-1.5-at-2019-6266106
✅ [186/1453] Done: https://bonbanh.com/xe-kia-sportage-2.0-at-2013-5995515
✅ [187/1453] Done: https://bonbanh.com/xe-hyundai-kona-2.0-ath-2020-6325675
✅ [188/1453] Done: https://bonbanh.com/xe-mitsubishi-mirage-1.2-at-2014-6246576
✅ [189/1453] Done: https://bonbanh.com/xe-kia-carnival-signature-2.2d-2022-6315136
✅ [190/1453] Done: https://bonbanh.com/xe-toyota-fortuner-2.4l-4x2-at-2022-6187118
✅ [191/1453] Done: https://bonbanh.com/xe-kia-sportage-signature-1.6t-awd-2023-6361769
✅ [192/1453] Done: https://bonbanh.com/xe-mg-5-luxury-1.5-at-2024-6338819
✅ [193/1453] Done: https://bonbanh.com/xe-bmw-3_series-330i-m-sport-2021-6356039
✅ [194/1453] Done: https://bonbanh.com/xe-hyundai-santafe-2.4l-2016-6159154
✅ [195/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-premium-1.5-at-2025-6114447
✅ [196/1453] Done: https://bonbanh.com/xe-kia-sonet-premium-1.5-at-2022-6361851
✅ [197/1453] Done: https://bonbanh.com/xe-hyundai-tucson-2.0-at-tieu-chuan-2021-6271525
✅ [198/1453] Done: https://bonbanh.com/xe-kia-sonet-premium-1.5-at-2022-6343963
✅ [199/1453] Done: https://bonbanh.com/xe-lexus-rx-300-2021-6238321
✅ [200/1453] Done: https://bonbanh.com/xe-lexus-lx-600-urban-2025-5485796
✅ [201/1453] Done: https://bonbanh.com/xe-lexus-lx-600-urban-2023-6303489
✅ [202/1453] Done: https://bonbanh.com/xe-toyota-camry-2.4g-2004-6303536
✅ [203/1453] Done: https://bonbanh.com/xe-peugeot-3008-1.6-at-2018-6347675
✅ [204/1453] Done: https://bonbanh.com/xe-rolls_royce-phantom-6.7-v12-2009-6325219
✅ [205/1453] Done: https://bonbanh.com/xe-toyota-fortuner-2.7v-4x2-at-2019-6304890
✅ [206/1453] Done: https://bonbanh.com/xe-hyundai-elantra-1.6-at-2019-6347843
✅ [207/1453] Done: https://bonbanh.com/xe-ford-everest-titanium-2.0l-4x2-at-2023-6358351
✅ [208/1453] Done: https://bonbanh.com/xe-toyota-prado-txl-2.7l-2014-6300509
✅ [209/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s450l-2017-6119014
✅ [210/1453] Done: https://bonbanh.com/xe-toyota-fortuner-2.7v-4x2-at-2015-6305896
⚠️ [211/1453] Attempt 1/3 failed for https://bonbanh.com/xe-mazda-cx5-2.0-at-2019-6358300: Server disconnected
✅ [211/1453] Done: https://bonbanh.com/xe-mazda-cx5-2.0-at-2019-6358300
✅ [212/1453] Done: https://bonbanh.com/xe-mitsubishi-xpander-cross-1.5-at-2021-6262015
✅ [213/1453] Done: https://bonbanh.com/xe-mercedes_benz-e_class-e300-amg-2023-6244796
✅ [214/1453] Done: https://bonbanh.com/xe-hyundai-i30-cw-1.6-at-2009-6145910
✅ [215/1453] Done: https://bonbanh.com/xe-mitsubishi-outlander-2.0-cvt-2022-6235527
✅ [216/1453] Done: https://bonbanh.com/xe-vinfast-fadil-nang-cao-1.4-at-2022-6330579
✅ [217/1453] Done: https://bonbanh.com/xe-toyota-innova-2.0e-2020-6346207
✅ [218/1453] Done: https://bonbanh.com/xe-ford-ranger-wildtrak-2.0l-4x4-at-2025-6323192
✅ [219/1453] Done: https://bonbanh.com/xe-toyota-innova-2.0e-2018-6281569
✅ [220/1453] Done: https://bonbanh.com/xe-kia-rio-1.4-at-2016-6330774
✅ [221/1453] Done: https://bonbanh.com/xe-mercedes_benz-glc-200-4matic-2022-6224070
✅ [222/1453] Done: https://bonbanh.com/xe-ford-ranger-xls-2.0l-4x2-at-2022-6293110
✅ [223/1453] Done: https://bonbanh.com/xe-mercedes_benz-s_class-s500l-2013-6141121
✅ [224/1453] Done: https://bonbanh.com/xe-mitsubishi-outlander-2.4-cvt-premium-2018-6296954
✅ [225/1453] Done: https://bonbanh.com/xe-landrover-range_rover-autobiography-lwb-5.0-2014-6106674
✅ [226/1453] Done: https://bonbanh.com/xe-toyota-fortuner-legender-2.4l-4x2-at-2022-6113186
✅ [227/1453] Done: https://bonbanh.com/xe-toyota-corolla_cross-1.8v-2025-6076861
✅ [228/1453] Done: https://bonbanh.com/xe-isuzu-mu-x-3.0l-4x4-at-2019-6361825
✅ [229/1453] Done: https://bonbanh.com/xe-thaco-towner--2015-6351345
✅ [230/1453] Done: https://bonbanh.com/xe-kia-carnival-premium-2.2d-2022-6351771
✅ [231/1453] Done: https://bonbanh.com/xe-mg-g50-1.5-mt-com-2025-6361722
✅ [232/1453] Done: https://bonbanh.com/xe-ford-explorer-limited-2.3l-ecoboost-2017-6280791
✅ [233/1453] Done: https://bonbanh.com/xe-volvo-xc90-ultimate-b6-awd-2022-6280382
✅ [234/1453] Done: https://bonbanh.com/xe-hyundai-creta-cao-cap-1.5-at-2022-6157398
✅ [235/1453] Done: https://bonbanh.com/xe-mercedes_benz-glk_class-glk300-4matic-2012-6341690
✅ [236/1453] Done: https://bonbanh.com/xe-toyota-yaris-cross-1.5-d-cvt-2025-5625730
✅ [237/1453] Done: https://bonbanh.com/xe-vinfast-vf8-eco-2023-6351732
✅ [238/1453] Done: https://bonbanh.com/xe-hyundai-i10-grand-1.2-at-2017-6302165
✅ [239/1453] Done: https://bonbanh.com/xe-volvo-xc60-ultimate-bright-b6-awd-2023-6323641
✅ [240/1453] Done: https://bonbanh.com/xe-mazda-cx5-2.0-at-2014-6351133
✅ [241/1453] Done: https://bonbanh.com/xe-vinfast-fadil-nang-cao-1.4-at-2022-6209736
✅ [242/1453] Done: https://bonbanh.com/xe-mercedes_benz-glb-35-4matic-2024-5724632
✅ [243/1453] Done: https://bonbanh.com/xe-kia-seltos-premium-1.4-at-2022-6345135
✅ [244/1453] Done: https://bonbanh.com/xe-vinfast-lux_a_2.0-plus-2.0-at-2021-6345770
✅ [245/1453] Done: https://bonbanh.com/xe-toyota-camry-2.5-hev-top-2025-6319191
✅ [246/1453] Done: https://bonbanh.com/xe-bentley-continental-gtc-2007-6107387
✅ [247/1453] Done: https://bonbanh.com/xe-ford-everest-wildtrak-2.0l-4x4-at-2023-6361875

In [47]:
df2 = pd.DataFrame(all_cars2)
df2.head()

,Name,Năm sản xuất,Tình trạng,Số Km đã đi,Xuất xứ,Kiểu dáng,Động cơ,Màu ngoại thất,Màu nội thất
0,Xe \n\t\t\t\n\t\t\t\t\t\t\tFord Territory \n\t...,2024,Xe đã dùng,"10,000 Km",Lắp ráp trong nước,SUV,Xăng 1.5 L,Trắng,Đen
1,Xe \n\t\t\t\n\t\t\t\t\t\t\tKia Sedona \n\t\t\t...,2020,Xe đã dùng,"60,000 Km",Lắp ráp trong nước,Van/Minivan,Dầu 2.2 L,Xanh,Kem
2,Xe \n\t\t\t\n\t\t\t\t\t\t\tFord Ranger \n\t\t\...,2023,Xe đã dùng,645 Km,Lắp ráp trong nước,Bán tải / Pickup,Dầu 2.0 L,Đỏ,Nâu
3,Xe \n\t\t\t\n\t\t\t\t\t\t\tMG 5 \n\t\t\t\t\t\t...,2024,Xe mới,NaN,Nhập khẩu,Sedan,Xăng 1.5 L,Đỏ,Kem
4,Xe \n\t\t\t\n\t\t\t\t\t\t\tToyota Vios \n\t\t\...,2018,Xe đã dùng,"69,000 Km",Lắp ráp trong nước,Sedan,Xăng 1.5 L,Cát,Ghi

In [ ]:
df2 = pd.DataFrame(all_cars2)
df2.head()

In [48]:
df2.to_sql("car_data2", engine, if_exists="replace", index=False)
print(f"✅ Saved {len(df2)} rows to PostgreSQL table 'car_data2'")

✅ Saved 2906 rows to PostgreSQL table 'car_data2'

link-page3 ="https://xe.chotot.com/mua-ban-oto?page=1"

In [7]:
def extract_links_chotot(soup):
    items = soup.find_all("div", class_="crd7gu7")
    links = []
    for item in items:
        a_tag = item.find_next("a")
        if a_tag and a_tag.get("href"):
            link = "https://xe.chotot.com" + a_tag.get("href")
            links.append(link)
    return links

In [8]:
class ChototCrawler:
    def __init__(self, max_no_new=3):
        self.semaphore = asyncio.Semaphore(random.randint(5, 10))
        self.link_set = set()
        self.no_new_count = 0
        self.MAX_NO_NEW = max_no_new

    async def get_links(self, session, page):
        url = f"https://xe.chotot.com/mua-ban-oto?page={page}"
        async with self.semaphore:
            try:
                await asyncio.sleep(random.uniform(0.5, 1.5))
                async with session.get(url, headers=headers, proxy=proxy, timeout=15) as resp:
                    if resp.status != 200:
                        print(f"❌ HTTP {resp.status} at page {page}")
                        return False

                    soup = BeautifulSoup(await resp.text(), "html.parser")
                    links = extract_links_chotot(soup)
                    if not links:
                        print(f"⚠️ No products found on page {page}")
                        return False

                    before = len(self.link_set)
                    self.link_set.update(links)
                    after = len(self.link_set)

                    if after == before:
                        self.no_new_count += 1
                        print(f"⚠️ Page {page}: no new links ({self.no_new_count}/{self.MAX_NO_NEW})")
                    else:
                        self.no_new_count = 0
                        print(f"✅ Page {page} done. Added {after - before} new products.")

                    if self.no_new_count >= self.MAX_NO_NEW:
                        print(f"\n⛔ Stopping crawl: {self.MAX_NO_NEW} consecutive pages with no new links.")
                        return "STOP"
                    return True
            except Exception as e:
                print(f"⚠️ Error at page {page}: {e}")
                return False

In [10]:
crawler = ChototCrawler()

async def main():
    async with aiohttp.ClientSession() as session:
        for batch_start in range(1, 500, 10):
            tasks = [crawler.get_links(session, i) for i in range(batch_start, batch_start + 10)]
            results = await asyncio.gather(*tasks)

            if "STOP" in results:
                break

await main()

print(f"\n📦 Total product links collected from chotot: {len(crawler.link_set)}")

✅ Page 3 done. Added 18 new products.
✅ Page 2 done. Added 23 new products.
✅ Page 4 done. Added 18 new products.
✅ Page 1 done. Added 24 new products.
✅ Page 5 done. Added 17 new products.
✅ Page 6 done. Added 12 new products.
✅ Page 8 done. Added 18 new products.
✅ Page 10 done. Added 18 new products.
✅ Page 9 done. Added 20 new products.
✅ Page 7 done. Added 19 new products.
✅ Page 15 done. Added 19 new products.
✅ Page 14 done. Added 18 new products.
✅ Page 11 done. Added 17 new products.
✅ Page 12 done. Added 19 new products.
✅ Page 13 done. Added 17 new products.
✅ Page 16 done. Added 17 new products.
✅ Page 18 done. Added 19 new products.
✅ Page 17 done. Added 15 new products.
✅ Page 20 done. Added 18 new products.
✅ Page 19 done. Added 19 new products.
✅ Page 25 done. Added 15 new products.
✅ Page 24 done. Added 18 new products.
✅ Page 22 done. Added 20 new products.
✅ Page 21 done. Added 18 new products.
✅ Page 23 done. Added 17 new products.
✅ Page 28 done. Added 15 new products.
✅ Page 27 done. Added 16 new products.
✅ Page 30 done. Added 18 new products.
✅ Page 26 done. Added 14 new products.
✅ Page 29 done. Added 19 new products.
✅ Page 32 done. Added 17 new products.
✅ Page 35 done. Added 18 new products.
✅ Page 31 done. Added 18 new products.
✅ Page 34 done. Added 19 new products.
✅ Page 33 done. Added 19 new products.
✅ Page 37 done. Added 20 new products.
✅ Page 39 done. Added 17 new products.
✅ Page 36 done. Added 16 new products.
✅ Page 40 done. Added 19 new products.
✅ Page 38 done. Added 17 new products.
✅ Page 42 done. Added 18 new products.
✅ Page 45 done. Added 17 new products.
✅ Page 43 done. Added 19 new products.
✅ Page 41 done. Added 17 new products.
✅ Page 44 done. Added 14 new products.
✅ Page 46 done. Added 19 new products.
✅ Page 47 done. Added 18 new products.
✅ Page 48 done. Added 18 new products.
✅ Page 50 done. Added 19 new products.
✅ Page 49 done. Added 15 new products.
✅ Page 52 done. Added 17 new products.
✅ Page 55 done. Added 19 new products.
✅ Page 51 done. Added 18 new products.
✅ Page 54 done. Added 15 new products.
✅ Page 53 done. Added 19 new products.
✅ Page 56 done. Added 18 new products.
✅ Page 58 done. Added 17 new products.
✅ Page 59 done. Added 16 new products.
✅ Page 57 done. Added 17 new products.
✅ Page 60 done. Added 16 new products.
✅ Page 62 done. Added 20 new products.
✅ Page 63 done. Added 19 new products.
✅ Page 64 done. Added 18 new products.
✅ Page 65 done. Added 18 new products.
✅ Page 61 done. Added 17 new products.
✅ Page 66 done. Added 18 new products.
✅ Page 68 done. Added 17 new products.
✅ Page 67 done. Added 18 new products.
✅ Page 69 done. Added 18 new products.
✅ Page 70 done. Added 17 new products.
✅ Page 72 done. Added 18 new products.
✅ Page 73 done. Added 14 new products.
✅ Page 71 done. Added 17 new products.
✅ Page 75 done. Added 16 new products.
✅ Page 77 done. Added 18 new products.
✅ Page 76 done. Added 18 new products.
✅ Page 79 done. Added 17 new products.
✅ Page 78 done. Added 18 new products.
✅ Page 80 done. Added 15 new products.
✅ Page 74 done. Added 18 new products.
✅ Page 82 done. Added 17 new products.
✅ Page 84 done. Added 17 new products.
✅ Page 83 done. Added 16 new products.
✅ Page 81 done. Added 17 new products.
✅ Page 85 done. Added 18 new products.
✅ Page 86 done. Added 19 new products.
✅ Page 88 done. Added 19 new products.
✅ Page 87 done. Added 17 new products.
✅ Page 89 done. Added 19 new products.
✅ Page 90 done. Added 17 new products.
✅ Page 92 done. Added 18 new products.
✅ Page 95 done. Added 19 new products.
✅ Page 94 done. Added 14 new products.
✅ Page 93 done. Added 19 new products.
✅ Page 97 done. Added 19 new products.
✅ Page 96 done. Added 17 new products.
✅ Page 98 done. Added 19 new products.
✅ Page 99 done. Added 18 new products.
✅ Page 100 done. Added 18 new products.
⚠️ Error at page 91:
✅ Page 101 done. Added 18 new products.
✅ Page 105 done. Added 15 new products.
✅ Page 104 done. Added 17 new products.
✅ Page 102 done. Added 17 new products.
✅ Page 103 done. Added 18 new products.
✅ Page 107 done. Added 16 new products.
✅ Page 106 done. Added 14 new products.
✅ Page 109 done. Added 16 new products.
✅ Page 110 done. Added 18 new products.
✅ Page 108 done. Added 16 new products.
✅ Page 113 done. Added 17 new products.
✅ Page 114 done. Added 16 new products.
✅ Page 111 done. Added 18 new products.
✅ Page 112 done. Added 17 new products.
✅ Page 115 done. Added 17 new products.
✅ Page 117 done. Added 15 new products.
✅ Page 116 done. Added 19 new products.
✅ Page 118 done. Added 17 new products.
✅ Page 120 done. Added 19 new products.
✅ Page 119 done. Added 19 new products.
✅ Page 121 done. Added 17 new products.
✅ Page 125 done. Added 16 new products.
✅ Page 124 done. Added 14 new products.
✅ Page 123 done. Added 17 new products.
✅ Page 122 done. Added 16 new products.
✅ Page 126 done. Added 19 new products.
✅ Page 127 done. Added 18 new products.
✅ Page 130 done. Added 17 new products.
✅ Page 128 done. Added 16 new products.
✅ Page 129 done. Added 18 new products.
✅ Page 131 done. Added 18 new products.
✅ Page 134 done. Added 19 new products.
✅ Page 132 done. Added 18 new products.
✅ Page 135 done. Added 18 new products.
✅ Page 133 done. Added 19 new products.
✅ Page 137 done. Added 20 new products.
✅ Page 138 done. Added 20 new products.
✅ Page 136 done. Added 16 new products.
✅ Page 139 done. Added 19 new products.
✅ Page 140 done. Added 20 new products.
✅ Page 142 done. Added 20 new products.
✅ Page 144 done. Added 19 new products.
✅ Page 141 done. Added 20 new products.
✅ Page 143 done. Added 18 new products.
✅ Page 146 done. Added 20 new products.
✅ Page 148 done. Added 20 new products.
✅ Page 147 done. Added 20 new products.
✅ Page 149 done. Added 19 new products.
✅ Page 150 done. Added 18 new products.
✅ Page 145 done. Added 20 new products.
✅ Page 153 done. Added 20 new products.
✅ Page 151 done. Added 20 new products.
✅ Page 155 done. Added 18 new products.
✅ Page 154 done. Added 20 new products.
✅ Page 156 done. Added 18 new products.
✅ Page 152 done. Added 20 new products.
✅ Page 157 done. Added 20 new products.
✅ Page 158 done. Added 18 new products.
✅ Page 159 done. Added 20 new products.
✅ Page 160 done. Added 19 new products.
✅ Page 165 done. Added 18 new products.
✅ Page 162 done. Added 19 new products.
✅ Page 163 done. Added 18 new products.
✅ Page 164 done. Added 18 new products.
✅ Page 166 done. Added 20 new products.
✅ Page 167 done. Added 18 new products.
✅ Page 168 done. Added 19 new products.
✅ Page 169 done. Added 20 new products.
✅ Page 170 done. Added 19 new products.
✅ Page 161 done. Added 19 new products.
✅ Page 174 done. Added 19 new products.
✅ Page 172 done. Added 18 new products.
✅ Page 173 done. Added 20 new products.
✅ Page 171 done. Added 20 new products.
✅ Page 175 done. Added 18 new products.
✅ Page 177 done. Added 20 new products.
✅ Page 176 done. Added 18 new products.
✅ Page 179 done. Added 18 new products.
✅ Page 178 done. Added 20 new products.
✅ Page 180 done. Added 15 new products.
✅ Page 185 done. Added 20 new products.
✅ Page 182 done. Added 19 new products.
✅ Page 181 done. Added 19 new products.
✅ Page 183 done. Added 17 new products.
✅ Page 184 done. Added 19 new products.
✅ Page 186 done. Added 19 new products.
✅ Page 190 done. Added 18 new products.
✅ Page 188 done. Added 19 new products.
✅ Page 189 done. Added 17 new products.
✅ Page 187 done. Added 18 new products.
✅ Page 194 done. Added 20 new products.
✅ Page 193 done. Added 16 new products.
✅ Page 192 done. Added 18 new products.
✅ Page 191 done. Added 17 new products.
✅ Page 195 done. Added 19 new products.
✅ Page 196 done. Added 19 new products.
✅ Page 198 done. Added 20 new products.
✅ Page 197 done. Added 19 new products.
✅ Page 199 done. Added 18 new products.
✅ Page 200 done. Added 18 new products.
✅ Page 205 done. Added 18 new products.
✅ Page 201 done. Added 20 new products.
✅ Page 202 done. Added 19 new products.
✅ Page 203 done. Added 12 new products.
✅ Page 204 done. Added 12 new products.
✅ Page 206 done. Added 20 new products.
✅ Page 207 done. Added 18 new products.
✅ Page 208 done. Added 20 new products.
✅ Page 210 done. Added 17 new products.
✅ Page 209 done. Added 16 new products.
✅ Page 211 done. Added 19 new products.
✅ Page 214 done. Added 20 new products.
✅ Page 213 done. Added 20 new products.
✅ Page 212 done. Added 20 new products.
✅ Page 215 done. Added 20 new products.
✅ Page 216 done. Added 19 new products.
✅ Page 217 done. Added 20 new products.
✅ Page 218 done. Added 19 new products.
✅ Page 220 done. Added 19 new products.
✅ Page 219 done. Added 18 new products.
✅ Page 221 done. Added 16 new products.
✅ Page 224 done. Added 19 new products.
✅ Page 225 done. Added 19 new products.
✅ Page 222 done. Added 20 new products.
✅ Page 223 done. Added 20 new products.
✅ Page 226 done. Added 18 new products.
✅ Page 228 done. Added 18 new products.
✅ Page 227 done. Added 20 new products.
✅ Page 230 done. Added 18 new products.
✅ Page 229 done. Added 19 new products.
✅ Page 233 done. Added 20 new products.
✅ Page 234 done. Added 20 new products.
✅ Page 231 done. Added 20 new products.
✅ Page 232 done. Added 16 new products.
✅ Page 235 done. Added 20 new products.
✅ Page 236 done. Added 20 new products.
✅ Page 238 done. Added 20 new products.
✅ Page 237 done. Added 19 new products.
✅ Page 239 done. Added 19 new products.
✅ Page 240 done. Added 18 new products.
✅ Page 245 done. Added 20 new products.
✅ Page 241 done. Added 18 new products.
✅ Page 242 done. Added 19 new products.
✅ Page 244 done. Added 18 new products.
✅ Page 243 done. Added 18 new products.
✅ Page 246 done. Added 19 new products.
✅ Page 247 done. Added 16 new products.
✅ Page 248 done. Added 19 new products.
✅ Page 249 done. Added 17 new products.
✅ Page 250 done. Added 16 new products.
✅ Page 252 done. Added 20 new products.
✅ Page 253 done. Added 18 new products.
✅ Page 254 done. Added 18 new products.
✅ Page 251 done. Added 18 new products.
✅ Page 255 done. Added 20 new products.
✅ Page 256 done. Added 20 new products.
✅ Page 257 done. Added 20 new products.
✅ Page 258 done. Added 19 new products.
✅ Page 259 done. Added 19 new products.
✅ Page 260 done. Added 20 new products.
✅ Page 263 done. Added 18 new products.
✅ Page 265 done. Added 19 new products.
✅ Page 261 done. Added 19 new products.
✅ Page 262 done. Added 20 new products.
✅ Page 266 done. Added 18 new products.
✅ Page 269 done. Added 17 new products.
✅ Page 268 done. Added 18 new products.
✅ Page 267 done. Added 16 new products.
✅ Page 270 done. Added 19 new products.
✅ Page 264 done. Added 20 new products.
✅ Page 274 done. Added 18 new products.
✅ Page 271 done. Added 20 new products.
✅ Page 275 done. Added 19 new products.
✅ Page 273 done. Added 20 new products.
✅ Page 272 done. Added 20 new products.
✅ Page 277 done. Added 20 new products.
✅ Page 276 done. Added 18 new products.
✅ Page 279 done. Added 20 new products.
✅ Page 278 done. Added 19 new products.
✅ Page 280 done. Added 20 new products.
✅ Page 281 done. Added 19 new products.
✅ Page 284 done. Added 18 new products.
✅ Page 285 done. Added 20 new products.
✅ Page 283 done. Added 19 new products.
✅ Page 282 done. Added 19 new products.
✅ Page 286 done. Added 18 new products.
✅ Page 288 done. Added 19 new products.
✅ Page 289 done. Added 19 new products.
✅ Page 287 done. Added 19 new products.
✅ Page 290 done. Added 19 new products.
✅ Page 292 done. Added 19 new products.
✅ Page 295 done. Added 20 new products.
✅ Page 294 done. Added 18 new products.
✅ Page 293 done. Added 19 new products.
✅ Page 291 done. Added 20 new products.
✅ Page 296 done. Added 19 new products.
✅ Page 298 done. Added 16 new products.
✅ Page 300 done. Added 19 new products.
✅ Page 297 done. Added 14 new products.
✅ Page 299 done. Added 17 new products.
✅ Page 305 done. Added 20 new products.
✅ Page 302 done. Added 18 new products.
✅ Page 301 done. Added 19 new products.
✅ Page 304 done. Added 20 new products.
✅ Page 303 done. Added 20 new products.
✅ Page 307 done. Added 17 new products.
✅ Page 306 done. Added 19 new products.
✅ Page 310 done. Added 20 new products.
✅ Page 308 done. Added 20 new products.
✅ Page 309 done. Added 20 new products.
✅ Page 312 done. Added 19 new products.
✅ Page 311 done. Added 19 new products.
✅ Page 313 done. Added 20 new products.
✅ Page 315 done. Added 20 new products.
✅ Page 314 done. Added 20 new products.
✅ Page 317 done. Added 20 new products.
✅ Page 316 done. Added 19 new products.
✅ Page 319 done. Added 20 new products.
✅ Page 318 done. Added 20 new products.
✅ Page 320 done. Added 19 new products.
✅ Page 325 done. Added 19 new products.
✅ Page 324 done. Added 20 new products.
✅ Page 321 done. Added 18 new products.
✅ Page 322 done. Added 19 new products.
✅ Page 323 done. Added 19 new products.
✅ Page 326 done. Added 19 new products.
✅ Page 327 done. Added 18 new products.
✅ Page 328 done. Added 20 new products.
✅ Page 329 done. Added 20 new products.
✅ Page 330 done. Added 20 new products.
✅ Page 333 done. Added 20 new products.
✅ Page 331 done. Added 20 new products.
✅ Page 334 done. Added 19 new products.
✅ Page 335 done. Added 20 new products.
✅ Page 332 done. Added 18 new products.
✅ Page 338 done. Added 18 new products.
✅ Page 336 done. Added 17 new products.
✅ Page 339 done. Added 19 new products.
✅ Page 337 done. Added 18 new products.
✅ Page 340 done. Added 16 new products.
✅ Page 345 done. Added 18 new products.
✅ Page 343 done. Added 19 new products.
✅ Page 342 done. Added 20 new products.
✅ Page 341 done. Added 17 new products.
✅ Page 346 done. Added 20 new products.
✅ Page 347 done. Added 20 new products.
✅ Page 348 done. Added 19 new products.
✅ Page 349 done. Added 16 new products.
✅ Page 350 done. Added 20 new products.
✅ Page 344 done. Added 19 new products.
✅ Page 355 done. Added 20 new products.
✅ Page 352 done. Added 20 new products.
✅ Page 354 done. Added 17 new products.
✅ Page 351 done. Added 17 new products.
✅ Page 353 done. Added 17 new products.
✅ Page 359 done. Added 19 new products.
✅ Page 357 done. Added 19 new products.
✅ Page 356 done. Added 18 new products.
✅ Page 358 done. Added 20 new products.
✅ Page 360 done. Added 20 new products.
✅ Page 365 done. Added 18 new products.
✅ Page 361 done. Added 18 new products.
✅ Page 363 done. Added 14 new products.
✅ Page 364 done. Added 12 new products.
✅ Page 362 done. Added 20 new products.
✅ Page 367 done. Added 18 new products.
✅ Page 369 done. Added 19 new products.
✅ Page 366 done. Added 19 new products.
✅ Page 370 done. Added 18 new products.
✅ Page 368 done. Added 18 new products.
✅ Page 375 done. Added 20 new products.
✅ Page 371 done. Added 19 new products.
✅ Page 372 done. Added 16 new products.
✅ Page 373 done. Added 14 new products.
✅ Page 374 done. Added 20 new products.
✅ Page 378 done. Added 20 new products.
✅ Page 376 done. Added 19 new products.
✅ Page 377 done. Added 18 new products.
✅ Page 380 done. Added 20 new products.
✅ Page 379 done. Added 19 new products.
✅ Page 384 done. Added 18 new products.
✅ Page 381 done. Added 20 new products.
✅ Page 385 done. Added 18 new products.
✅ Page 383 done. Added 18 new products.
✅ Page 382 done. Added 20 new products.
✅ Page 387 done. Added 18 new products.
✅ Page 388 done. Added 18 new products.
✅ Page 390 done. Added 19 new products.
✅ Page 386 done. Added 19 new products.
✅ Page 389 done. Added 19 new products.
✅ Page 393 done. Added 19 new products.
✅ Page 391 done. Added 19 new products.
✅ Page 395 done. Added 19 new products.
✅ Page 394 done. Added 19 new products.
✅ Page 392 done. Added 19 new products.
✅ Page 398 done. Added 19 new products.
✅ Page 397 done. Added 19 new products.
✅ Page 396 done. Added 19 new products.
✅ Page 399 done. Added 19 new products.
✅ Page 400 done. Added 19 new products.
✅ Page 402 done. Added 20 new products.
✅ Page 403 done. Added 19 new products.
✅ Page 404 done. Added 20 new products.
✅ Page 405 done. Added 19 new products.
✅ Page 401 done. Added 16 new products.
✅ Page 407 done. Added 19 new products.
✅ Page 406 done. Added 20 new products.
✅ Page 410 done. Added 17 new products.
✅ Page 408 done. Added 18 new products.
✅ Page 409 done. Added 20 new products.
✅ Page 411 done. Added 18 new products.
✅ Page 414 done. Added 19 new products.
✅ Page 415 done. Added 20 new products.
✅ Page 412 done. Added 20 new products.
✅ Page 413 done. Added 15 new products.
✅ Page 416 done. Added 19 new products.
✅ Page 417 done. Added 16 new products.
✅ Page 418 done. Added 19 new products.
✅ Page 419 done. Added 19 new products.
✅ Page 420 done. Added 19 new products.
✅ Page 421 done. Added 19 new products.
✅ Page 425 done. Added 20 new products.
✅ Page 423 done. Added 19 new products.
✅ Page 424 done. Added 19 new products.
✅ Page 422 done. Added 19 new products.
✅ Page 427 done. Added 17 new products.
✅ Page 426 done. Added 19 new products.
✅ Page 428 done. Added 18 new products.
✅ Page 429 done. Added 18 new products.
✅ Page 430 done. Added 18 new products.
✅ Page 435 done. Added 20 new products.
✅ Page 434 done. Added 20 new products.
✅ Page 432 done. Added 19 new products.
✅ Page 431 done. Added 18 new products.
✅ Page 433 done. Added 18 new products.
✅ Page 436 done. Added 17 new products.
✅ Page 438 done. Added 19 new products.
✅ Page 437 done. Added 18 new products.
✅ Page 439 done. Added 18 new products.
✅ Page 440 done. Added 19 new products.
✅ Page 443 done. Added 20 new products.
✅ Page 444 done. Added 19 new products.
✅ Page 442 done. Added 17 new products.
✅ Page 445 done. Added 19 new products.
✅ Page 441 done. Added 16 new products.
✅ Page 447 done. Added 20 new products.
✅ Page 448 done. Added 18 new products.
✅ Page 450 done. Added 17 new products.
✅ Page 446 done. Added 20 new products.
✅ Page 449 done. Added 19 new products.
✅ Page 455 done. Added 20 new products.
✅ Page 454 done. Added 20 new products.
✅ Page 452 done. Added 19 new products.
✅ Page 451 done. Added 19 new products.
✅ Page 453 done. Added 20 new products.
✅ Page 457 done. Added 19 new products.
✅ Page 456 done. Added 20 new products.
✅ Page 460 done. Added 18 new products.
✅ Page 459 done. Added 20 new products.
✅ Page 458 done. Added 19 new products.
✅ Page 462 done. Added 20 new products.
✅ Page 463 done. Added 20 new products.
✅ Page 465 done. Added 19 new products.
✅ Page 461 done. Added 17 new products.
✅ Page 464 done. Added 20 new products.
✅ Page 467 done. Added 20 new products.
✅ Page 469 done. Added 20 new products.
✅ Page 466 done. Added 19 new products.
✅ Page 468 done. Added 18 new products.
✅ Page 470 done. Added 19 new products.
✅ Page 472 done. Added 20 new products.
✅ Page 474 done. Added 20 new products.
✅ Page 473 done. Added 18 new products.
✅ Page 471 done. Added 18 new products.
✅ Page 475 done. Added 19 new products.
✅ Page 476 done. Added 20 new products.
✅ Page 477 done. Added 20 new products.
✅ Page 478 done. Added 19 new products.
✅ Page 479 done. Added 19 new products.
✅ Page 480 done. Added 18 new products.
✅ Page 481 done. Added 17 new products.
✅ Page 482 done. Added 18 new products.
✅ Page 485 done. Added 17 new products.
✅ Page 484 done. Added 19 new products.
✅ Page 487 done. Added 19 new products.
✅ Page 486 done. Added 20 new products.
✅ Page 488 done. Added 17 new products.
✅ Page 489 done. Added 19 new products.
✅ Page 490 done. Added 20 new products.
✅ Page 483 done. Added 17 new products.
✅ Page 491 done. Added 20 new products.
✅ Page 492 done. Added 19 new products.
✅ Page 495 done. Added 18 new products.
✅ Page 493 done. Added 20 new products.
✅ Page 494 done. Added 17 new products.
✅ Page 496 done. Added 19 new products.
✅ Page 498 done. Added 17 new products.
✅ Page 500 done. Added 20 new products.
✅ Page 497 done. Added 19 new products.
✅ Page 499 done. Added 18 new products.

📦 Total product links collected from chotot: 9189

In [28]:
def info(soup):
    specs = {}
    
    name_tag = soup.find("div", class_="r9vw5if")
    if not name_tag:
        return None
    
    name = name_tag.find_next("h1").get_text(strip=True)
    if not name:
        return None
    price_tag = soup.find("b", class_="p26z2wb")
    price = price_tag.get_text(strip=True) if price_tag else None

    specs["name"] = name
    specs["price"] = price


    details = soup.find_all("div", class_="p1ja3eq0")
    for detail in details:
        key_tag = detail.find("span", class_="bwq0cbs")
        if key_tag:
            key = key_tag.get_text(strip=True)
            value_tag = key_tag.find_next("span", class_="bwq0cbs")
            value = value_tag.get_text(strip=True) if value_tag else None
            specs[key] = value

    return specs

In [37]:
class CarDetailCrawler:
    def __init__(self, max_retries=3, missing_name_limit=15):
        self.semaphore = asyncio.Semaphore(random.randint(5, 10))
        self.all_cars3 = []
        self.max_retries = max_retries
        self.missing_name_limit = missing_name_limit
        self.missing_name_count = 0

    async def fetch_car_detail(self, session, link, idx, total):
        async with self.semaphore:
            for attempt in range(1, self.max_retries + 1):
                try:
                    async with session.get(link, headers=headers, proxy=proxy, timeout=20) as resp:
                        if resp.status != 200:
                            print(f"❌ [{idx}/{total}] HTTP {resp.status} at {link}")
                            continue

                        html = await resp.text(errors="ignore")
                        soup = BeautifulSoup(html, "html.parser")

                        specs = info(soup)

                        if not specs or not specs.get("name"):
                            self.missing_name_count += 1
                            print(f"⚠️ [{idx}/{total}] Missing car name ({self.missing_name_count}/{self.missing_name_limit})")
                        else:
                            print(f"✅ [{idx}/{total}] Done: {link}")
                            return specs
                except Exception as e:
                    print(f"⚠️ [{idx}/{total}] Attempt {attempt}/{self.max_retries} failed for {link}: {e}")
                    if attempt < self.max_retries:
                        await asyncio.sleep(2 * attempt) 
                    else:
                        print(f"⛔ [{idx}/{total}] Giving up on {link} after {self.max_retries} attempts.")
                        return None
        return None

    async def run(self, links):
        async with aiohttp.ClientSession() as session:
            for idx, link in enumerate(links, 1):
                if self.missing_name_count >= self.missing_name_limit:
                    print(f"\n⛔ Stopping: Exceeded {self.missing_name_limit} cars missing names.")
                    break

                spec = await self.fetch_car_detail(session, link, idx, len(links))
                if spec:
                    self.all_cars3.append(spec)

        return self.all_cars3

In [38]:
links = list(crawler.link_set)
total = len(links)
n = 5

chunk_size = total // n
remainder = total % n

lists = []
start = 0
for i in range(n):
    end = start + chunk_size + (1 if i < remainder else 0)
    lists.append(links[start:end])
    start = end

list1, list2, list3, list4, list5 = lists

print(len(list1), len(list2), len(list3), len(list4), len(list5))

1838 1838 1838 1838 1837

In [39]:
detail_chotot = CarDetailCrawler()
await detail_chotot.run(list1)

✅ [1/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/124229868.htm
✅ [2/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-vung-tau-ba-ria-vung-tau/126620318.htm
✅ [3/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-di-an-binh-duong/126674455.htm
✅ [4/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-6-tp-ho-chi-minh/126671722.htm
✅ [5/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-binh-chanh-tp-ho-chi-minh/126705109.htm
✅ [6/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-binh-chanh-tp-ho-chi-minh/126569677.htm
✅ [7/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-le-chan-hai-phong/125343532.htm
✅ [8/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126724741.htm
✅ [9/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126620137.htm
✅ [10/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cai-rang-can-tho/126687017.htm
✅ [11/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-thanh-tp-ho-chi-minh/126525010.htm
✅ [12/1838] Done: https://xe.chotot.com/mua-ban-oto-thi-xa-kinh-mon-hai-duong/125494805.htm
✅ [13/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-bien-hoa-dong-nai/126693518.htm
✅ [14/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/124811364.htm
✅ [15/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-10-tp-ho-chi-minh/124756234.htm
✅ [16/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-thanh-xuan-ha-noi/126389009.htm
✅ [17/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-bien-hoa-dong-nai/126467341.htm
✅ [18/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-thanh-xuan-ha-noi/119792496.htm
✅ [19/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/125088571.htm
✅ [20/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-buon-ma-thuot-dak-lak/123844846.htm
✅ [21/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-phu-nhuan-tp-ho-chi-minh/126752208.htm
✅ [22/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126368392.htm
✅ [23/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-bac-tu-liem-ha-noi/126750530.htm
✅ [24/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126697695.htm
✅ [25/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/125842989.htm
✅ [26/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-cu-kuin-dak-lak/126634426.htm
✅ [27/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-ninh-kieu-can-tho/126637546.htm
✅ [28/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cam-le-da-nang/126595239.htm
✅ [29/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-6-tp-ho-chi-minh/126672119.htm
✅ [30/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126628628.htm
✅ [31/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cai-rang-can-tho/126743698.htm
✅ [32/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126602617.htm
✅ [33/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126436040.htm
✅ [34/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-8-tp-ho-chi-minh/109067223.htm
✅ [35/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-go-vap-tp-ho-chi-minh/124922800.htm
✅ [36/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126606782.htm
✅ [37/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-thot-not-can-tho/126610524.htm
✅ [38/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-yen-the-bac-giang/126701079.htm
✅ [39/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-long-khanh-dong-nai/126694109.htm
✅ [40/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/123097295.htm
✅ [41/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-1-tp-ho-chi-minh/126622034.htm
✅ [42/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-hoai-duc-ha-noi/126447512.htm
✅ [43/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/126734693.htm
✅ [44/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-di-an-binh-duong/126676415.htm
✅ [45/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/126724834.htm
✅ [46/1838] Done: https://xe.chotot.com/mua-ban-oto-thi-xa-an-khe-gia-lai/126633938.htm
✅ [47/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-phu-nhuan-tp-ho-chi-minh/126176206.htm
✅ [48/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-binh-chanh-tp-ho-chi-minh/119881911.htm
✅ [49/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/126724462.htm
✅ [50/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-nha-trang-khanh-hoa/126616815.htm
✅ [51/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126644733.htm
✅ [52/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126603343.htm
✅ [53/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126732076.htm
✅ [54/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126389612.htm
✅ [55/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126616667.htm
✅ [56/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126605893.htm
✅ [57/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126216270.htm
✅ [58/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-long-bien-ha-noi/126671312.htm
✅ [59/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126700912.htm
✅ [60/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-thanh-tp-ho-chi-minh/126577279.htm
✅ [61/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/126743613.htm
✅ [62/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/125635087.htm
✅ [63/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/126540867.htm
✅ [64/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-1-tp-ho-chi-minh/126731683.htm
✅ [65/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-6-tp-ho-chi-minh/126666657.htm
✅ [66/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126698240.htm
✅ [67/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-6-tp-ho-chi-minh/126730639.htm
✅ [68/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-di-an-binh-duong/126511142.htm
✅ [69/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126586743.htm
✅ [70/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126603232.htm
✅ [71/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/125796185.htm
✅ [72/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126607058.htm
✅ [73/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-go-vap-tp-ho-chi-minh/118449895.htm
✅ [74/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126539065.htm
✅ [75/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126733748.htm#px=SR-stickyad-[PO-2][PL-top]
✅ [76/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126036265.htm
✅ [77/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-binh-chanh-tp-ho-chi-minh/126096437.htm
✅ [78/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-hoc-mon-tp-ho-chi-minh/125360682.htm
✅ [79/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-go-vap-tp-ho-chi-minh/126646592.htm
✅ [80/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-11-tp-ho-chi-minh/126245411.htm
✅ [81/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-ha-dong-ha-noi/126523966.htm
✅ [82/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/126592790.htm
✅ [83/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126106720.htm
✅ [84/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-rach-gia-kien-giang/126359718.htm
✅ [85/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-4-tp-ho-chi-minh/126722187.htm
✅ [86/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/126681843.htm
✅ [87/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thuan-an-binh-duong/126676998.htm
✅ [88/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-phu-nhuan-tp-ho-chi-minh/117458956.htm
✅ [89/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-thanh-tp-ho-chi-minh/126361465.htm
✅ [90/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-binh-chanh-tp-ho-chi-minh/125158974.htm
✅ [91/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/124617666.htm
✅ [92/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hai-ba-trung-ha-noi/126678688.htm
✅ [93/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126482013.htm
✅ [94/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-binh-tp-ho-chi-minh/126077241.htm
✅ [95/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126680584.htm
✅ [96/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126409954.htm
✅ [97/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/126191345.htm
✅ [98/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cai-rang-can-tho/126680845.htm
✅ [99/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/126365216.htm
✅ [100/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-3-tp-ho-chi-minh/126693229.htm
✅ [101/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/124707165.htm
✅ [102/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126373705.htm
✅ [103/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-go-vap-tp-ho-chi-minh/126315789.htm
✅ [104/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126672009.htm
✅ [105/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hai-chau-da-nang/126033267.htm
✅ [106/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-binh-tp-ho-chi-minh/126607783.htm
✅ [107/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-1-tp-ho-chi-minh/126742118.htm
✅ [108/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/125907579.htm
✅ [109/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-hoc-mon-tp-ho-chi-minh/125852328.htm
✅ [110/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/118616567.htm
✅ [111/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-nam-tu-liem-ha-noi/126609182.htm
✅ [112/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-chau-duc-ba-ria-vung-tau/126658800.htm
✅ [113/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126277118.htm
✅ [114/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-dong-anh-ha-noi/126320526.htm
✅ [115/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-ninh-kieu-can-tho/125741783.htm
✅ [116/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-binh-tp-ho-chi-minh/126571779.htm
✅ [117/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/125271042.htm
✅ [118/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126437567.htm
✅ [119/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thanh-hoa-thanh-hoa/126748189.htm
✅ [120/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126349447.htm
✅ [121/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-buon-ma-thuot-dak-lak/126721634.htm
✅ [122/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-bien-hoa-dong-nai/124764334.htm
✅ [123/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126745846.htm
✅ [124/1838] Done: https://xe.chotot.com/mua-ban-oto-thi-xa-binh-minh-vinh-long/126298216.htm
✅ [125/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126718421.htm
✅ [126/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cam-le-da-nang/126710532.htm
✅ [127/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-thanh-xuan-ha-noi/126634115.htm
✅ [128/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126709768.htm
✅ [129/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/123480690.htm
✅ [130/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-go-vap-tp-ho-chi-minh/125881492.htm
✅ [131/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/126611197.htm
✅ [132/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-long-bien-ha-noi/126607991.htm
✅ [133/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cam-le-da-nang/125774677.htm
✅ [134/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/125971112.htm
✅ [135/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126219595.htm
✅ [136/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-6-tp-ho-chi-minh/126733289.htm
✅ [137/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/126614431.htm
✅ [138/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-4-tp-ho-chi-minh/125539649.htm
✅ [139/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-go-vap-tp-ho-chi-minh/124263780.htm
✅ [140/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-nam-tu-liem-ha-noi/125879794.htm
✅ [141/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126310838.htm
✅ [142/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-bac-tan-uyen-binh-duong/126695612.htm
✅ [143/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/125537557.htm
✅ [144/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-long-xuyen-an-giang/126299870.htm
✅ [145/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-da-lat-lam-dong/126604363.htm
✅ [146/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-6-tp-ho-chi-minh/125319768.htm
✅ [147/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126602673.htm
✅ [148/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-ba-ria-ba-ria-vung-tau/126717425.htm
✅ [149/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-long-thanh-dong-nai/126643533.htm
✅ [150/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-thanh-tp-ho-chi-minh/123383223.htm
✅ [151/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-8-tp-ho-chi-minh/126313674.htm
✅ [152/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-ha-dong-ha-noi/126660229.htm
✅ [153/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-pleiku-gia-lai/126648119.htm
✅ [154/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-binh-tp-ho-chi-minh/126480897.htm
✅ [155/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-bien-hoa-dong-nai/124884828.htm
✅ [156/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-long-bien-ha-noi/126620762.htm
✅ [157/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126605413.htm
✅ [158/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/126724765.htm
✅ [159/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-6-tp-ho-chi-minh/126734738.htm
✅ [160/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126538762.htm
✅ [161/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/125949421.htm
✅ [162/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-1-tp-ho-chi-minh/126571220.htm
✅ [163/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-thanh-xuan-ha-noi/125484437.htm
✅ [164/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-10-tp-ho-chi-minh/121742872.htm
✅ [165/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cam-le-da-nang/126567662.htm
✅ [166/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-3-tp-ho-chi-minh/126734880.htm
✅ [167/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-dau-mot-binh-duong/126671602.htm
✅ [168/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/126654638.htm
✅ [169/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/126665777.htm
✅ [170/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126415501.htm
✅ [171/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126228926.htm
✅ [172/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-phu-nhuan-tp-ho-chi-minh/125493893.htm
✅ [173/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-bao-loc-lam-dong/126675530.htm
✅ [174/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-pleiku-gia-lai/126718224.htm
✅ [175/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-soc-son-ha-noi/124952384.htm
✅ [176/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/126736349.htm
✅ [177/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-phu-nhuan-tp-ho-chi-minh/125529576.htm
✅ [178/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thuan-an-binh-duong/126699728.htm
✅ [179/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-phu-nhuan-tp-ho-chi-minh/126401937.htm
✅ [180/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-binh-tp-ho-chi-minh/126531056.htm
✅ [181/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126168702.htm
✅ [182/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-cu-chi-tp-ho-chi-minh/120265877.htm
✅ [183/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126520458.htm
✅ [184/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-nam-tu-liem-ha-noi/126712521.htm
✅ [185/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126577954.htm
✅ [186/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-binh-chanh-tp-ho-chi-minh/126631342.htm
✅ [187/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126688626.htm
✅ [188/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/125668718.htm
✅ [189/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-binh-tp-ho-chi-minh/125959920.htm
✅ [190/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126501198.htm
✅ [191/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-tan-phu-tp-ho-chi-minh/126710351.htm
✅ [192/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hai-chau-da-nang/113988539.htm
✅ [193/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/124700153.htm
✅ [194/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-thanh-tp-ho-chi-minh/124814800.htm
✅ [195/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126300154.htm
✅ [196/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-7-tp-ho-chi-minh/126090884.htm
✅ [197/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/125795157.htm
✅ [198/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126626290.htm
✅ [199/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/125675536.htm
✅ [200/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126600677.htm
✅ [201/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/126510751.htm
✅ [202/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-dong-anh-ha-noi/124557115.htm
✅ [203/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126124178.htm
✅ [204/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126699172.htm
✅ [205/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-hoang-mai-ha-noi/126654596.htm
✅ [206/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-di-an-binh-duong/126664733.htm
✅ [207/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-binh-tan-tp-ho-chi-minh/125046071.htm
✅ [208/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-cau-giay-ha-noi/121829659.htm
✅ [209/1838] Done: https://xe.chotot.com/mua-ban-oto-huyen-cu-m-gar-dak-lak/126610643.htm
✅ [210/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-12-tp-ho-chi-minh/126712837.htm
✅ [211/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-long-bien-ha-noi/124184005.htm
✅ [212/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-thu-duc-tp-ho-chi-minh/126602841.htm
✅ [213/1838] Done: https://xe.chotot.com/mua-ban-oto-quan-dong-da-ha-noi/126741649.htm
✅ [214/1838] Done: https://xe.chotot.com/mua-ban-oto-thanh-pho-di-an-binh-duong/123637006.htm

CancelledError: